### ISSUE TITLE
Can't log in to Jellyfin from Kodi

### ISSUE THREAD

**Issue by DarkVirtue** [jellyfin/jellyfin-kodi#119]
**Describe the bug**
After upgrading to Jellyfin 10.4.0, when I open Kodi, it prompts for my username and password for the Jellyfin server. Entering the credentials and hitting "Sign in" seems to do nothing. The logs indicate a 500 error.

**To Reproduce**

1. Set up the Kodi plugin under a previous version of Jellyfin, suchas 10.3.7.
2. Use Jellyfin server 10.4.0.
3. Open Kodi. There will be an error message that it couldn't correct to Jellfyn.
4. There will be a login prompt a moment later.
5. Enter correct credentials.
6, Press "Sign in"

**Expected behavior**
Logging in should complete, or at least show the user an error message.

**Logs**
```
2019-10-07 10:14:54.918 T:139721208518400  NOTICE: Jellyfin.jellyfin.core.http -> ERROR::resources/lib/jellyfin/core/http.py:120 500 Server Error: Internal Server Error for url: https://{jellyfin-server}/emby/Users/AuthenticateByName
2019-10-07 10:14:54.919 T:139721208518400  NOTICE: Jellyfin.jellyfin.core.http -> ERROR::resources/lib/jellyfin/core/http.py:135 --[ 500 response ] 500 Server Error: Internal Server Error for url: https://{jellyfin-server}/emby/Users/AuthenticateByName
2019-10-07 10:14:54.921 T:139721208518400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/home/username/.kodi/addons/plugin.video.jellyfin/resources/lib/dialogs/loginmanual.py", line 84, in onClick
                                                elif self._login(user, password):
                                              File "/home/username/.kodi/addons/plugin.video.jellyfin/resources/lib/dialogs/loginmanual.py", line 122, in _login
                                                result = self.connect_manager.login(server, username, password)
                                              File "/home/username/.kodi/addons/plugin.video.jellyfin/resources/lib/jellyfin/core/connection_manager.py", line 130, in login
                                                self._on_authenticated(result, options)
                                              File "/home/username/.kodi/addons/plugin.video.jellyfin/resources/lib/jellyfin/core/connection_manager.py", line 585, in _on_authenticated
                                                self.config.data['auth.user_id'] = result['User']['Id']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<-
```

**System (please complete the following information):**
 - OS: Kubuntu 19.04
 - Jellyfin Version: 10.4.0
 - Kodi Version: 18.4
 - Addon Version: 0.3.4

**Comment by mcarlton00** [comment]
I'm not able to replicate this with the same kodi and JF versions.  If you reset the kodi database and try a fresh sync, does it fix the issue?

`Add-ons -> Jellyfin -> Perform local database reset`

ps: I edited your comment for easier reading of the log snippet

**Comment by DarkVirtue** [comment]
I got the same error and behavior after a local database reset.

In addition, this error is logged at the Jellyfin server:
`[2019-10-07 19:10:50.278 -04:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Common.Cryptography.PasswordHash.Parse(String storageString)
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

**Comment by mcarlton00** [comment]
Are you trying to connect to the server through a reverse proxy, or directly via IP address and port?

If you're connecting through an apache or nginx reverse proxy, it may be worth double checking your config.  Server 10.4 changed the `/embywebsocket` path to just `/socket`.  Updated docs can be found [here](https://jellyfin.org/docs/general/administration/reverse-proxy.html)

**Comment by DarkVirtue** [comment]
I am using a reverse proxy (HAProxy), but it's routing based on domain, not paths, so my setup shouldn't be affected by that change.

I can't log in to the web interface now either (I could right after the upgrade to 10.4, my session must have expired).

So this isn't an issue with the plugin, but with Jellyfin. I'll move this issue there. Thanks for the help!
