### ISSUE TITLE
Remove web service as means of caching images

### ISSUE THREAD

**Issue by TrueTechy** [jellyfin/jellyfin-kodi#120]
Running the addon on the xbox one means that kodi itself is running with restricted permissions and as such cannot do things like listening on ports it seems as the log file contains this error

```
2019-10-08 19:54:13.805 T:5924  NOTICE: JELLYFIN.webservice -> ERROR::resources\lib\webservice.py:51 [Errno 10013] A
                                            Traceback (most recent call last):
                                              File "resources\lib\webservice.py", line 46, in run
                                                server = HttpServer(('127.0.0.1', PORT), requestHandler)
                                              File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\SocketServer.py", line 417, in __init__
                                                self.server_bind()
                                              File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\BaseHTTPServer.py", line 108, in server_bind
                                                SocketServer.TCPServer.server_bind(self)
                                              File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\SocketServer.py", line 431, in server_bind
                                                self.socket.bind(self.server_address)
                                              File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\socket.py", line 228, in meth
                                                return getattr(self._sock,name)(*args)
                                            error: [Errno 10013] A
```

Don't know why the error message is cut off but googling it suggests it would be "An attempt was made to access a socket in a way forbidden by its access permissions" - https://stackoverflow.com/questions/2778840/socket-error-errno-10013-an-attempt-was-made-to-access-a-socket-in-a-way-forb

Though not entirely sure what this web service does (might have something to do with the "Play to" feature) this is mainly to track the issue for future reference

**Comment by TrueTechy** [comment]
![image](https://user-images.githubusercontent.com/23321780/66785165-5cdd5f80-eed4-11e9-91fe-6e69fd7c1b85.png)

Appears this web service is to allow artwork caching, not sure why it requires a web server to be running to achieve this though
