### ISSUE TITLE
Syncing results in Core dump

### ISSUE THREAD

**Issue by Uatschitchun** [jellyfin/jellyfin-kodi#126]
Syncing a fresh Kodi with Jellyfin

**To Reproduce**
Just syncing a large library

**Expected behavior**
No crashing of Jellyfin

**Logs**
```
[13:52:37] [FTL] Unhandled Exception
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```

**The relevant Kodi-log should be:**

```
2019-10-23 14:04:23.274 T:139795162437376  NOTICE: JELLYFIN.full_sync -> ERROR::resources/lib/full_sync.py:244 'auth.server-id'
                                            Traceback (most recent call last):
                                              File "resources/lib/full_sync.py", line 235, in process_library
                                                media[library['CollectionType']](library)
                                              File "resources/lib/helper/wrapper.py", line 40, in wrapper
                                                result = func(self, dialog=dialog, *args, **kwargs)
                                              File "resources/lib/full_sync.py", line 414, in music
                                                for songs in server.get_items(album['Id'], "Audio"):
                                              File "resources/lib/downloader.py", line 179, in get_items
                                                for items in _get_items(query):
                                              File "resources/lib/downloader.py", line 264, in _get_items
                                                result = _get(url, params, server_id=server_id) or {'Items': []}
                                              File "resources/lib/downloader.py", line 47, in _get
                                                return _http("GET", get_jellyfinserver_url(handler), {'params': params}, server_id)
                                              File "resources/lib/downloader.py", line 43, in _http
                                                return Jellyfin(server_id).http.request(request)
                                              File "resources/lib/jellyfin/core/http.py", line 103, in request
                                                self.client.callback("ServerUnreachable", {'ServerId': self.config.data['auth.server-id']})
                                            KeyError: 'auth.server-id'
2019-10-23 14:04:27.633 T:139789407631104  NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:65 [Errno 111] Connection refused
2019-10-23 14:04:32.887 T:139789407631104  NOTICE: JELLYFIN.jellyfin.core.ws_client -> INFO::resources/lib/jellyfin/core/ws_client.py:68 --->[ websocket ]
2019-10-23 14:05:29.567 T:139795162437376  NOTICE: JELLYFIN.full_sync -> ERROR::resources/lib/full_sync.py:249 full sync exited unexpectedly
2019-10-23 14:05:29.577 T:139795162437376  NOTICE: JELLYFIN.full_sync -> INFO::resources/lib/full_sync.py:567 --<[ fullsync ]
2019-10-23 14:05:29.583 T:139795162437376  NOTICE: JELLYFIN.library -> ERROR::resources/lib/library.py:332 'auth.server-id'
                                            Traceback (most recent call last):
                                              File "resources/lib/library.py", line 328, in startup
                                                sync.libraries()
                                              File "resources/lib/full_sync.py", line 97, in libraries
                                                self.start()
                                              File "resources/lib/full_sync.py", line 186, in start
                                                self.process_library(library)
                                              File "resources/lib/full_sync.py", line 235, in process_library
                                                media[library['CollectionType']](library)
                                              File "resources/lib/helper/wrapper.py", line 40, in wrapper
                                                result = func(self, dialog=dialog, *args, **kwargs)
                                              File "resources/lib/full_sync.py", line 414, in music
                                                for songs in server.get_items(album['Id'], "Audio"):
                                              File "resources/lib/downloader.py", line 179, in get_items
                                                for items in _get_items(query):
                                              File "resources/lib/downloader.py", line 264, in _get_items
                                                result = _get(url, params, server_id=server_id) or {'Items': []}
                                              File "resources/lib/downloader.py", line 47, in _get
                                                return _http("GET", get_jellyfinserver_url(handler), {'params': params}, server_id)
                                              File "resources/lib/downloader.py", line 43, in _http
                                                return Jellyfin(server_id).http.request(request)
                                              File "resources/lib/jellyfin/core/http.py", line 103, in request
                                                self.client.callback("ServerUnreachable", {'ServerId': self.config.data['auth.server-id']})
                                            KeyError: 'auth.server-id'

```

**System (please complete the following information):**
 - OS: Docker 
 - Jellyfin Version: 10.4.0
 - Kodi Version: 18.4
 - Addon Version: 0.3.4

**Comment by mcarlton00** [comment]
How large of a library are you talking about?  I have tens of thousands of items in my Jellyfin/Kodi libraries and haven't encountered this.

What device are you running Kodi on?

**Comment by Uatschitchun** [comment]
It's a kodi instance on my laptop (bionic) connected to jellyfin server over lan.
I got these core dumps about 10 times already when scanning audio library and its not even finished scanning artists with "A...".
So it's probably not a matter of how large the library is...

**Comment by mcarlton00** [comment]
It seems unlikely that library size is the cause.  Few more questions that might help track down what the root cause is:

* Does this only happen with Music, or does it also happen with Movies/TV Shows?
* How are you connecting to the server?  Are you going through through a reverse proxy of some kind, or hitting the server ports directly?
* Do you have a TLS/SSL certificate in place?

**Comment by Uatschitchun** [comment]
As far as it seems, it's only happening with Music

No proxy, just LAN with IP:8096

No certificate. The docker I'm running jellyfin in, is going linked with traefik as reverse proxy and LetsEncrypt certificate, but as I'm connecting through LAN and direkt ip:port, this shouldn't come to matter.

This is the docker-compose.yml:
```
version: '2'

services:
    jellyfin:
        image: 'jellyfin/jellyfin:latest'
        container_name: jellyfin
        restart: always
        user: 1000:1000
        ports:
            - 8096:8096
        expose:
            - 8096
        networks:
            - web
            - default
        volumes:
            - /media/8TB/:/media/8TB/:ro
            - /media/mp3/:/media/mp3/:ro
            - /home/user/Jellyfin/config/:/config:rw
            - /home/user/Jellyfin/cache/:/cache:rw
        environment:
            - TZ=Europe/Berlin
        devices:
            - /dev/dri:/dev/dri # For H/W transcoding
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:jellyfin.subdomain.duckdns.org"
            - "traefik.port=8096"
            - "traefik.backend=jellyfin"
            - "traefik.docker.network=web"
            - "traefik.frontend.entryPoints=https"
            - "traefik.frontend.headers.forceSTSHeader=true"
            - "traefik.frontend.headers.STSSeconds=315360000"
            - "traefik.frontend.headers.STSIncludeSubdomains=true"
            - "traefik.frontend.headers.STSPreload=true"

networks:
  web:
    external: true

```

**Comment by mcarlton00** [comment]
It being an issue in the sync queue plugin rather than this addon makes a lot more sense.  It seems like we're blocked waiting for upstream, but possibly we can find a workaround for the time being.  Do you know how many songs are in your music library?  There may be an upper limit to how many that can sync at one time and you could work around it by making multiple library folders

**Comment by Uatschitchun** [comment]
About 130k

**Comment by oddstr13** [comment]
Jellyfin for Kodi should never be able to crash the server.
This also looks like may be a .net core bug.

**Comment by dkanada** [comment]
> Jellyfin for Kodi should never be able to crash the server.

This is actually not true in practice. The Roku client was able to crash the server with a single API request before it was recently fixed.
