### ISSUE TITLE
discovery loop - music

### ISSUE THREAD

**Issue by bugsyb** [jellyfin/jellyfin-kodi#135]
Kodi v18.4 

Seems like the plugin got stuck in the discovery loop:
```
2019-11-05 01:08:58.389 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [1112/26/4089] e9a326eacf2e1646e422d8799b91ac64: 
2019-11-05 01:08:58.565 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [1113/26/4090] 4c3e4b06adf9be2b73256ba7eb6bbe25: 
2019-11-05 01:08:58.576 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [1114/26/4091] 3ddf5b7312a15f52618e325f643e0114: 
2019-11-05 01:08:58.586 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [1115/26/4092] 4ba72f5e56aaa66c4cb9af435c41a448: 
2019-11-05 01:08:58.599 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [1116/26/4093] a3edc49840673ceb9dabed04ad4e2f38: 
2019-11-05 01:08:58.609 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [1117/26/4094] 81f9629738dcbcac9200d0762ae46760: 
2019-11-05 01:08:58.619 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [1118/26/4095] b2a86caed893c13acbc7815ddca80812: 
2019-11-05 01:08:58.628 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [1119/26/4096] 7d6c0cd5b248087747c55d2a2bd5564c: 
2019-11-05 01:08:58.638 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [1120/26/4097] 7853f95f8acfa9b8bf596fe99d504657: 
2019-11-05 01:08:58.650 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [1121/26/4098] 0440786e2493876ec3cb3039d4fe5fd4: 
2019-11-05 01:08:58.927 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [978/26/3955] afaff07f9e42ef8f8b20e1491d865cab: 
2019-11-05 01:08:58.940 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:102 UPDATE artist [471] Moby: 846945aafbe73b678450c52c3a5388b3
2019-11-05 01:08:58.943 T:544915579024  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::resources/lib/objects/kodi/artwork.py:176 DELETE cached b/bde7348f.jpg
2019-11-05 01:08:58.944 T:544915579024  NOTICE: JELLYFIN.database -> INFO::resources/lib/database/__init__.py:179 [texture] 2 rows updated.
2019-11-05 01:08:58.953 T:544915579024  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::resources/lib/objects/kodi/artwork.py:67 UPDATE to kodi_id 471 art: http://mediateka.vpn:8096/jellyfin/emby/Items/846945aafbe73b678450c52c3a5388b3/Images/Backdrop/0?Format=original&Tag=e437d590b2c2661f378009758805bdf6
2019-11-05 01:08:58.955 T:544915579024  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::resources/lib/objects/kodi/artwork.py:157 -->[ q:artwork/544881477264 ]
2019-11-05 01:08:58.987 T:543548670096  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::resources/lib/objects/kodi/artwork.py:214 HTTPConnectionPool(host=u'localhost', port=8090): Read timed out. (read timeout=0.01)
                                            Traceback (most recent call last):
                                              File "resources/lib/objects/kodi/artwork.py", line 211, in run
                                                s.send(prep, timeout=(0.01, 0.01))
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host=u'localhost', port=8090): Read timed out. (read timeout=0.01)
2019-11-05 01:09:00.106 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:165 UPDATE album [26] Top 40 Singles: 47d289ce28c51186f0293c92010abbf2
2019-11-05 01:09:00.487 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [393/26/3370] 5bcca02d8c2b435fa2918c7f93d51702: 
2019-11-05 01:09:00.505 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [394/26/3371] 99294d968953ff43b74e4cdca92ee088: 
2019-11-05 01:09:00.519 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [395/26/3372] d4acbf6b91c7ee5cbd4221ae75388710: 
2019-11-05 01:09:00.536 T:544915579024  NOTICE: JELLYFIN.objects.music -> INFO::resources/lib/objects/music.py:317 UPDATE song [396/26/3373] 1f76e4ef69580e9389f463c9908c77f5: 
```
(titles removed)

```
2019-11-05 01:15:20.763 T:547857776784  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
```

Not sure how to further troubleshoot it.

Thanks.

**Comment by mcarlton00** [comment]
The `ServerId` isn't an issue.  It's the result of some poor inherited structure and overzealous logging and means nothing.

I don't see any looping in the log snippet you've posted. Each item looks unique.  The timeout is unusual, but it doesn't seem to be a breaking error.  Does kodi report an error in the UI while trying to sync?  Does the sync complete and can you browse the library in kodi?  It seems as though the timeout is on a single piece of artwork, which should be largely inconsequential.

The version of the kodi addon and of the jellyfin server are generally more important than the kodi version

**Comment by mcarlton00** [comment]
Can't replicate, no response.  Closing

**Comment by bugsyb** [comment]
@mcarlton00 apologies for slow response.
The discovery was stuck and never finishing as it looked like.
Did full reset of the database and after adding resources slowly back to Jellyfin and re-discovering manually (forcing db update) it worked at the end of the day.
Didn't have time to re-add everything from scratch to test if problem is reproducible still.
