### ISSUE TITLE
Addon won't connect

### ISSUE THREAD

**Issue by dukenukemx** [jellyfin/jellyfin-kodi#146]
Jellyfin is installed on Linux Mint 19 and is version 10.4.1.  The addon is version 3.6.  When I try to manual login and connect connect, nothing happens.  Jellyfin works fine through the web browser.  I checked the Kodi logs and saw this when trying.  

```
2019-11-19 23:27:38.493 T:15392  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:276 tryConnect url: http://192.168.1.5:8096/emby/system/info/public
2019-11-19 23:27:38.502 T:15392  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:151 connectToAddress http://192.168.1.5:8096 succeeded
2019-11-19 23:27:38.503 T:15392  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:165 begin connectToServer
2019-11-19 23:27:38.503 T:15392  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:177 beginning connection tests
2019-11-19 23:27:38.503 T:15392  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:299 testing connection mode 2 with server None
2019-11-19 23:27:38.503 T:15392  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:276 tryConnect url: http://192.168.1.5:8096/emby/system/info/public
2019-11-19 23:27:38.513 T:15392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "C:\Users\Demetrius\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\resources\lib\dialogs\servermanual.py", line 83, in onClick
                                                elif self._connect_to_server(server):
                                              File "C:\Users\Demetrius\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\resources\lib\dialogs\servermanual.py", line 120, in _connect_to_server
                                                result = self.connect_manager.connect_to_address(server)
                                              File "C:\Users\Demetrius\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\resources\lib\jellyfin\core\connection_manager.py", line 157, in connect_to_address
                                                server = self.connect_to_server(server, options)
                                              File "C:\Users\Demetrius\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\resources\lib\jellyfin\core\connection_manager.py", line 178, in connect_to_server
                                                return self._test_next_connection_mode(tests, 0, server, options)
                                              File "C:\Users\Demetrius\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\resources\lib\jellyfin\core\connection_manager.py", line 325, in _test_next_connection_mode
                                                if self._compare_versions(self._get_min_server_version(), result['Version']) == 1:
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
```

**Comment by mcarlton00** [comment]
First guess is one of 2 things:
* You're trying to run on Kodi 19 (we haven't worked out the kinks yet)
* You're not taking the baseurl change into account with server version 10.4.1.  Try doing `192.168.0.5:8096/jellyfin` and seeing if it lets you log in

If it's something else, then we'll need to do further investigating

**Comment by dukenukemx** [comment]
I'm running Kodi 18.  I just tried 192.168.1.5:8096/jellyfin and that didn't work.  I'll reboot the Jellyfin server seeing as there were updates and it has been running for 28 days.  I'll report back if there was any changes.

**Comment by dukenukemx** [comment]
Rebooted and same issue.  This did work before using the Emby plugin for Kodi, but that stopped working as well.

**Comment by dukenukemx** [comment]
Jellyfin shows this error I think when I try to hit the connect button.  I have TVheadend installed and I believe it uses port 1900.  Not sure if that could be the reason?  

Failed to bind to port 1900: "Address already in use". DLNA will be unavailable

**Comment by dukenukemx** [comment]
Stopping the TVHeadEnd service didn't fix it.  I also tried removing the plugin from Jellyfin as well.

**Comment by mcarlton00** [comment]
Are you trying to manually add the server, or go through the setup wizard when it's first installed?  When you load Jellyfin in the Web UI, what's in the URL bar?  For example, mine is `http://192.168.0.200:8096/web/index.html#!/home.html`.

**Comment by dukenukemx** [comment]
It pops up on Kodi after the addon is installed and I choose to manually add the server.  The URL bar is http://192.168.1.5:8096/jellyfin/web/index.html#!/home.html

**Comment by hrvstr** [comment]
I have to same issue running Kodi 18.5 and Jellyfin 10.4.1.

I added the new base url in the settings but I can't login anymore (movies will not start playing, no login notification like usually). I don't get any notification although they are all checked in the plugin settings - even no login failed. I also don't see Kodi in the Jellyfin dashboard like I used to.

**Comment by mcarlton00** [comment]
@dukenukemx In that case, the URL you should be using to connect should be `192.168.1.5:8096/jellyfin`.  Assuming this is from a fresh setup and it can reach your server, it should proceed through to the next screen.

@hrvstr It sounds like you're doing this from an existing install.  Did you restart Kodi after changing the server string?  Unfortunately, the addon doesn't seem to handle having it's server string changed very well.  The easiest solutions are to either change the baseurl in the server back to `/` instead of `/jellyfin`, or reset the Kodi database and do a fresh sync under the new URL path.

**Comment by dukenukemx** [comment]
I can confirm that 192.168.1.5:8096/jellyfin does allow me to log in.  Why did this change?

**Comment by mcarlton00** [comment]
It's a required change due to how the baseurl api was updated in the server.

https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1

**Comment by hrvstr** [comment]
> @hrvstr It sounds like you're doing this from an existing install. Did you restart Kodi after changing the server string? Unfortunately, the addon doesn't seem to handle having it's server string changed very well. The easiest solutions are to either change the baseurl in the server back to `/` instead of `/jellyfin`, or reset the Kodi database and do a fresh sync under the new URL path.

Yes, I did a restart on both Kodi and Jellyfin. I fixed it for now by changing the base url to  `/` instead of `/jellyfin` but if I interpret the release not correctly this will keep me from using the Android and Android TV app. (not a big deal for me)

**Comment by mcarlton00** [comment]
All clients should be compatible with any baseurl that's defined in the server.  If for some reason it doesn't work, you should either open an issue in that clients' repo or come discuss the problem in [Matrix](https://matrix.to/#/#jellyfin:matrix.org) with the dev team.
