### ISSUE TITLE
Connection loss since server version 10.4.3-1

### ISSUE THREAD

**Issue by douglasriper** [jellyfin/jellyfin-kodi#155]
**Describe the bug**

since the last version of Jellyfin server the Kodi client can no longer connect.

**To Reproduce**

1. Lunch LibreElec or Try to play video

**Expected behavior**

```
**Logs**


[2019-12-08 17:07:28.083 T:1580286848  NOTICE: JELLYFIN.entrypoint.service -> INFO::resources/lib/entrypoint/service.py:62 --->>>[ JELLYFIN ]
2019-12-08 17:07:28.085 T:1580286848  NOTICE: JELLYFIN.entrypoint.service -> INFO::resources/lib/entrypoint/service.py:63 Version: 0.3.6
2019-12-08 17:07:28.087 T:1580286848  NOTICE: JELLYFIN.entrypoint.service -> INFO::resources/lib/entrypoint/service.py:64 KODI Version: 18.5 Git:newclock5_18.5-Leia
2019-12-08 17:07:28.098 T:1580286848  NOTICE: JELLYFIN.entrypoint.service -> INFO::resources/lib/entrypoint/service.py:65 Platform: LibreElec
2019-12-08 17:07:28.099 T:1580286848  NOTICE: JELLYFIN.entrypoint.service -> INFO::resources/lib/entrypoint/service.py:66 Python Version: 2.7.16 (default, Nov 23 2019, 02:28:55) 
                                            [GCC 8.3.0]
2019-12-08 17:07:28.135 T:1580286848  NOTICE: JELLYFIN.entrypoint.service -> INFO::resources/lib/entrypoint/service.py:67 Using dynamic paths: True
2019-12-08 17:07:28.140 T:1580286848  NOTICE: JELLYFIN.entrypoint.service -> INFO::resources/lib/entrypoint/service.py:68 Log Level: 2
2019-12-08 17:07:28.183 T:1580286848  NOTICE: JELLYFIN.views -> WARNING::resources/lib/views.py:119 [Errno 17] File exists: '/storage/.kodi/userdata/library/video'
2019-12-08 17:07:28.274 T:1580286848  NOTICE: JELLYFIN.service -> ERROR::service.py:54 no element found: line 1, column 0
                                            Traceback (most recent call last):
                                              File "service.py", line 47, in run
                                                service = Service()
                                              File "resources/lib/entrypoint/service.py", line 70, in __init__
                                                verify_kodi_defaults()
                                              File "resources/lib/views.py", line 127, in verify_kodi_defaults
                                                xml = etree.parse(file).getroot()
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 657, in parse
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1671, in close
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
                                            ParseError: no element found: line 1, column 0
2019-12-08 17:07:28.276 T:1688023936  NOTICE: JELLYFIN.service -> INFO::service.py:94 --<[ service ]

2019-12-08 17:07:20.066 T:1937657264  NOTICE: ADDON: plugin.video.jellyfin v0.3.6 installed
2019-12-08 17:07:20.067 T:1937657264  NOTICE: ADDON: repository.jellyfin.kodi v1.0.0 installed
```
**Screenshots**

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Jellyfin Version: 10.4.3-1 (stable version from jellyfin's depot) with Kodi sync queue extension 
 - Kodi Version: 18.5 (libreelec 9.2.0)
 - Addon Version: 0.36

**Additional context**

No trace of websocket connection in the server logs since this update.

**Comment by mcarlton00** [comment]
I can't replicate this.  I have 3 kodi boxes all working fine on server version 10.4.3.

Unrelated, but unless you mean 2 separate systems, Ubuntu and LibreElec are 2 entirely separate things.

The error suggests that one of the xml files in your kodi directory is misformed somehow.  Is it possible something changed them?  Possibly another addon installed modified them?

Worst case scenario you should be able to reset the kodi database and do a fresh connection/sync and it should fix any issues, but I can't imagine what would've caused it.

**Comment by douglasriper** [comment]
I have already tried to reset the plugin, including settings.
As it still didn't work I tried to delete the addon and profile files.
but still the same problem

I will try to do a configuration with a newly installed OSMC.

**Comment by douglasriper** [comment]
You were right:)
I just realized that my old configuration no longer asked me for my password.
I didn't all understand it, but if it works, it's enough for my little head.
Thank you for your help. :)
