### ISSUE TITLE
Kodi Crash 

### ISSUE THREAD

**Issue by jee-r** [jellyfin/jellyfin-kodi#158]
**Describe the bug**
Jellyfin-kodi addon make crash/freeze Kodi after a few seconds when i play video.

**To Reproduce**

1. install Libreelec on a raspberry (4 in my case)
2. install Kodi-Jellyfin addon from the repo
3. Loggin to your jellyfin server and sync your librairy
4. play a video

**Expected behavior**
Play video without this issue

**Logs**
```
raspi:~ # tail -f .kodi/temp/kodi.log 
2019-12-10 09:43:28.664 T:3012018192  NOTICE: VideoPlayer: waiting for threads to exit
2019-12-10 09:43:28.664 T:3012018192  NOTICE: VideoPlayer: finished waiting
2019-12-10 09:43:29.232 T:2624582512  NOTICE: JELLYFIN.player -> INFO::resources/lib/player.py:369 --<[ playback ]
2019-12-10 09:43:31.839 T:2624582512  NOTICE: JELLYFIN.monitor -> INFO::resources/lib/monitor.py:92 [ playlist ] cleared
2019-12-10 09:43:31.888 T:2574226288  NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:65 Handshake Status 404
2019-12-10 09:43:36.692 T:2494780272   ERROR: CCurlFile::Exists - Failed: Couldn't resolve host name(6) for http://folder.jpg/
2019-12-10 09:43:36.937 T:2574226288  NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:65 Handshake Status 404
2019-12-10 09:45:08.679 T:3012018192  NOTICE: Previous line repeats 18 times.
2019-12-10 09:45:08.679 T:3012018192  NOTICE: Samba is idle. Closing the remaining connections
2019-12-10 09:45:12.977 T:2574226288  NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:65 Handshake Status 404
2019-12-10 10:08:53.706 T:2165891952  NOTICE: Previous line repeats 280 times.
2019-12-10 10:08:53.706 T:2165891952  NOTICE: JELLYFIN.entrypoint.default -> INFO::resources/lib/entrypoint/default.py:52 path: ?dbid=87&mode=play&id=593316c94eef8d6beb7d2bac151be47d&filename=peaky.blinders.s03e02.multi.1080p.bluray.x264-sh0w.mkv params: {
                                                "dbid": "87", 
                                                "filename": "peaky.blinders.s03e02.multi.1080p.bluray.x264-sh0w.mkv", 
                                                "mode": "play", 
                                                "id": "593316c94eef8d6beb7d2bac151be47d"
                                            }
2019-12-10 10:08:53.707 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:341 ---[ contact MU-TH-UR 6000/GetItem ]
2019-12-10 10:08:53.727 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:08:53.742 T:2574226288  NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:65 Handshake Status 404
2019-12-10 10:08:53.775 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:08:53.807 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:367 --[ void/712f115c-7a3c-443e-9cd5-6ddb77177ae8 ]
2019-12-10 10:08:54.414 T:2165891952  NOTICE: Previous line repeats 6 times.
2019-12-10 10:08:54.414 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:341 ---[ contact MU-TH-UR 6000/GetServerAddress ]
2019-12-10 10:08:54.437 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:08:54.515 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:367 --[ void/8686744e-8222-4365-b6da-efad8fae468b ]
2019-12-10 10:08:54.516 T:2165891952  NOTICE: JELLYFIN.objects.actions -> INFO::resources/lib/objects/actions.py:50 [ play/593316c94eef8d6beb7d2bac151be47d ] Episode 2
2019-12-10 10:08:54.521 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:341 ---[ contact MU-TH-UR 6000/GetToken ]
2019-12-10 10:08:54.622 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:367 --[ void/0b7987b9-2a91-4c6d-8e44-97d7b9b3ed70 ]
2019-12-10 10:08:54.626 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:08:54.723 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:367 --[ void/0b7987b9-2a91-4c6d-8e44-97d7b9b3ed70 ]
2019-12-10 10:08:54.739 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:341 ---[ contact MU-TH-UR 6000/GetPlaybackInfo ]
2019-12-10 10:08:54.842 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:367 --[ void/338468a2-605b-4fbe-9ede-28310214fcd9 ]
2019-12-10 10:08:54.843 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:08:54.850 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:08:54.943 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:367 --[ void/338468a2-605b-4fbe-9ede-28310214fcd9 ]
2019-12-10 10:08:54.944 T:2165891952  NOTICE: JELLYFIN.helper.playutils -> INFO::resources/lib/helper/playutils.py:81 {u'PlaySessionId': u'ac082106f4354e2d9b1dd9759bfaf49b', u'MediaSources': [{u'SupportsDirectStream': True, u'Container': u'mkv', u'RequiresClosing': False, u'IgnoreDts': False, u'IgnoreIndex': False, u'DefaultAudioStreamIndex': 1, u'SupportsDirectPlay': True, u'MediaStreams': [{u'IsInterlaced': False, u'Index': 0, u'AverageFrameRate': 25, u'Width': 1920, u'VideoRange': u'SDR', u'Codec': u'h264', u'IsForced': False, u'AspectRatio': u'16:9', u'Type': u'Video', u'IsTextSubtitleStream': False, u'Profile': u'High', u'TimeBase': u'1/1000', u'NalLengthSize': u'4', u'CodecTimeBase': u'1/50', u'RealFrameRate': 25, u'Level': 41, u'DisplayTitle': u'1080P H264', u'RefFrames': 1, u'BitDepth': 8, u'BitRate': 13573545, u'IsDefault': True, u'SupportsExternalStream': False, u'Height': 1080, u'IsAVC': True, u'PixelFormat': u'yuv420p', u'IsExternal': False}, {u'Profile': u'DTS', u'IsInterlaced': False, u'DisplayTitle': u'Fre DTS stereo Default', u'ChannelLayout': u'stereo', u'Language': u'fre', u'Title': u'French', u'Index': 1, u'BitRate': 1536000, u'Level': 0, u'Channels': 2, u'TimeBase': u'1/1000', u'Codec': u'dts', u'SupportsExternalStream': False, u'IsForced': False, u'CodecTimeBase': u'1/48000', u'SampleRate': 48000, u'Type': u'Audio', u'IsTextSubtitleStream': False, u'IsDefault': True, u'IsExternal': False}, {u'Profile': u'DTS', u'IsInterlaced': False, u'DisplayTitle': u'Eng DTS stereo', u'ChannelLayout': u'stereo', u'Language': u'eng', u'Title': u'English', u'Index': 2, u'BitRate': 1536000, u'Level': 0, u'Channels': 2, u'TimeBase': u'1/1000', u'Codec': u'dts', u'SupportsExternalStream': False, u'IsForced': False, u'CodecTimeBase': u'1/48000', u'SampleRate': 48000, u'Type': u'Audio', u'IsTextSubtitleStream': False, u'IsDefault': False, u'IsExternal': False}, {u'IsInterlaced': False, u'TimeBase': u'1/1000', u'Language': u'fre', u'Title': u'French (Forced)', u'Index': 3, u'Type': u'Subtitle', u'SupportsExternalStream': True, u'Codec': u'subrip', u'DeliveryMethod': u'Embed', u'IsTextSubtitleStream': True, u'localizedForced': u'Forced', u'localizedUndefined': u'Undefined', u'IsForced': True, u'CodecTimeBase': u'0/1', u'Level': 0, u'DisplayTitle': u'French (Forced) - Default', u'localizedDefault': u'Default', u'IsDefault': True, u'IsExternal': False}, {u'IsInterlaced': False, u'CodecTimeBase': u'0/1', u'TimeBase': u'1/1000', u'Language': u'fre', u'Level': 0, u'Index': 4, u'Type': u'Subtitle', u'SupportsExternalStream': True, u'Score': 10111221, u'DeliveryMethod': u'Embed', u'localizedForced': u'Forced', u'localizedUndefined': u'Undefined', u'IsForced': False, u'Title': u'French (Full)', u'Codec': u'subrip', u'localizedDefault': u'Default', u'DisplayTitle': u'French (Full)', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}], u'Type': u'Default', u'ReadAtNativeFramerate': False, u'RequiresLooping': False, u'Path': u'/Media/TvShows/Peaky Blinders/Season 03/peaky.blinders.s03e02.multi.1080p.bluray.x264-sh0w.mkv', u'RequiresOpening': False, u'Bitrate': 16645545, u'IsRemote': False, u'Name': u'peaky.blinders.s03e02.multi.1080p.bluray.x264-sh0w', u'RequiredHttpHeaders': {}, u'SupportsTranscoding': True, u'Formats': [], u'Protocol': u'File', u'IsInfiniteStream': False, u'SupportsProbing': True, u'VideoType': u'VideoFile', u'ETag': u'0463f131abdca8c1d2ff31d2eba0b082', u'RunTimeTicks': 34561818624L, u'Size': 5864080384L, u'GenPtsInput': False, u'Id': u'593316c94eef8d6beb7d2bac151be47d', u'DefaultSubtitleStreamIndex': 4}]}
2019-12-10 10:08:54.945 T:2165891952  NOTICE: JELLYFIN.helper.playutils -> INFO::resources/lib/helper/playutils.py:98 Skip source selection.
2019-12-10 10:08:54.950 T:2165891952  NOTICE: JELLYFIN.helper.playutils -> INFO::resources/lib/helper/playutils.py:203 --[ direct stream ]
2019-12-10 10:08:54.993 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:341 ---[ contact MU-TH-UR 6000/GetIntros ]
2019-12-10 10:08:55.081 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:08:55.096 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:08:55.097 T:2165891952  NOTICE: JELLYFIN.downloader -> INFO::resources/lib/downloader.py:367 --[ void/a526cd0d-7671-4f24-b4cf-6ed0033c2cd1 ]
2019-12-10 10:08:55.631 T:2165891952  NOTICE: Previous line repeats 1 times.
2019-12-10 10:08:55.631 T:2165891952  NOTICE: JELLYFIN.default -> INFO::default.py:39 ---<[ default ]
2019-12-10 10:08:55.701 T:3012018192  NOTICE: VideoPlayer::OpenFile: videodb://inprogresstvshows/10/3/87?season=3&tvshowid=10
2019-12-10 10:08:55.704 T:2539574128  NOTICE: Creating InputStream
2019-12-10 10:08:55.772 T:2624582512  NOTICE: JELLYFIN.player -> INFO::resources/lib/player.py:155 -->[ play/593316c94eef8d6beb7d2bac151be47d ] {'Volume': 100, u'PlaySessionId': u'ac082106f4354e2d9b1dd9759bfaf49b', u'SubsMapping': {}, u'CurrentPosition': 0, 'Muted': False, u'SubtitleStreamIndex': 4, 'Server': <jellyfin.client.JellyfinClient object at 0xaba2fd70>, 'Paused': False, u'MediaSourceId': u'593316c94eef8d6beb7d2bac151be47d', u'AudioStreamIndex': 1, u'DeviceId': u'20F9B046067541CD95933844B789B199', 'File': 'https://{jellyfin-server}/emby/Videos/593316c94eef8d6beb7d2bac151be47d/stream?static=true&MediaSourceId=593316c94eef8d6beb7d2bac151be47d&api_key={jellyfin-token}', u'PlayOption': u'Addon', u'CurrentEpisode': {u'rating': None, u'tvshowid': u'7db301d3239f358ac100c8625c58b43e', u'episode': 2, u'title': u'Episode 2', u'season': 3, u'plot': u"Tommy discovers the extent of the mission given to him and the extreme lengths his new paymasters are willing to go to in their quest for power.Meanwhile his own family's activities lead to escalating danger in Birmingham.", u'episodeid': u'593316c94eef8d6beb7d2bac151be47d', u'firstaired': 2016, u'art': {u'tvshow.fanart': u'https://{jellyfin-server}/emby/Items/7db301d3239f358ac100c8625c58b43e/Images/Backdrop/0?Format=original&Tag=a3336be5453b1fd770bedcf4d22751eb', u'tvshow.poster': u'https://{jellyfin-server}/emby/Items/7db301d3239f358ac100c8625c58b43e/Images/Primary/0?Format=original&Tag=2c9d90ce62206f1a85efbfce71110d6e', u'thumb': u'https://{jellyfin-server}/emby/Items/593316c94eef8d6beb7d2bac151be47d/Images/Primary/0?Format=original&Tag=6786a4520edb305172df4c54b225282d'}, u'playcount': 0, u'showtitle': u'Peaky Blinders'}, u'Path': u'https://{jellyfin-server}/emby/Videos/593316c94eef8d6beb7d2bac151be47d/stream?static=true&MediaSourceId=593316c94eef8d6beb7d2bac151be47d&api_key={jellyfin-token}', u'ServerId': None, u'Runtime': 34561818624L, u'Type': u'Episode', u'Id': u'593316c94eef8d6beb7d2bac151be47d', u'PlayMethod': u'DirectStream'}
2019-12-10 10:08:55.776 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:08:56.488 T:2539574128  NOTICE: Creating Demuxer
2019-12-10 10:08:56.529 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:08:56.530 T:2624582512  NOTICE: JELLYFIN.objects.actions -> INFO::resources/lib/objects/actions.py:755  [ play ] kodi_id: 87 media: episode
2019-12-10 10:08:56.899 T:2539574128  NOTICE: Opening stream: 0 source: 256
2019-12-10 10:08:56.899 T:2539574128  NOTICE: Creating video codec with codec id: 27
2019-12-10 10:08:56.911 T:2539574128  NOTICE: Creating video thread
2019-12-10 10:08:56.911 T:2494780272  NOTICE: running thread: video_thread
2019-12-10 10:08:56.988 T:2539574128  NOTICE: Opening stream: 2 source: 256
2019-12-10 10:08:56.988 T:2539574128  NOTICE: Finding audio codec for: 86020
2019-12-10 10:08:56.989 T:2539574128  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder dca
2019-12-10 10:08:56.989 T:2539574128  NOTICE: Creating audio thread
2019-12-10 10:08:56.989 T:2539574128  NOTICE: Opening stream: 4 source: 256
2019-12-10 10:08:56.990 T:2237993840  NOTICE: running thread: CVideoPlayerAudio::Process()
2019-12-10 10:08:57.002 T:2237993840  NOTICE: Creating audio stream (codec id: 86020, channels: 2, sample rate: 48000, no pass-through)
2019-12-10 10:08:57.052 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:08:57.078 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:08:57.601 T:2494780272 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2019-12-10 10:08:58.117 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:08:58.124 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:08:58.922 T:2574226288  NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:65 Handshake Status 404
2019-12-10 10:08:59.054 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:08:59.059 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:08:59.831 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:08:59.842 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:09:00.872 T:2624582512  NOTICE: JELLYFIN.player -> INFO::resources/lib/player.py:161 Setting audio: 2 subs: 4
2019-12-10 10:09:00.879 T:2539574128  NOTICE: Closing stream player 1
2019-12-10 10:09:00.879 T:2539574128  NOTICE: Waiting for audio thread to exit
2019-12-10 10:09:00.883 T:2237993840  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2019-12-10 10:09:00.883 T:2539574128  NOTICE: Closing audio device
2019-12-10 10:09:00.934 T:2539574128  NOTICE: Deleting audio codec
2019-12-10 10:09:00.936 T:2539574128  NOTICE: Opening stream: 2 source: 256
2019-12-10 10:09:00.936 T:2539574128  NOTICE: Finding audio codec for: 86020
2019-12-10 10:09:00.938 T:2539574128  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder dca
2019-12-10 10:09:00.938 T:2539574128  NOTICE: Creating audio thread
2019-12-10 10:09:00.939 T:2237993840  NOTICE: running thread: CVideoPlayerAudio::Process()
2019-12-10 10:09:01.049 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:09:01.065 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:09:01.884 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:09:01.894 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:09:01.921 T:2539574128  NOTICE: Closing stream player 3
2019-12-10 10:09:01.922 T:2539574128  NOTICE: Opening stream: 4 source: 256
2019-12-10 10:09:02.085 T:2494780272 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2019-12-10 10:09:02.416 T:2237993840 WARNING: Previous line repeats 1 times.
2019-12-10 10:09:02.417 T:2237993840  NOTICE: Creating audio stream (codec id: 86020, channels: 2, sample rate: 48000, no pass-through)
2019-12-10 10:09:02.793 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:09:02.805 T:2624582512   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2019-12-10 10:09:04.049 T:2574226288  NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:65 Handshake Status 404
2019-12-10 10:09:04.652 T:2237993840   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2019-12-10 10:09:09.228 T:2574226288   ERROR: Previous line repeats 1 times.
2019-12-10 10:09:09.235 T:2574226288  NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:65 Handshake Status 404
2019-12-10 10:09:12.498 T:2624582512  NOTICE: JELLYFIN.monitor -> ERROR::resources/lib/monitor.py:123 ServerId undefined.
                                            Traceback (most recent call last):
                                              File "resources/lib/monitor.py", line 107, in onNotification
                                                raise Exception("ServerId undefined.")
                                            Exception: ServerId undefined.
2019-12-10 10:09:14.436 T:2574226288  NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:65 Handshake Status 404
```

**Screenshots**

**System (please complete the following information):**
 - OS: Libreelec 9.2.0
 - Jellyfin Version: 10.4.3
 - Kodi Version: 18.5-Leia
 - Addon Version: [e.g. 0.2.1]

**Additional context**
This happend since the 9.2.0 libreelec's update.
This happend even if i disable the "verify connection" option in addon settings

**Comment by mcarlton00** [comment]
It seems as though it's failing to verify your SSL connection to the server.  Are you using a self signed certificate?  Also, is there a reverse proxy between kodi and the server?

**Comment by jee-r** [comment]
Thank's for your answer @mcarlton00 

At first I thought like you, but unfortunately this happens through reverse proxy (https://domain.com) and also through a direct connexion on LAN (http://192.168.1.52:8096)

btw my certificat is generate by Let's Encrypt, it's not a self-signed certificate.

Thank's for your help

**Comment by mcarlton00** [comment]
Confirmed it's an issue on a fresh Libreelec 9.2.0 installed to a Pi.  but it's working fine on kodi on a desktop.  very odd

**Comment by mcarlton00** [comment]
In another strange twist, the current master seems to be working fine on mine, but I can't think of anything we've done that could've affected this.  @jee-r would you be able to download the current master from [here](https://github.com/jellyfin/jellyfin-kodi/archive/master.zip) and test it?

Easiest way to get the addon onto the server would be to uninstall the JF for kodi addon, restart Libreelec (this is to make sure you'll be using the new version, not a cached old version), ssh into the pi, and run `wget https://github.com/jellyfin/jellyfin-kodi/archive/master.zip`.

If that works for you as well, I'll go ahead and push a new release out.
