### ISSUE TITLE
Switches to https on http defined server

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin-kodi#184]
**Describe the bug**
I configure the Kodi addon to use the Jellyfin server on the non-https port.  Using the wizard, I don't think it's even possible to use https, is it?

In any case, after making several http connections to the Jellyfin server, the addon strangely wants to use https, which of course does not work on the http port.

**To Reproduce**

Simply step through the wizard, choosing the server name and setting the http port, which is 80 in my case, not 8096.  When it gets time to choosing the Jellyfin user, notice in the log (below) how it's trying to use https instead of http.

**Expected behavior**
Should only use http, not try to use https after being configured for http.

**Logs**
```
2020-02-05 17:57:26.924 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.configuration -> Begin app constructor.
2020-02-05 17:57:26.933 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> Begin connect
2020-02-05 17:57:26.934 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> Begin getAvailableServers
2020-02-05 17:57:26.935 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> ERROR:: [Errno 101] Network is unreachable
2020-02-05 17:57:26.936 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> Found no servers
2020-02-05 17:57:26.937 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> Begin connectToServers, with 0 servers
2020-02-05 17:57:54.403 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> tryConnect url: http://videoserver.example.com:80/emby/system/info/public
2020-02-05 17:57:54.560 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> connectToAddress http://videoserver.example.com:80 succeeded
2020-02-05 17:57:54.560 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> begin connectToServer
2020-02-05 17:57:54.561 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> beginning connection tests
2020-02-05 17:57:54.561 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> testing connection mode 2 with server pvr
2020-02-05 17:57:54.562 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> tryConnect url: http://videoserver.example.com:80/emby/system/info/public
2020-02-05 17:57:54.667 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> calling onSuccessfulConnection with connection mode 2 with server pvr
2020-02-05 17:57:54.706 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> Begin connect
2020-02-05 17:57:54.707 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> Begin getAvailableServers
2020-02-05 17:57:54.709 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> ERROR:: [Errno 101] Network is unreachable
2020-02-05 17:57:54.710 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> Begin connectToServers, with 1 servers
2020-02-05 17:57:54.711 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> begin connectToServer
2020-02-05 17:57:54.711 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> beginning connection tests
2020-02-05 17:57:54.712 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> testing connection mode 2 with server pvr
2020-02-05 17:57:54.712 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> tryConnect url: http://videoserver.example.com:80/emby/system/info/public
2020-02-05 17:57:54.819 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> calling onSuccessfulConnection with connection mode 2 with server pvr
2020-02-05 17:58:07.904 T:139723578619648  NOTICE: JELLYFIN.dialogs.serverconnect -> Server Id selected: 9be14d61c64b452eb0fe38a39d2022a8
2020-02-05 17:58:07.905 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> begin connectToServer
2020-02-05 17:58:07.905 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> beginning connection tests
2020-02-05 17:58:08.117 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> testing connection mode 2 with server pvr
2020-02-05 17:58:08.117 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> tryConnect url: http://videoserver.example.com:80/emby/system/info/public
2020-02-05 17:58:08.226 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> calling onSuccessfulConnection with connection mode 2 with server pvr
2020-02-05 17:58:09.325 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.configuration -> Begin app constructor.
2020-02-05 17:58:09.335 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> Begin connect
2020-02-05 17:58:09.336 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> Begin getAvailableServers
2020-02-05 17:58:09.338 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> ERROR:: [Errno 101] Network is unreachable
2020-02-05 17:58:09.340 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> Begin connectToServers, with 1 servers
2020-02-05 17:58:09.340 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> begin connectToServer
2020-02-05 17:58:09.341 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> beginning connection tests
2020-02-05 17:58:09.341 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> testing connection mode 2 with server pvr
2020-02-05 17:58:09.342 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> tryConnect url: http://videoserver.example.com:80/emby/system/info/public
2020-02-05 17:58:09.453 T:139723578619648  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> calling onSuccessfulConnection with connection mode 2 with server pvr
2020-02-05 17:58:09.593 T:139725285480000   ERROR: Control 155 in window 13000 has been asked to focus, but it can't
2020-02-05 17:58:27.229 T:139725285480000   ERROR: Control 155 in window 13002 has been asked to focus, but it can't
2020-02-05 17:58:36.039 T:139723578619648  NOTICE: JELLYFIN.dialogs.usersconnect -> User Id selected: 3abbfc1aaa864057bad867e6230f9184
2020-02-05 17:58:36.187 T:139723578619648  NOTICE: Jellyfin.jellyfin.core.http -> ERROR:: 500 Server Error: Internal Server Error for url: https://videoserver.example.com/emby/Users/AuthenticateByName
2020-02-05 17:58:36.188 T:139723578619648  NOTICE: Jellyfin.jellyfin.core.http -> ERROR:: --[ 500 response ] 500 Server Error: Internal Server Error for url: https://videoserver.example.com/emby/Users/AuthenticateByName
2020-02-05 17:58:36.189 T:139723578619648  NOTICE: JELLYFIN.entrypoint.service -> ERROR:: 'NoneType' object has no attribute '__getitem__'
```

Notice in particular:

```
2020-02-05 17:58:36.187 T:139723578619648  NOTICE: Jellyfin.jellyfin.core.http -> ERROR:: 500 Server Error: Internal Server Error for url: https://videoserver.example.com/emby/Users/AuthenticateByName
```

This should not happen.  The wizard creates an http configuration, not https.

**System (please complete the following information):**
 - OS: Linux
 - Jellyfin Version: 10.4.2
 - Kodi Version: 18.5
 - Addon Version: 0.4.0

**Comment by mcarlton00** [comment]
I haven't seen this before.  Does the addon throw anerror and stop working when that happens?  Are you using a reverse proxy, or did you change the port in your Jellyfin server?

Also, the `/emby` endpoint was removed from all api requests in version 0.4.0, so it really doesn't make sense that it's trying to connect like that.

**Comment by brianjmurrell** [comment]
This is interesting.  I followed [the instructions](https://jellyfin.org/docs/general/clients/installing-kodi.html) to install the repo and then installed the Jellyfin addon from the repo.  I did have a "master" zip of jellyfin-kodi installed previously.  Now `~kodi/.kodi/addons/plugin.video.jellyfin/addon.xml` says:

```
<addon  id="plugin.video.jellyfin"
        name="Jellyfin" 
        version="10.1.0"
        provider-name="angelblue05">
```
which frankly looks like the older "master" zip of the addon that was installed before I installed from the repo.

**Comment by mcarlton00** [comment]
Very weird.  It seems as though trying to install from the repo isn't overriding the old master that you had installed manually.  That is rather old.  The version numbering scheme was changed back in https://github.com/jellyfin/jellyfin-kodi/issues/39.  

It may be worth uninstalling the addon, restarting kodi, and reinstalling the new version from the repo.  I believe that can be done without a full library sync again, but I'm not 100% positive.  You may want to backup your `~/.kodi` directory before trying it.

**Comment by brianjmurrell** [comment]
Yeah, I did an uninstall and install and it's now working much better.  I am getting a bunch of these though:

```
2020-02-06 10:08:11.527 T:139722668111616  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/objects/kodi/artwork.py", line 211, in run
                                                s.send(prep, timeout=(0.01, 0.01))
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
2020-02-06 10:08:11.877 T:139723607635712  NOTICE: Previous line repeats 2 times.
2020-02-06 10:08:11.877 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:164 ADD tvshow [25/61/32] How to Get Away with Murder: 7e023e53513545ee61ef068b0d40c9a6
2020-02-06 10:08:11.899 T:139723053979392  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/objects/kodi/artwork.py", line 211, in run
                                                s.send(prep, timeout=(0.01, 0.01))
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
2020-02-06 10:08:12.160 T:139723570226944  NOTICE: Previous line repeats 2 times.
2020-02-06 10:08:12.160 T:139723570226944  NOTICE: JELLYFIN.jellyfin.ws_client -> ERROR::jellyfin_kodi/jellyfin/ws_client.py:65 [Errno 101] Network is unreachable
2020-02-06 10:08:12.166 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:230 UPDATE season [32/110] Season 5: 638c3dd514dc20a765c0e73928352724
2020-02-06 10:08:12.259 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:230 UPDATE season [32/111] Season 6: 924d368e8f19a075ad018088a98db0b6
2020-02-06 10:08:12.267 T:139722668111616  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/objects/kodi/artwork.py", line 211, in run
                                                s.send(prep, timeout=(0.01, 0.01))
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
2020-02-06 10:08:14.463 T:139723053979392  NOTICE: Previous line repeats 3 times.
2020-02-06 10:08:14.463 T:139723053979392  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::jellyfin_kodi/objects/kodi/artwork.py:201 --<[ q:artwork/139724174362640 ]
2020-02-06 10:08:14.525 T:139722668111616  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::jellyfin_kodi/objects/kodi/artwork.py:201 --<[ q:artwork/139724149123856 ]
2020-02-06 10:08:15.130 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:164 ADD tvshow [25/63/33] Jann: fb6ff3be6276414f50367c3a9d146853
2020-02-06 10:08:15.153 T:139723607635712  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::jellyfin_kodi/objects/kodi/artwork.py:157 -->[ q:artwork/139723598003152 ]
2020-02-06 10:08:15.179 T:139723607635712  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::jellyfin_kodi/objects/kodi/artwork.py:157 -->[ q:artwork/139723598002384 ]
2020-02-06 10:08:15.242 T:139722668111616  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/objects/kodi/artwork.py", line 211, in run
                                                s.send(prep, timeout=(0.01, 0.01))
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
2020-02-06 10:08:15.277 T:139723607635712  NOTICE: Previous line repeats 1 times.
2020-02-06 10:08:15.278 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:230 UPDATE season [33/113] Season 1: 58a1e7a326b6dee170036a6810329b8f
2020-02-06 10:08:15.429 T:139723045586688  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/objects/kodi/artwork.py", line 211, in run
                                                s.send(prep, timeout=(0.01, 0.01))
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
2020-02-06 10:08:15.695 T:139723607635712  NOTICE: Previous line repeats 1 times.
2020-02-06 10:08:15.695 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:164 ADD tvshow [25/65/34] Kevin (Probably) Saves the World: cd72c49d8a175d26e6ebbba815bacb83
2020-02-06 10:08:15.796 T:139723045586688  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/objects/kodi/artwork.py", line 211, in run
                                                s.send(prep, timeout=(0.01, 0.01))
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
2020-02-06 10:08:15.845 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:230 UPDATE season [34/115] Season 1: 88bca203d883a04c5980dbb36a4c8b67
2020-02-06 10:08:15.883 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:230 UPDATE season [34/116] Season 2017: c47d57ff1e1ceb504beb88e43f698e49
2020-02-06 10:08:15.905 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:230 UPDATE season [34/117] Season 2018: 3ae1208e39a6a8964c737acc21fa477a
2020-02-06 10:08:16.015 T:139722668111616  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/objects/kodi/artwork.py", line 211, in run
                                                s.send(prep, timeout=(0.01, 0.01))
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
2020-02-06 10:08:17.011 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:164 ADD tvshow [25/67/35] Masters of Sex: f2b5e83b1f69e90c5e208ad29c478836
2020-02-06 10:08:17.132 T:139722668111616  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/objects/kodi/artwork.py", line 211, in run
                                                s.send(prep, timeout=(0.01, 0.01))
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
2020-02-06 10:08:17.141 T:139723607635712  NOTICE: Previous line repeats 1 times.
2020-02-06 10:08:17.141 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:129 POOL Masters of Sex [f2b5e83b1f69e90c5e208ad29c478836/f41bb16de2835c14be55aa9aae32cf12]
2020-02-06 10:08:17.169 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:230 UPDATE season [35/119] Season 3: e27127a96a118d632e1fc62e353da27d
2020-02-06 10:08:17.174 T:139723570226944  NOTICE: JELLYFIN.jellyfin.ws_client -> ERROR::jellyfin_kodi/jellyfin/ws_client.py:65 [Errno 101] Network is unreachable
2020-02-06 10:08:17.205 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:230 UPDATE season [35/120] Season 4: e63be19ff200affe8b1f7ad13169475f
2020-02-06 10:08:17.373 T:139722668111616  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/objects/kodi/artwork.py", line 211, in run
                                                s.send(prep, timeout=(0.01, 0.01))
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
2020-02-06 10:08:19.427 T:139723045586688  NOTICE: Previous line repeats 2 times.
2020-02-06 10:08:19.427 T:139723045586688  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::jellyfin_kodi/objects/kodi/artwork.py:201 --<[ q:artwork/139723598002384 ]
2020-02-06 10:08:19.446 T:139722668111616  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::jellyfin_kodi/objects/kodi/artwork.py:201 --<[ q:artwork/139723598003152 ]
2020-02-06 10:08:19.848 T:139723607635712  NOTICE: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:164 ADD tvshow [25/70/36] The Mentalist: 057b8a9f96aaa72e610c42905552d1f5
2020-02-06 10:08:19.896 T:139723607635712  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::jellyfin_kodi/objects/kodi/artwork.py:157 -->[ q:artwork/139724492082128 ]
2020-02-06 10:08:19.937 T:139723607635712  NOTICE: JELLYFIN.objects.kodi.artwork -> INFO::jellyfin_kodi/objects/kodi/artwork.py:157 -->[ q:artwork/139724951496720 ]
2020-02-06 10:08:19.994 T:139722668111616  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
```

**Comment by mcarlton00** [comment]
If I had to guess, when you had set up the addon the last time around, you enabled image caching and this time you didn't.

The addon's internal image caching mechanism is to run a local webserver.  That would be why you're trying to connect to localhost there.  Don't know why it does it that way, it's a relic of pre-fork that we haven't gotten to yet.

**Comment by brianjmurrell** [comment]
But the `localhost` and `8080` in the error message:

```
2020-02-06 10:08:17.373 T:139722668111616  NOTICE: JELLYFIN.objects.kodi.artwork -> ERROR::jellyfin_kodi/objects/kodi/artwork.py:214 HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=0.01)
```

is the Kodi remote control port.  Any idea where that timeout is being specified?  I'd be happy to just crank it up and see if it really is just a case of a too-small timeout.

**Comment by mcarlton00** [comment]
Yeah, that's unfortunately expected.  That's why I'm assuming you used to have that image caching setting enabled and now you don't.  You'll notice the popup says "Enable the webserver service in the Kodi settings to allow artwork caching".  That's (somehow) in use when using the artwork caching feature.  Don't ask me how, I haven't spent the time to understand it.  Like I said, it's a relic from pre-fork that simply hasn't come up for rework yet.  It's on the list, though

**Comment by brianjmurrell** [comment]
I did used to have image caching enabled.  But I also had the remote control enabled, so I shouldn't have been getting those errors.  Unless the timeout is too small, which is why I had hoped to increase it, at least as a debug aide.  I cannot seem to find where it's being specified though.

**Comment by mcarlton00** [comment]
Do you have image caching and remote control enabled now?  It's likely those things are already stored in the database from before and are being referenced, so having them not enabled now will throw errors.

**Comment by mcarlton00** [comment]
Not really a bug and no response.  Closing
