### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by herrwusel** [jellyfin/jellyfin-kodi#196]
**Describe the bug**

Trying to connect to my jellyfin server and getting stuck on the "Please sign in" window in Kodi. I can press "Sign in" and nothing happens. I'm not sure if it's the kodi plugin or my server setup. I have the jellyfin server behind a nginx reverse proxy and took the documentation's example.

**To Reproduce**

Following the plugin's set up routine 

**Logs**

```
2020-02-17 10:11:27.883 T:3376399232  NOTICE: Jellyfin.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:120 500 Server Error: Internal Server Error for url: https://***/Users/AuthenticateByName
2020-02-17 10:11:27.883 T:3376399232  NOTICE: Jellyfin.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:135 --[ 500 response ] 500 Server Error: Internal Server Error for url: https://***/Users/AuthenticateByName
2020-02-17 10:11:27.888 T:3376399232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/dialogs/loginmanual.py", line 84, in onClick
                                                elif self._login(user, password):
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/dialogs/loginmanual.py", line 121, in _login
                                                result = self.connect_manager.login(server, username, password)
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/connection_manager.py", line 115, in login
                                                self._on_authenticated(result, options)
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/connection_manager.py", line 460, in _on_authenticated
                                                self.config.data['auth.user_id'] = result['User']['Id']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
```

**System (please complete the following information):**
 - OS: CoreElec
 - Jellyfin Version: 10.4.3-1
 - Kodi Version: 18
 - Addon Version: 0.4.0

**Additional context**
Server log:
```
[2020-02-17 10:13:48.036 +01:00] [ERR] AcceptWebSocketAsync error
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Emby.Server.Implementations.SocketSharp.WebSocketSharpListener.ProcessWebSocketRequest(HttpContext ctx)
```

**Comment by mcarlton00** [comment]
When you say selecting "Sign In" doesn't do anything, do you mean after selecting a user?  Or are you manually putting in a username/password combo?

**Comment by herrwusel** [comment]
The latter - I'm entering username and password since I'm running the server on a dedicated server.

**Comment by mcarlton00** [comment]
Double check your password to be positive you're entering it correctly.  Currently, when logging in and entering an incorrect password, the logs will report 500 errors and give that same traceback

**Comment by herrwusel** [comment]
I'm using a password manager so the password is copy and pasted. I double checked now and it is the same I'm using to log into the web interface

**Comment by mcarlton00** [comment]
I'm not sure that copy/paste into Kodi actually works.  A quick test on one of my workstations isn't letting me paste a string in for the URL field at least.  [This post](https://forum.kodi.tv/showthread.php?tid=314361) is a bit old, but it seems to suggest that pasting into Kodi won't work.  So it might suck, but try typing your password manually

**Comment by herrwusel** [comment]
It is working with Kore or yatse though

**Comment by mcarlton00** [comment]
I was just able to copy my password from Yaste to a fresh Kodi install and it logged me in properly.  I'm assuming you want to keep your main user with a strong password, so try to make another temporary user with a simple password and see if it works then.  I can't find any instances where we're doing any processing on the password, but it's possible that Kodi just doesn't handle certain special characters well.  I can't find any documentation to indicate such a thing exists, but it's good to verify and track down if it exists.

**Comment by mcarlton00** [comment]
Guessing this was probably related to the addon not following redirects properly.  Closing.

**Comment by herrwusel** [comment]
Can confirm. It is working now. Thanks!

**Comment by Fire-Kirin** [comment]
> Can confirm. It is working now. Thanks!

Can you tell me how you solved it?
