### ISSUE TITLE
Handle login errors more gracefully

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-kodi#199]
**Describe the bug**

Login errors trigger ugly tracebacks in the logs.  Additionally, there's no feedback to the user if they enter an invalid password.

**Logs**

Bad user:
```
2020-02-17 22:31:16.987 T:140201300317952  NOTICE: Jellyfin.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:120 401 Client Error: Unauthorized for url: http://192.168.0.200:8097/Users/AuthenticateByName
2020-02-17 22:31:16.987 T:140201300317952  NOTICE: JELLYFIN.jellyfin.connection_manager -> ERROR::jellyfin_kodi/jellyfin/connection_manager.py:197 'auth.server-id'
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/jellyfin/connection_manager.py", line 195, in _request_url
                                                return self.http.request(request)
                                              File "jellyfin_kodi/jellyfin/http.py", line 129, in request
                                                self.client.callback("Unauthorized", {'ServerId': self.config.data['auth.server-id']})
                                            KeyError: 'auth.server-id'
2020-02-17 22:31:16.988 T:140201300317952  NOTICE: JELLYFIN.jellyfin.connection_manager -> ERROR::jellyfin_kodi/jellyfin/connection_manager.py:112 'auth.server-id'
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/jellyfin/connection_manager.py", line 110, in login
                                                result = self._request_url(request, False)
                                              File "jellyfin_kodi/jellyfin/connection_manager.py", line 195, in _request_url
                                                return self.http.request(request)
                                              File "jellyfin_kodi/jellyfin/http.py", line 129, in request
                                                self.client.callback("Unauthorized", {'ServerId': self.config.data['auth.server-id']})
                                            KeyError: 'auth.server-id'
```
bad password:
```
2020-02-17 22:43:37.592 T:140201300317952  NOTICE: Jellyfin.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:120 500 Server Error: Internal Server Error for url: http://192.168.0.200:8097/Users/AuthenticateByName
2020-02-17 22:43:37.592 T:140201300317952  NOTICE: Jellyfin.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:135 --[ 500 response ] 500 Server Error: Internal Server Error for url: http://192.168.0.200:8097/Users/AuthenticateByName
2020-02-17 22:43:37.592 T:140201300317952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/dialogs/loginmanual.py", line 84, in onClick
                                                elif self._login(user, password):
                                              File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/dialogs/loginmanual.py", line 121, in _login
                                                result = self.connect_manager.login(server, username, password)
                                              File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/connection_manager.py", line 115, in login
                                                self._on_authenticated(result, options)
                                              File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/connection_manager.py", line 460, in _on_authenticated
                                                self.config.data['auth.user_id'] = result['User']['Id']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
```

**Comment by TrueTechy** [comment]
Should have at least some better insight into what happened with the merge of #221

**Comment by TrueTechy** [comment]
Currently looks as follows when a user enters a wrong password

```
2020-03-30 03:13:41.055 T:140203628951296  NOTICE: JELLYFIN.jellyfin.api -> INFO::jellyfin_kodi/jellyfin/api.py:403 Trying to login to http://192.168.1.175:8096/Users/AuthenticateByName as jellyfin
2020-03-30 03:13:41.057 T:140203628951296  NOTICE: JELLYFIN.jellyfin.api -> INFO::jellyfin_kodi/jellyfin/api.py:385 Sending post request to Users/AuthenticateByName
2020-03-30 03:13:41.094 T:140203628951296  NOTICE: JELLYFIN.jellyfin.api -> ERROR::jellyfin_kodi/jellyfin/api.py:409 Failed to login to server with status code: 500
2020-03-30 03:13:41.094 T:140203628951296  NOTICE: JELLYFIN.jellyfin.api -> ERROR::jellyfin_kodi/jellyfin/api.py:410 Server Response:
                                            Object reference not set to an instance of an object.
2020-03-30 03:13:41.094 T:140203628951296  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:94 Failed to login as `jellyfin`
```
