### ISSUE TITLE
Bug: Index of Bounds when creating log handler 

### ISSUE THREAD

**Issue by Aerex** [jellyfin/jellyfin-kodi#2]
In my `kodi.log` file I get the following error on any operation done on the plugin causing the plugin to crash 

```
2:06:25.056 T:1114633120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.emby.tvshows/default.py", line 25, in <module>
                                                from entrypoint import Events
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/entrypoint/__init__.py", line 15, i
                                                Emby.set_loghandler(loghandler.LogHandler, logging.DEBUG)
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/emby/__init__.py", line 68, in set_
                                                config(level)
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/emby/__init__.py", line 24, in conf
                                                logger.addHandler(Emby.loghandler())
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/helper/loghandler.py", line 40, in
                                                self.sensitive['Server'].append(server['RemoteAddress'].split('://')[1])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

```

I found out that that `data.json` under `addons_data` generates a `RemoteAddress` with an address of `0.0.0.0` which is basically a broadcast ip address that allow any ip4 address. Problem is that it omits the protocal causing the error above to happen. I haven't experience this bug before in emby but I am with jellyfin and I don't know what is creating this data.json file. 

My temporary solution was to remove that propery in the file but there is a better solution but I am not knowledable on this codebase.

**Comment by joshuaboniface** [comment]
This should be fixed by the new release as we're restored the proper WAN address field.

**Comment by JustAMan** [comment]
Was fixed for a while already. The @cvium for reminder.
