### ISSUE TITLE
Watched status not properly synced

### ISSUE THREAD

**Issue by TrueTechy** [jellyfin/jellyfin-kodi#210]
**Describe the bug**
Watched status not syncing back to Jellyfin server when marked manually as watched in Kodi 

**To Reproduce**
Start playing unwatched tv episode.
Stop episode before end so content is marked partially watched
Mark item as watched manually

**Expected behavior**
Watched status is synced back to Jellyfin server and Kodi reflects this

**Logs**
```
2020-02-24 19:12:08.707 T:8996  NOTICE: JELLYFIN.library -> -->[ q:userdata/Season/140540708094976 ]
2020-02-24 19:12:08.726 T:9203  NOTICE: JELLYFIN.library -> 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/library.py", line 692, in run
                                                obj(item)
                                            TypeError: 'NoneType' object is not callable
2020-02-24 19:12:09.732 T:9203  NOTICE: JELLYFIN.library -> --<[ q:userdata/140540708094976 ]
2020-02-24 19:12:10.714 T:8996  NOTICE: JELLYFIN.library -> -->[ q:userdata/Episode/140540708094976 ]
2020-02-24 19:12:10.728 T:9206  NOTICE: JELLYFIN.library -> 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/library.py", line 692, in run
                                                obj(item)
                                            TypeError: 'NoneType' object is not callable
2020-02-24 19:12:11.734 T:9206  NOTICE: JELLYFIN.library -> --<[ q:userdata/140540708094976 ]
```

**System (please complete the following information):**
 - OS:Ubuntu
 - Jellyfin Version: 10.4.3
 - Kodi Version: 18.5
 - Addon Version: master branch

**Additional context**
After noticing a sync happened in the logs, the item which had been marked as watched was now marked as unwatched. Makes sense since the server thinks the item is unwatched

**Comment by random-human-being** [comment]
I'm having the same issue here, minus the errors in the log.
Jellyfin for Kodi syncs the episode being interrupted halfway through, but it straight up ignores the fact that it's marked as watched:

```
[2021-12-06 09:42:15.718 +00:00] [INF] [71] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Kodi" "0.7.7+py3" playing "Cheer Up, Sleepy Gene". Stopped at "907000" ms
[2021-12-06 09:42:16.235 +00:00] [INF] [95] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Starting User Changes Sync...
[2021-12-06 09:42:16.475 +00:00] [INF] [95] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: "USERSYNC" User "3ba51211fcdf402aa8cfe0974a637a1b"("MyName") posted 2 Updates: "918f508fec576e9334e03f0ea289553f,0a4890ac75910a52b1469267060d060e"
[2021-12-06 09:42:16.475 +00:00] [INF] [95] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: User Changes Sync Finished Taking "00:00:00.2390937"
```

Jellyfin 10.7.6 on docker
Jellyfin for Kodi 0.7.7 on various Android and Linux devices with Kodi 18.x or 19.x
