### ISSUE TITLE
Kodi plugin doesn't prompt for server connection details

### ISSUE THREAD

**Issue by brainstormi** [jellyfin/jellyfin-kodi#272]
Kodi plugin doesn't prompt for server connection details when installed it. It also not possible to enter the server/user manually, fields appears in disabled in gray. In the logs it appears the following error when installing the plugin:
```
2020-04-13 23:17:48.893 T:139932171069184  NOTICE: JELLYFIN.service -> ERROR::service.py:54 no element found: line 1, column 0
                                            Traceback (most recent call last):
                                              File "service.py", line 47, in run
                                                service = Service()
                                              File "jellyfin_kodi/entrypoint/service.py", line 71, in __init__
                                                verify_kodi_defaults()
                                              File "jellyfin_kodi/views.py", line 127, in verify_kodi_defaults
                                                xml = etree.parse(file).getroot()
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
                                                tree.parse(source, parser)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 657, in parse
                                                self._root = parser.close()
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1665, in close
                                                self._raiseerror(v)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
                                                raise err
                                            ParseError: no element found: line 1, column 0

```

Plugin was working before. It stopped working after updating kodi from version 18.5 to 18.6 in Ubuntu 16.04 through repository. I tried uninstalling and installed back again multiple times, but always through the previous error during the installation, not prompting server/user details.
Regards,

**Comment by mcarlton00** [comment]
The issue template is there for a reason, we need more information like addon and server versions.  That being said, this looks like an error that was fixed several releases ago related to unicode characters.

**Comment by brainstormi** [comment]
Excuse me, running plugin latest 0.5.3 and server 10.5.3.

**Comment by mcarlton00** [comment]
That particular error is indicating that there's an issue parsing Kodi's xml files used to navigate the library.  Those files aren't modified by the addon.  You might be able to just delete those directories and see if Kodi will recreate them, but a safer alternative would unfortunately probably be a totally fresh start.

The directories in question:
```
~/kodi/userdata/library/video/movies
~/kodi/userdata/library/video/musicvideos
~/kodi/userdata/library/video/tvshows
```

The error is specifically happening on the index.xml files, but fixing those is uncharted territory for me.  Personally, I would nuke the whole `~/.kodi` directory and start fresh.  Either way, this seems to be an issue with your Kodi install, not the addon, so I'm going to close this unless you continue to have addon specific problems.
