### ISSUE TITLE
Addon crash when special characters are in path

### ISSUE THREAD

**Issue by reov** [jellyfin/jellyfin-kodi#273]
**Describe the bug**

**To Reproduce**

1. Go to 'add-ons'
2. Click on 'jellyfin'
3. See error

**Expected behavior**

**Logs**
Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xcc in position 7: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\service.py", line 22, in <module>
                                                from entrypoint import Service  # noqa: F402
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\jellyfin_kodi\entrypoint\__init__.py", line 10, in <module>
                                                from helper import loghandler
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\jellyfin_kodi\helper\loghandler.py", line 14, in <module>
                                                import database
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\jellyfin_kodi\database\__init__.py", line 16, in <module>
                                                from objects import obj
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\jellyfin_kodi\objects\__init__.py", line 13, in <module>
                                                Objects().mapping()
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\jellyfin_kodi\objects\obj.py", line 35, in mapping
                                                with open(os.path.join(os.path.dirname(__file__), 'obj_map.json')) as infile:
                                              File "C:\Program Files\Kodi\system\python\Lib\ntpath.py", line 85, in join
                                                result_path = result_path + p_path
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 7: ordinal not in range(128)
                                            -->End of Python script error report<-- -->

**Screenshots**

**System (please complete the following information):**
 - OS: [Windows]
 - Jellyfin Version: [e.g. 10.0.1]
 - Kodi Version: [18.6]
 - Addon Version: [ 0.5.3]

**Additional context**

**Comment by mcarlton00** [comment]
What should the contents of the `��` be? I'm assuming your username, but I'm not familiar with Windows anymore.  Also what language do you have Kodi set to?

**Comment by reov** [comment]
> 内容应该`��`是什么？我假设使用您的用户名，但是我对Windows不再熟悉。另外，您将Kodi设置为哪种语言？
This is my username. Kodi has set up Chinese and English

**Comment by reov** [comment]
This is the log file
[kodi.log](https://github.com/jellyfin/jellyfin-kodi/files/4478958/kodi.log)
