### ISSUE TITLE
sys.getfilesystemencoding() returns None on Android

### ISSUE THREAD

**Issue by Norin-Radd** [jellyfin/jellyfin-kodi#285]
Jellyfin error, can´t play any streams, nor can I use the addon.

the addon was working fine and properly installed.

the kodi log says this.

```python
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: decode() argument 1 must be string, not None
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/service.py", line 21, in <module>
                                                from entrypoint import Service  # noqa: F402
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/__init__.py", line 13, in <module>
                                                from .default import Events
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/default.py", line 14, in <module>
                                                from database import reset, get_sync, Database, jellyfin_db, get_credentials
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/database/__init__.py", line 16, in <module>
                                                from objects import obj
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/objects/__init__.py", line 13, in <module>
                                                Objects().mapping()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/objects/obj.py", line 37, in mapping
                                                file_dir = os.path.dirname(ensure_text(__file__, sys.getfilesystemencoding()))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.six/lib/six.py", line 915, in ensure_text
                                                return s.decode(encoding, errors)
                                            TypeError: decode() argument 1 must be string, not None
                                            -->End of Python script error report<--
```

I have auto update on... so probably was an update who broke my addon.

**Comment by Norin-Radd** [comment]
yep it was the update. installed 0.53 and its working fine.

**Comment by oddstr13** [comment]
Looks like `sys.getfilesystemencoding()` returns `None` on Android.
Issue was introduced by #282.

**Comment by Mattyfaz** [comment]
Yep not working for me on 0.54 now either
