### ISSUE TITLE
Add-on doesn't like to be uninstalled

### ISSUE THREAD

**Issue by z3ntu** [jellyfin/jellyfin-kodi#324]
**Describe the bug**

I'm able to reproduce this bug under Kodi 19, not sure if the same happens on the stable version of Kodi.

**To Reproduce**

1. Install plugin
2. Potentially start some job (e.g. add to library) so the add-on is busy
3. Try to uninstall the add-on

**Expected behavior**

It shouldn't crash

**Logs**

<details>
<summary>logs (expand!)</summary>
<pre><code>
2020-06-17 19:58:57.082 T:201702   DEBUG <general>: ContextMenuManager: addon menus reloaded.
2020-06-17 19:58:57.082 T:201702   DEBUG <general>: CServiceAddonManager: stopping plugin.video.jellyfin.
2020-06-17 19:58:57.082 T:201702   DEBUG <general>: CPythonInvoker(1, /home/luca/.kodi/addons/plugin.video.jellyfin/service.py): trigger Monitor abort request
2020-06-17 19:58:57.082 T:200452   ERROR <general>: EXCEPTION: Unknown addon id 'plugin.video.jellyfin'.
2020-06-17 19:58:57.082 T:200452   ERROR <general>: EXCEPTION: Unknown addon id 'plugin.video.jellyfin'.
2020-06-17 19:58:57.082 T:200452   ERROR <general>: Exception in thread 
2020-06-17 19:58:57.082 T:200452   ERROR <general>: Thread-1
2020-06-17 19:58:57.082 T:200452   ERROR <general>: :
                                                   
2020-06-17 19:58:57.082 T:200452   ERROR <general>: Traceback (most recent call last):
                                                   
2020-06-17 19:58:57.082 T:200452   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/service.py", line 52, in run
                                                   
2020-06-17 19:58:57.082 T:200453   ERROR <general>: EXCEPTION: Unknown addon id 'plugin.video.jellyfin'.
2020-06-17 19:58:57.082 T:200453   ERROR <general>: Exception in thread 
2020-06-17 19:58:57.082 T:200453   ERROR <general>: Thread-2
2020-06-17 19:58:57.082 T:200453   ERROR <general>: :
                                                   
2020-06-17 19:58:57.083 T:200453   ERROR <general>: Traceback (most recent call last):
                                                   
2020-06-17 19:58:57.083 T:200453   ERROR <general>:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2020-06-17 19:58:57.083 T:200453   ERROR <general>:     
2020-06-17 19:58:57.083 T:200453   ERROR <general>: self.run()
2020-06-17 19:58:57.083 T:200453   ERROR <general>: 
                                                   
2020-06-17 19:58:57.083 T:200453   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 463, in run
                                                   
2020-06-17 19:58:57.083 T:200452   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/service.py", line 121, in service
                                                   
2020-06-17 19:58:57.083 T:200453   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1434, in info
                                                   
2020-06-17 19:58:57.084 T:200453   ERROR <general>:     
2020-06-17 19:58:57.084 T:200453   ERROR <general>: self._log(INFO, msg, args, **kwargs)
2020-06-17 19:58:57.084 T:200453   ERROR <general>: 
                                                   
2020-06-17 19:58:57.084 T:200453   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
                                                   
2020-06-17 19:58:57.085 T:200452   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/service.py", line 411, in shutdown
                                                   
2020-06-17 19:58:57.085 T:200453   ERROR <general>:     
2020-06-17 19:58:57.085 T:200453   ERROR <general>: self.handle(record)
2020-06-17 19:58:57.085 T:200453   ERROR <general>: 
                                                   
2020-06-17 19:58:57.085 T:200453   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
                                                   
2020-06-17 19:58:57.086 T:200453   ERROR <general>:     
2020-06-17 19:58:57.086 T:200453   ERROR <general>: self.callHandlers(record)
2020-06-17 19:58:57.086 T:200453   ERROR <general>: 
                                                   
2020-06-17 19:58:57.086 T:200453   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
                                                   
2020-06-17 19:58:57.086 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1434, in info
                                                   
2020-06-17 19:58:57.087 T:200453   ERROR <general>:     
2020-06-17 19:58:57.087 T:200453   ERROR <general>: hdlr.handle(record)
2020-06-17 19:58:57.087 T:200453   ERROR <general>: 
                                                   
2020-06-17 19:58:57.087 T:200453   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
                                                   
2020-06-17 19:58:57.087 T:200453   ERROR <general>:     
2020-06-17 19:58:57.087 T:200453   ERROR <general>: self.emit(record)
2020-06-17 19:58:57.087 T:200453   ERROR <general>: 
                                                   
2020-06-17 19:58:57.087 T:200453   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 54, in emit
                                                   
2020-06-17 19:58:57.087 T:200452   ERROR <general>:     
2020-06-17 19:58:57.087 T:200452   ERROR <general>: self._log(INFO, msg, args, **kwargs)
2020-06-17 19:58:57.087 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.087 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
                                                   
2020-06-17 19:58:57.088 T:200452   ERROR <general>:     
2020-06-17 19:58:57.088 T:200452   ERROR <general>: self.handle(record)
2020-06-17 19:58:57.088 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.088 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
                                                   
2020-06-17 19:58:57.088 T:200453   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 76, in _get_log_level
                                                   
2020-06-17 19:58:57.089 T:200452   ERROR <general>:     
2020-06-17 19:58:57.089 T:200452   ERROR <general>: self.callHandlers(record)
2020-06-17 19:58:57.089 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.089 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
                                                   
2020-06-17 19:58:57.089 T:200453   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/utils.py", line 78, in settings
                                                   
2020-06-17 19:58:57.089 T:200452   ERROR <general>:     
2020-06-17 19:58:57.089 T:200452   ERROR <general>: hdlr.handle(record)
2020-06-17 19:58:57.089 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.089 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
                                                   
2020-06-17 19:58:57.089 T:200452   ERROR <general>:     
2020-06-17 19:58:57.089 T:200452   ERROR <general>: self.emit(record)
2020-06-17 19:58:57.089 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.089 T:200452   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 54, in emit
                                                   
2020-06-17 19:58:57.090 T:200453   ERROR <general>: RuntimeError
2020-06-17 19:58:57.090 T:200453   ERROR <general>: : 
2020-06-17 19:58:57.090 T:200453   ERROR <general>: Unknown addon id 'plugin.video.jellyfin'.
2020-06-17 19:58:57.090 T:200453   ERROR <general>: 
                                                   
2020-06-17 19:58:57.090 T:200453   DEBUG <general>: .
2020-06-17 19:58:57.090 T:200453   DEBUG <general>: .
2020-06-17 19:58:57.090 T:200452   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 76, in _get_log_level
                                                   
2020-06-17 19:58:57.090 T:200452   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/utils.py", line 78, in settings
                                                   
2020-06-17 19:58:57.090 T:200452   ERROR <general>: RuntimeError
2020-06-17 19:58:57.090 T:200452   ERROR <general>: : 
2020-06-17 19:58:57.090 T:200452   ERROR <general>: Unknown addon id 'plugin.video.jellyfin'.
2020-06-17 19:58:57.090 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.090 T:200452   ERROR <general>: 
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   
2020-06-17 19:58:57.090 T:200452   ERROR <general>: Traceback (most recent call last):
                                                   
2020-06-17 19:58:57.090 T:200452   ERROR <general>:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2020-06-17 19:58:57.090 T:200452   ERROR <general>:     
2020-06-17 19:58:57.090 T:200452   ERROR <general>: self.run()
2020-06-17 19:58:57.090 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.090 T:200452   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/service.py", line 54, in run
                                                   
2020-06-17 19:58:57.090 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1469, in exception
                                                   
2020-06-17 19:58:57.091 T:200452   ERROR <general>:     
2020-06-17 19:58:57.091 T:200452   ERROR <general>: self.error(msg, *args, exc_info=exc_info, **kwargs)
2020-06-17 19:58:57.091 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.091 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1463, in error
                                                   
2020-06-17 19:58:57.091 T:200452   ERROR <general>:     
2020-06-17 19:58:57.091 T:200452   ERROR <general>: self._log(ERROR, msg, args, **kwargs)
2020-06-17 19:58:57.091 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.091 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
                                                   
2020-06-17 19:58:57.091 T:200452   ERROR <general>:     
2020-06-17 19:58:57.091 T:200452   ERROR <general>: self.handle(record)
2020-06-17 19:58:57.091 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.091 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
                                                   
2020-06-17 19:58:57.092 T:200452   ERROR <general>:     
2020-06-17 19:58:57.092 T:200452   ERROR <general>: self.callHandlers(record)
2020-06-17 19:58:57.092 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.092 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
                                                   
2020-06-17 19:58:57.092 T:200452   ERROR <general>:     
2020-06-17 19:58:57.092 T:200452   ERROR <general>: hdlr.handle(record)
2020-06-17 19:58:57.092 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.092 T:200452   ERROR <general>:   File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
                                                   
2020-06-17 19:58:57.092 T:200452   ERROR <general>:     
2020-06-17 19:58:57.092 T:200452   ERROR <general>: self.emit(record)
2020-06-17 19:58:57.092 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.092 T:200452   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 54, in emit
                                                   
2020-06-17 19:58:57.092 T:200452   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 76, in _get_log_level
                                                   
2020-06-17 19:58:57.092 T:200452   ERROR <general>:   File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/utils.py", line 78, in settings
                                                   
2020-06-17 19:58:57.093 T:200452   ERROR <general>: RuntimeError
2020-06-17 19:58:57.093 T:200452   ERROR <general>: : 
2020-06-17 19:58:57.093 T:200452   ERROR <general>: Unknown addon id 'plugin.video.jellyfin'.
2020-06-17 19:58:57.093 T:200452   ERROR <general>: 
                                                   
2020-06-17 19:58:57.093 T:200452   DEBUG <general>: .
2020-06-17 19:58:57.093 T:200452   DEBUG <general>: .
2020-06-17 19:58:57.093 T:200446   ERROR <general>: EXCEPTION: Unknown addon id 'plugin.video.jellyfin'.
2020-06-17 19:58:57.094 T:200446   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'RuntimeError'>
                                                   Error Contents: Unknown addon id 'plugin.video.jellyfin'.
                                                   Traceback (most recent call last):
                                                     File "/home/luca/.kodi/addons/plugin.video.jellyfin/service.py", line 92, in <module>
                                                     File "/usr/lib/python3.8/logging/__init__.py", line 1434, in info
                                                       self._log(INFO, msg, args, **kwargs)
                                                     File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
                                                       self.handle(record)
                                                     File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
                                                       self.callHandlers(record)
                                                     File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
                                                       hdlr.handle(record)
                                                     File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
                                                       self.emit(record)
                                                     File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 54, in emit
                                                     File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 76, in _get_log_level
                                                     File "/home/luca/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/utils.py", line 78, in settings
                                                   RuntimeError: Unknown addon id 'plugin.video.jellyfin'.
                                                   -->End of Python script error report<--
</code></pre>
</details>

**System (please complete the following information):**
 - OS: Linux
 - Jellyfin Version: 10.5.5
 - Kodi Version: 19 nightly r55334.c6d47fe20b1
 - Addon Version: git master + a bit
 - Playback Mode: Add-on

**Comment by TrueTechy** [comment]
I added checks for the addon to stop in all the sane places whilst it was doing library activity but could not get it for it to cleanup all the threads. Think if we ever get around to cleaning up the threading in the addon this would get resolved. 

In the meantime I can only suggest you wait till the addon isn't busy to uninstall it
