### ISSUE TITLE
ImportError: cannot import name DEFAULT_BUFFER_SIZE

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin-kodi#332]
**Describe the bug**
Failing to start

**To Reproduce**
Not really sure

**Expected behavior**
Plugin should start

**Logs**
```
2020-07-03 09:55:41.485 T:139887940458240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name DEFAULT_BUFFER_SIZE
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.jellyfin/service.py", line 22, in <module>
                                                from entrypoint import Service  # noqa: F402
                                              File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/__init__.py", line 10, in <module>
                                                from helper import loghandler
                                              File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/__init__.py", line 6, in <module>
                                                from .utils import addon_id
                                              File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/utils.py", line 15, in <module>
                                                from dateutil import tz, parser
                                              File "/home/kodi/.kodi/addons/script.module.dateutil/lib/dateutil/parser/__init__.py", line 2, in <module>
                                                from ._parser import parse, parser, parserinfo, ParserError
                                              File "/home/kodi/.kodi/addons/script.module.dateutil/lib/dateutil/parser/_parser.py", line 40, in <module>
                                                from io import StringIO
                                              File "/usr/lib64/python2.7/io.py", line 54, in <module>
                                                from _io import (DEFAULT_BUFFER_SIZE, BlockingIOError, UnsupportedOperation,
                                            ImportError: cannot import name DEFAULT_BUFFER_SIZE
                                            -->End of Python script error report<--
```

**System (please complete the following information):**
 - OS: Fedora 32
 - Jellyfin Version: 10.5.4
 - Kodi Version: 18.7
 - Addon Version: 0.5.2
 - Playback Mode: Add-On

**Additional context**
Python and the `io` module are working fine:

```bash
# python2 -c "from io import StringIO"
# python3 -c "from io import StringIO"
```

**Comment by mcarlton00** [comment]
Kodi generally doesn't use the system python (but kinda does.  it's very confusing), it uses it's own python package bundled with it.  That said, if it works on one device it should work everywhere.  That error is also being thrown from the dateutil module, not our code.  Maybe try to re-install the dateutil addon and see if that fixes it
