### ISSUE TITLE
Certificate verify failed with wildcard Let’s Encrypt on Amazon Fire TV (Kodi Plugin and Jellyfin App )

### ISSUE THREAD

**Issue by jeschero** [jellyfin/jellyfin-kodi#377]
**Describe the bug:**
Connection failed on Amazon Fire TV (Kodi Plugin and Jellyfin App ) with a wildcard Let’s Encrypt Jellyfin docker server

**To Reproduce:**
In Kodi(Amazon Fire TV):
1. Open Kodi
2. wait until jellyfin plugin asks for the webaddress
3. enter web-address
4. 'can't connection to selected server'

In Jellyfin App(Amazon Fire TV):
1. Open Jellyfin App
2. select manual server
3. enter webaddress
4. 'can't connection to selected server'

**Expected behavior:**
can login to the server

**Logs:**
```
certificate verify failed (_ssl.c:726)'),))
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/jellyfin/connection_manager.py", line 135, in connect_to_address
                                                response_url = self.API.check_redirect(address)
                                              File "jellyfin_kodi/jellyfin/api.py", line 453, in check_redirect
                                                response = self.send_request(server_address, "system/info/public")
                                              File "jellyfin_kodi/jellyfin/api.py", line 397, in send_request
                                                return request_method(url, **request_settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 514, in send
                                                raise SSLError(e, request=request)
                                            SSLError: HTTPSConnectionPool(host='jellyfin.nf.<my-domain>', port=443): Max retries exceeded with url: /system/info/public (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),))
```

**System:**
 - OS: Fire TV
 - Jellyfin Version: 10.6.3
 - Kodi Version: 18.8
 - Addon Version: 0.5.8

**Additional context**
Traefik v2 is the proxy server for the jellyfin server and the traefik container has a private ip-addresse.

With the android app i have no problems.

In firefox(Amazon Fire TV App) can i open the website from the jellyfin server.

**Comment by oddstr13** [comment]
This looks like an upstream bug with your Fire TV. Old device?

**Comment by jeschero** [comment]
I have installed the last update of fire tv (Fire OS 6.2.7.3) but the error is the same.

I have this device: [fire tv box](https://developer.amazon.com/de/docs/fire-tv/device-specifications-fire-tv-pendant-box.html?v=ftvgen3)

**Comment by oddstr13** [comment]
Please test your https setup with https://www.ssllabs.com/ssltest/index.html
It'll hopefully outline any issues you may have with your https setup.

Considering you are seeing this problem both with the Kodi addon and the Android TV app, I'm quite certain this is not an issue with this addon, but an underlying issue with either your https setup or the underlying OS.

**Comment by Legogris** [comment]
yeah, the ssl verify error indicates that whatever CA signed the certificate is not trusted on your system.

Either:

* You have really outdated CA root on these devices that don't trust letsencrypt (I find this the less likely option)
* Something is going wrong in your TLS setup (never successfully updating with the signed response from LetsEncrypt, domains mismatching, etc)

If your wildcard cert is for `*.<my-domain>`, it won't work for `jellyfin.nf.<my-domain>`. You'd need `jellyfin.nf.<my-domain>` and/or `*.nf.<my-domain>`.

https://stackoverflow.com/questions/26744696/ssl-multilevel-subdomain-wildcard

**Comment by jeschero** [comment]
i have found the problem, after i test the ssl setup.
The cert chain don't include the root ca. After i added this, the kodi plugin and app works.

Thanks for your help.
