### ISSUE TITLE
Plugin is silently crashing on startup

### ISSUE THREAD

**Issue by eloo** [jellyfin/jellyfin-kodi#379]
**Describe the bug**
It looks like the plugin is silently crashing on my RPI3 since a few days. 
Before it worked mostly without any problem.
But now i'm unable to get it connected or at least startet.

Also the restart plugin action are not responding anything to UI. 

**To Reproduce**
Not sure. Happens directly after start.

**Expected behavior**
Jellyfin is available after i start my RPI

**Logs**
In the logs i see the following execption
```
 NOTICE: JELLYFIN.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:67 Using dynamic paths: True
2020-09-01 22:50:24.586 T:1282204544  NOTICE: JELLYFIN.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:68 Log Level: 2
2020-09-01 22:50:24.641 T:1282204544  NOTICE: JELLYFIN.__main__ -> ERROR::service.py:54 no element found: line 1, column 0
                                            Traceback (most recent call last):
                                              File "service.py", line 47, in run
                                                service = Service()
                                              File "jellyfin_kodi/entrypoint/service.py", line 70, in __init__
                                                verify_kodi_defaults()
                                              File "jellyfin_kodi/views.py", line 127, in verify_kodi_defaults
                                                xml = etree.parse(file).getroot()
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 657, in parse
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1671, in close
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
                                            ParseError: no element found: line 1, column 0
2020-09-01 22:50:24.669 T:1766388608  NOTICE: JELLYFIN.__main__ -> INFO::service.py:92 --<[ service ]
```

**System (please complete the following information):**
 - OS: LibreELEC 9.2.4
 - Jellyfin Version: 10.6.3
 - Kodi Version: 18.8
 - Addon Version: 0.5.8
 - Playback Mode: Add-On

**Comment by oddstr13** [comment]
Looks like one of the following files have been corrupted in your installation (empty?)
This could be caused by powerloss while the files are being written, you should avoid removing power from the Pi without properly shutting it down if at all possible.

#### `$HOME/.kodi/userdata/library/video/movies/index.xml`
```xml
<node order="17" visible="Library.HasContent(Movies)">
	<label>342</label>
	<icon>DefaultMovies.png</icon>
</node>
```
#### `$HOME/.kodi/userdata/library/video/tvshows/index.xml`

```xml
<node order="18" visible="Library.HasContent(TVShows)">
	<label>20343</label>
	<icon>DefaultTVShows.png</icon>
</node>
```
#### `$HOME/.kodi/userdata/library/video/musicvideos/index.xml`
```xml
<node order="19" visible="Library.HasContent(MusicVideos)">
	<label>20389</label>
	<icon>DefaultMusicVideos.png</icon>
</node>
```

**Comment by eloo** [comment]
@oddstr13 
Yes you're right the `$HOME/.kodi/userdata/library/video/movies/index.xml` was empty.
I guess this happend while my RPI was crashing yesterday.
Would be cool if this could be more resilient. For example checking if the is empty and if so the content should be written again as it looks very static.

Thanks
