### ISSUE TITLE
Request missing schema since 0.6.2

### ISSUE THREAD

**Issue by Travolter** [jellyfin/jellyfin-kodi#400]
**Describe the bug**

Recently the plugin stopped working, showing an error pop-up. The logs print a "Request missing schema" error, so I tried downgrading the plugin to version 0.6.1 and then it works again. Not sure if this is a bug or if there's some migration necessary? I can't find any notes on this though. 

**To Reproduce**

1. Go to any media file
2. Try to open it
3. Error

**Logs**
```
2020-09-20 17:18:11.909 T:2480476368  NOTICE: JELLYFIN.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:154 Request missing Schema. Invalid URL '/Users/
{UserId}/Items/60a772decac01e3c3c9d9e3b27849b0b': No schema supplied. Perhaps you meant http:///Users/{UserId}/Items/60a772decac01e3c3c9d9e3b27849b0b?
2020-09-20 17:18:11.916 T:2480476368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'helper.exceptions.HTTPException'>
                                            Traceback (most recent call last):
                                              File "/home/travolter/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 127, in onNotification
                                                item = server.jellyfin.get_item(data['Id'])
                                              File "/home/travolter/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 139, in get_item
                                                return self.users("/Items/%s" % item_id)
                                              File "/home/travolter/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 92, in users
                                                return self._get("Users/{UserId}%s" % handler, params)
                                              File "/home/travolter/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 61, in _get
                                                return self._http("GET", handler, {'params': params})
                                              File "/home/travolter/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 58, in _http
                                                return self.client.request(request)
                                              File "/home/travolter/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/http.py", line 155, in request
                                                raise HTTPException("MissingSchema", {'Id': self.config.data.get('auth.server', "None")})
                                            HTTPException
                                            -->End of Python script error report<--
```

**System (please complete the following information):**
 - OS: Raspbian 10 
 - Jellyfin Version: 10.6.4
 - Kodi Version: 18.7
 - Addon Version: 0.6.2
 - Playback Mode: Add-on

**Comment by mcarlton00** [comment]
Something doesn't add up here.  There's exactly 0 functional difference between 0.6.2 and 0.6.1 except for a version number.  0.6.0-0.6.2 are all essentially the same release, it was just us fighting with the deployment pipeline.  Is there any other context you have about causing this?

**Comment by Waseh** [comment]
I'm also having this issue although for me it has been ongoing ever since i switched to jellyfin from emby
However my error is always prefaced by a connection failure.

`2020-09-25 14:02:57.415 T:10577  NOTICE: JELLYFIN.jellyfin.connection_manager -> ERROR::jellyfin_kodi/jellyfin/connection_manager.py:171 Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/connection_manager.py", line 158, in connect_to_server
                                                result = self.API.get_public_info(server.get('address'))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 441, in get_public_info
                                                response = self.send_request(server_address, "system/info/public")
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 397, in send_request
                                                return request_method(url, **request_settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 529, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='10.0.0.12', port=8096): Read timed out. (read timeout=5)
2020-09-25 14:02:57.420 T:10577  NOTICE: JELLYFIN.jellyfin.connection_manager -> ERROR::jellyfin_kodi/jellyfin/connection_manager.py:172 Failing server connection. ERROR msg: HTTPConnectionPool(host='10.0.0.12', port=8096): Read timed out. (read timeout=5)
2020-09-25 14:02:57.440 T:10577  NOTICE: JELLYFIN.entrypoint.service -> ERROR::jellyfin_kodi/entrypoint/service.py:132 u'Status_Code'
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/entrypoint/service.py", line 128, in start_default
                                                self.connect.register()
                                              File "jellyfin_kodi/connect.py", line 50, in register
                                                new_credentials = self.register_client(credentials, options, server_id, server_select)
                                              File "jellyfin_kodi/connect.py", line 122, in register_client
                                                elif state['State'] == CONNECTION_STATE['Unavailable'] and state['Status_Code'] == 401:
                                            KeyError: u'Status_Code'`


`2020-09-25 14:02:59.744 T:10577  NOTICE: JELLYFIN.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:154 Request missing Schema. Invalid URL '/Users/{UserId}/Items/c4d7f51c46c13fa51a86bda0d2d09679': No schema supplied. Perhaps you meant http:///Users/{UserId}/Items/c4d7f51c46c13fa51a86bda0d2d09679?
2020-09-25 14:02:59.759 T:10577   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'helper.exceptions.HTTPException'>
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 268, in onNotification
                                                on_play(data, server)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/objects/actions.py", line 795, in on_play
                                                item = server.jellyfin.get_item(item[0])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 139, in get_item
                                                return self.users("/Items/%s" % item_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 92, in users
                                                return self._get("Users/{UserId}%s" % handler, params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 61, in _get
                                                return self._http("GET", handler, {'params': params})
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 58, in _http
                                                return self.client.request(request)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/http.py", line 155, in request
                                                raise HTTPException("MissingSchema", {'Id': self.config.data.get('auth.server', "None")})
                                            HTTPException
                                            -->End of Python script error report<--`

A restart of Kodi fixes the issue for a period of time.
I have yet to completely zero in on the cause but i suspect it might have something to do with my jellyfin server going to sleep and perhaps not being available immediately.

The plugin doesn't seem to able to recover from the above unless i restart kodi.

**Comment by rystaf** [comment]
Running version 0.5.8. Same thing started happening to me after pulling the latest linuxserver/jellyfin container a day ago.

**Comment by mcarlton00** [comment]
Does anybody still see this occurring?  I've never manged to replicate it
