### ISSUE TITLE
Unable to sync music

### ISSUE THREAD

**Issue by ReekyMarko** [jellyfin/jellyfin-kodi#41]
I was directed to come here with my debug log. Here it is:
[gitea](https://git.reekynet.com/ReekyMarko/paste/src/branch/master/kodi/kodi-jellyfin.log) | [raw](https://git.reekynet.com/ReekyMarko/paste/raw/branch/master/kodi/kodi-jellyfin.log)

The actions I did while writing to this file:
1. Start kodi
2. Was asked if I wanted to continue the last sync (that failed). Answered no
3. Navigated to jellyfin addon and "Manage libraries"
4. Clicked "Add library" and selected "Music"
5. Was greeted with a message that something went wrong
6. Quit kodi

Running Kodi 18.3-1 and Jellyfin 0.2.0 on Arch Linux

**Comment by oddstr13** [comment]
Looks like your git server is down at the moment.
Could you attach the file directly on GitHub instead?

**Comment by ReekyMarko** [comment]
Yeah sorry it crashed just 10 minutes ago :D

Here is a gist: https://gist.github.com/ReekyMarko/bb7b55758c0bbfab773222227e384da0

**Comment by oddstr13** [comment]
Relevant section of the log;
```
2019-07-14 10:17:49.445 T:140388136453888  NOTICE: JELLYFIN.database -> DEBUG::resources/lib/database/__init__.py:113 Database detected: MyVideos116.db time: 1563088669
2019-07-14 10:17:49.445 T:140388136453888  NOTICE: JELLYFIN.database -> DEBUG::resources/lib/database/__init__.py:113 Database detected: MyVideos107.db time: 1550740340
2019-07-14 10:17:49.446 T:140388136453888  NOTICE: JELLYFIN.database -> INFO::resources/lib/database/__init__.py:120 Discovered database: {'file': u'MyVideos116.db', 'time': 1563088669L}
2019-07-14 10:17:49.452 T:140388136453888  NOTICE: JELLYFIN.database -> INFO::resources/lib/database/__init__.py:165 Database locked in: /home/teabag/.kodi/userdata/Database/MyVideos116.db
2019-07-14 10:17:49.452 T:140388136453888  NOTICE: JELLYFIN.database -> DEBUG::resources/lib/database/__init__.py:56 --->[ database: video ] 140391209886208
2019-07-14 10:17:49.453 T:140388136453888  NOTICE: JELLYFIN.database -> DEBUG::resources/lib/database/__init__.py:113 Database detected: MyMusic60.db time: 1547317926
2019-07-14 10:17:49.453 T:140388136453888  NOTICE: JELLYFIN.database -> DEBUG::resources/lib/database/__init__.py:113 Database detected: MyMusic72.db time: 1563088610
2019-07-14 10:17:49.453 T:140388136453888  NOTICE: JELLYFIN.database -> INFO::resources/lib/database/__init__.py:120 Discovered database: {'file': u'MyMusic72.db', 'time': 1563088610L}
2019-07-14 10:17:49.454 T:140388136453888  NOTICE: JELLYFIN.database -> INFO::resources/lib/database/__init__.py:165 Database locked in: /home/teabag/.kodi/userdata/Database/MyMusic72.db
2019-07-14 10:17:49.455 T:140388136453888  NOTICE: JELLYFIN.database -> DEBUG::resources/lib/database/__init__.py:56 --->[ database: music ] 140391209793160
2019-07-14 10:17:49.455 T:140388136453888  NOTICE: JELLYFIN.database -> DEBUG::resources/lib/database/__init__.py:183 ---<[ database: music ] 140391209793160
2019-07-14 10:17:49.455 T:140388136453888  NOTICE: JELLYFIN.database -> DEBUG::resources/lib/database/__init__.py:183 ---<[ database: video ] 140391209886208
```

```
2019-07-14 10:18:20.765 T:140387649844992  NOTICE: JELLYFIN.objects.music -> INFO::../../userdata/addon_data/plugin.video.jellyfin/jellyfin/objects/music.py:183 UPDATE album [1] Life After Death: 35e29c035428a02368741ac660851519
2019-07-14 10:18:20.766 T:140387649844992  NOTICE: JELLYFIN.database -> ERROR::resources/lib/database/__init__.py:176 type:  value: no such column: strArtists
2019-07-14 10:18:20.766 T:140387649844992  NOTICE: JELLYFIN.database -> INFO::resources/lib/database/__init__.py:180 [jellyfin] 4 rows updated.
2019-07-14 10:18:20.781 T:140387649844992  NOTICE: JELLYFIN.database -> DEBUG::resources/lib/database/__init__.py:183 ---<[ database: jellyfin ] 140388755164384
2019-07-14 10:18:20.786 T:140387649844992  NOTICE: JELLYFIN.database -> ERROR::resources/lib/database/__init__.py:176 type:  value: no such column: strArtists
2019-07-14 10:18:20.786 T:140387649844992  NOTICE: JELLYFIN.database -> INFO::resources/lib/database/__init__.py:180 [music] 5 rows updated.
2019-07-14 10:18:20.797 T:140387649844992  NOTICE: JELLYFIN.database -> DEBUG::resources/lib/database/__init__.py:183 ---<[ database: music ] 140388742818808
2019-07-14 10:18:20.804 T:140387649844992  NOTICE: JELLYFIN.full_sync -> ERROR::resources/lib/full_sync.py:251 no such column: strArtists
                                            Traceback (most recent call last):
                                              File "resources/lib/full_sync.py", line 242, in process_library
                                                media[library['CollectionType']](library)
                                              File "resources/lib/helper/wrapper.py", line 38, in wrapper
                                                result = func(self, dialog=dialog, *args, **kwargs)
                                              File "resources/lib/full_sync.py", line 419, in music
                                                obj.album(album)
                                              File "resources/lib/helper/wrapper.py", line 98, in wrapper
                                                return func(*args, **kwargs)
                                              File "resources/lib/helper/wrapper.py", line 111, in wrapper
                                                return func(self, item, e_item=e_item, *args, **kwargs)
                                              File "/home/teabag/.kodi/userdata/addon_data/plugin.video.jellyfin/jellyfin/objects/music.py", line 165, in album
                                                self.update_album(*values(obj, QU.update_album_obj))
                                              File "/home/teabag/.kodi/userdata/addon_data/plugin.video.jellyfin/jellyfin/objects/kodi/music.py", line 154, in update_album
                                                self.cursor.execute(QU.update_album, args)
                                            OperationalError: no such column: strArtists
2019-07-14 10:18:20.818 T:140391974333120   DEBUG: ------ Window Init (DialogConfirm.xml) ------
2019-07-14 10:18:21.892 T:140388161632000   ERROR: No handlers could be found for logger "root"
2019-07-14 10:18:21.893 T:140388161632000  NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:76 tuple index out of range
2019-07-14 10:18:22.237 T:140391974333120   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x000d, modifier: 0x0
2019-07-14 10:18:22.337 T:140391974333120   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x0000, modifier: 0x0
2019-07-14 10:18:22.337 T:140391974333120   DEBUG: HandleKey: return (0xf00d) pressed, action is Select
2019-07-14 10:18:22.555 T:140391974333120   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
2019-07-14 10:18:22.570 T:140387649844992  NOTICE: JELLYFIN.full_sync -> ERROR::resources/lib/full_sync.py:256 full sync exited unexpectedly
2019-07-14 10:18:22.571 T:140387649844992  NOTICE: JELLYFIN.helper.utils -> DEBUG::resources/lib/helper/utils.py:43 --[ window clear: jellyfin_sync ]
2019-07-14 10:18:22.571 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: loading setting definitions
2019-07-14 10:18:22.571 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: trying to load setting definitions from old format...
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: loading setting values
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CSettingsManager: requested setting (LastIncrementalSync) was not found.
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting LastIncrementalSync. Creating a setting on-the-fly...
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CSettingsManager: requested setting (MinimumSetup) was not found.
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting MinimumSetup. Creating a setting on-the-fly...
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CSettingsManager: requested setting (MusicRescan) was not found.
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting MusicRescan. Creating a setting on-the-fly...
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CSettingsManager: requested setting (SyncInstallRunDone) was not found.
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting SyncInstallRunDone. Creating a setting on-the-fly...
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CSettingsManager: requested setting (groupedSets) was not found.
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting groupedSets. Creating a setting on-the-fly...
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CSettingsManager: requested setting (platformDetected) was not found.
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting platformDetected. Creating a setting on-the-fly...
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CSettingsManager: requested setting (useWebServer) was not found.
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting useWebServer. Creating a setting on-the-fly...
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CSettingsManager: requested setting (webServerPass) was not found.
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting webServerPass. Creating a setting on-the-fly...
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CSettingsManager: requested setting (webServerPort) was not found.
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting webServerPort. Creating a setting on-the-fly...
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CSettingsManager: requested setting (webServerUser) was not found.
2019-07-14 10:18:22.572 T:140387649844992   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting webServerUser. Creating a setting on-the-fly...
2019-07-14 10:18:22.573 T:140387649844992  NOTICE: JELLYFIN.full_sync -> INFO::resources/lib/full_sync.py:569 --<[ fullsync ]
2019-07-14 10:18:22.574 T:140387649844992  NOTICE: JELLYFIN.library -> ERROR::resources/lib/library.py:526 no such column: strArtists
                                            Traceback (most recent call last):
                                              File "resources/lib/library.py", line 524, in add_library
                                                sync.libraries(library_id, update)
                                              File "resources/lib/full_sync.py", line 103, in libraries
                                                self.start()
                                              File "resources/lib/full_sync.py", line 193, in start
                                                self.process_library(library)
                                              File "resources/lib/full_sync.py", line 242, in process_library
                                                media[library['CollectionType']](library)
                                              File "resources/lib/helper/wrapper.py", line 38, in wrapper
                                                result = func(self, dialog=dialog, *args, **kwargs)
                                              File "resources/lib/full_sync.py", line 419, in music
                                                obj.album(album)
                                              File "resources/lib/helper/wrapper.py", line 98, in wrapper
                                                return func(*args, **kwargs)
                                              File "resources/lib/helper/wrapper.py", line 111, in wrapper
                                                return func(self, item, e_item=e_item, *args, **kwargs)
                                              File "/home/teabag/.kodi/userdata/addon_data/plugin.video.jellyfin/jellyfin/objects/music.py", line 165, in album
                                                self.update_album(*values(obj, QU.update_album_obj))
                                              File "/home/teabag/.kodi/userdata/addon_data/plugin.video.jellyfin/jellyfin/objects/kodi/music.py", line 154, in update_album
                                                self.cursor.execute(QU.update_album, args)
                                            OperationalError: no such column: strArtists
2019-07-14 10:18:22.602 T:140391974333120   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.jellyfin/?mode=managelibs)
2019-07-14 10:18:22.602 T:140391974333120   DEBUG:   ParentPath = [plugin://plugin.video.jellyfin/?mode=managelibs]
2019-07-14 10:18:22.602 T:140387616274176   DEBUG: Thread waiting start, auto delete: false
2019-07-14 10:18:22.611 T:140391231760128   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.jellyfin] took 10 ms
2019-07-14 10:18:22.612 T:140387616274176   DEBUG: StartScript - calling plugin Jellyfin('plugin://plugin.video.jellyfin/','3','?mode=managelibs','resume:false')
2019-07-14 10:18:22.612 T:140388144940800   DEBUG: Thread LanguageInvoker start, auto delete: false
2019-07-14 10:18:22.612 T:140388144940800    INFO: initializing python engine.
```

This looks like the error fixed in #32, but that the version detection isn't working properly

**Comment by oddstr13** [comment]
I was having serious trouble getting this part of the code to (miss)behave.

It turns out that this part of the code is getting cached in some weird way (copied to a different directory if it doesn't already exist there).

Running the following should clear that out.
```bash
find $HOME/.kodi/userdata/addon_data/plugin.video.jellyfin/jellyfin/ -ls -delete
```

This would also explain the comments in #32 complaining about having to "reset", "start clean" etc.

**Comment by oddstr13** [comment]
@ReekyMarko could you test if deleting the directory mentioned above and restarting Kodi fixes the issue for you, then report back here?

**Comment by ReekyMarko** [comment]
Thanks a lot! I actually have no way of testing this right now as the aformentioned server crash killed my jellyfin also.

**Comment by oddstr13** [comment]
Ah. The actual server died?
Best of luck getting it back up and running! :)

**Comment by ReekyMarko** [comment]
Well a HDD died, but thanks :)

**Comment by apatosaur** [comment]
I think I had the same issue. Removing the addon data folder (as described above) solved the issue.
