### ISSUE TITLE
Installation page should mention that non-local database, like MySQL, is not supported

### ISSUE THREAD

**Issue by robinsmidsrod** [jellyfin/jellyfin-kodi#411]
The [how to install Jellyfin for Kodi documentation page](https://jellyfin.org/docs/general/clients/kodi.html) should mention that only local (sqlite) database is supported, and any remote databases, like MySQL, is not supported by this addon.

The error message you get in the log,
```
Traceback (most recent call last):
  File "jellyfin_kodi/library.py", line 315, in startup
	sync.libraries()
  File "jellyfin_kodi/full_sync.py", line 101, in libraries
	self.start()
  File "jellyfin_kodi/full_sync.py", line 186, in start
	self.process_library(library)
  File "jellyfin_kodi/full_sync.py", line 243, in process_library
	media[library['CollectionType']](library)
  File "jellyfin_kodi/helper/wrapper.py", line 41, in wrapper
	result = func(self, dialog=dialog, *args, **kwargs)
  File "jellyfin_kodi/full_sync.py", line 291, in movies
	obj.movie(movie)
  File "jellyfin_kodi/helper/wrapper.py", line 65, in wrapper
	return func(*args, **kwargs)
  File "jellyfin_kodi/helper/wrapper.py", line 77, in wrapper
	return func(self, item, e_item=e_item, *args, **kwargs)
  File "jellyfin_kodi/objects/movies.py", line 102, in movie
	self.add_countries(*values(obj, QU.update_country_obj))
  File "jellyfin_kodi/objects/kodi/movies.py", line 104, in add_countries
	self.cursor.execute(QU.update_country, (self.get_country(country),) + args)
  File "jellyfin_kodi/objects/kodi/movies.py", line 113, in get_country
	self.cursor.execute(QU.get_country, args)
OperationalError: no such column: country_id
```

is confusing, when you should've gotten a message that your setup with an external database is not supported.

Had at least one of these been added, I would've saved a lot of time trying to figure out what was wrong with my setup.

This was tested on LibreELEC 9.2.4 (Kodi 18.8-Leia) with MyVideos database version 116 on MySQL version 5.7.31-0ubuntu0.18.04.1.

**Comment by oddstr13** [comment]
We always appreciate good documentation updates :wink: 
https://github.com/jellyfin/jellyfin-docs
https://github.com/jellyfin/jellyfin-docs/blob/master/general/clients/kodi.md

**Comment by robinsmidsrod** [comment]
@oddstr13 I've tried to add something to the documentation. Improving the error message is not something I know how to do, but adding a small check during "database open" that you actually have a local database connection would probably be good enough.
