### ISSUE TITLE
Can’t play any videos in Native Mode

### ISSUE THREAD

**Issue by kauniss** [jellyfin/jellyfin-kodi#451]
**Describe the bug**
Can’t play videos, haven’t been able to whatsoever since installation was complete. I’m running native mode.

**To Reproduce**
Nothing to reproduce except, click play on any film

**Expected behavior**
That the film plays

**Logs**

2020-12-21 02:08:28.114 T:123145342521344  NOTICE: VideoInfoScanner: Starting scan ..
2020-12-21 02:08:28.116 T:123145342521344  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
2020-12-21 02:08:28.188 T:123145354317824  NOTICE: JELLYFIN.monitor -> INFO::jellyfin_kodi/monitor.py:43 -->[ kodi scan/video ]
2020-12-21 02:08:28.191 T:123145354317824  NOTICE: JELLYFIN.monitor -> INFO::jellyfin_kodi/monitor.py:46 --<[ kodi scan/video ]
2020-12-21 02:08:45.526 T:4787760576  NOTICE: VideoPlayer::OpenFile: smb://192.168.xx.xxx/Test/amazingfilm
2020-12-21 02:08:45.527 T:123145335009280  NOTICE: Creating InputStream
2020-12-21 02:08:45.717 T:123145335009280  NOTICE: Creating Demuxer
2020-12-21 02:08:45.717 T:123145335009280   ERROR: Read - Error( -1, 53, Software caused connection abort )
2020-12-21 02:08:45.717 T:123145335009280   ERROR: Open - error probing input format, smb://192.168.xx.xxx/Test/amazingfilm
2020-12-21 02:08:45.717 T:123145335009280   ERROR: OpenDemuxStream - Error creating demuxer
2020-12-21 02:08:45.717 T:123145335009280  NOTICE: CVideoPlayer::OnExit()
2020-12-21 02:08:45.732 T:4787760576  NOTICE: CVideoPlayer::CloseFile()
2020-12-21 02:08:45.815 T:4787760576  NOTICE: VideoPlayer: waiting for threads to exit
2020-12-21 02:08:45.815 T:4787760576  NOTICE: VideoPlayer: finished waiting
2020-12-21 02:08:45.820 T:123145354317824  NOTICE: JELLYFIN.objects.actions -> INFO::jellyfin_kodi/objects/actions.py:776  [ play ] kodi_id: 1 media: movie
2020-12-21 02:08:45.833 T:123145354317824   ERROR: EXCEPTION: XBMC is not playing any file
2020-12-21 02:08:45.841 T:123145354317824  NOTICE: JELLYFIN.objects.actions -> ERROR::jellyfin_kodi/objects/actions.py:791 XBMC is not playing any file
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/objects/actions.py", line 789, in on_play
                                                file = player.getPlayingFile()
                                              File "/Users/xx/Library/Application Support/Kodi/addons/script.module.kodi-six/libs/kodi_six/utils.py", line 62, in wrapper
                                                return py2_decode(func(*mod_args, **mod_kwargs),
                                            RuntimeError: XBMC is not playing any file
2020-12-21 02:08:45.949 T:123145354317824  NOTICE: JELLYFIN.player -> INFO::jellyfin_kodi/player.py:376 --<[ playback ]
2020-12-21 02:08:46.692 T:4787760576  NOTICE: VideoPlayer::OpenFile: smb://192.168.xx.xxx/Test/amazingfilm
2020-12-21 02:08:46.694 T:123145335009280  NOTICE: Creating InputStream
2020-12-21 02:08:46.880 T:123145335009280  NOTICE: Creating Demuxer
2020-12-21 02:08:46.880 T:123145335009280   ERROR: Read - Error( -1, 53, Software caused connection abort )
2020-12-21 02:08:46.880 T:123145335009280   ERROR: Open - error probing input format, smb://192.168.xx.xxx/Test/amazingfilm
2020-12-21 02:08:46.880 T:123145335009280   ERROR: OpenDemuxStream - Error creating demuxer
2020-12-21 02:08:46.880 T:123145335009280  NOTICE: CVideoPlayer::OnExit()
2020-12-21 02:08:46.900 T:4787760576  NOTICE: CVideoPlayer::CloseFile()
2020-12-21 02:08:46.983 T:4787760576  NOTICE: VideoPlayer: waiting for threads to exit
2020-12-21 02:08:46.983 T:4787760576  NOTICE: VideoPlayer: finished waiting

And on it goes.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: [macOS Catalina 10.15.7]
 - Jellyfin Version: [e.g. 10.0.1]
 - Kodi Version: [18.9.0]
 - Jellyfin Addon Version: [0.6.5+py2]
 - JellyCon Addon Version: [0.3.0)
 - Playback Mode: [Native]

**Additional context**
This is my first time installing Kodi, but have had Jellyfin up and running for a long time without hickups, so likely a newbie mistake in the Jellyfin4Kodi or Kodi configuration here somewhere.
Eg., dont know if JellyCon is supposed to be installed? I've got both Kodi and Jellyfin set up and running on my Mac but not yet any Kodi clients for my TV (planning on making a raspberry pi4 Kodi client), so I dont really need films to play on Kodi Mac... but I thought it's worth investigating anyway; might mean I cant play on my future Kodi clients either. 
I turned off hardware acceleration and any transcoding in Kodi and Jellyfin. “Enable Jellyfin for Kodi” is on, as well as “Kodi Sync Queue” and it syncs well. As mentioned, as files show up. Playback mode is verified to be set to native.

**Comment by oddstr13** [comment]
This looks like miss-configured native mode; Kodi isn't able to open the provided native path (the smb://…).

If there is no particular reason for why you *need* to use native path, I would highly recommend to use addon mode (the default).

You do *not* need JellyCon, that is a completely separate addon.

**Comment by kauniss** [comment]
I definitely want to use native mode for that sweet direct play of all 7.1 formats. And delted JellyCon, thanks for the advice.

I'm at a complete loss as to how I should do this. 

The network share path I write in Jellyfin are: "\\192.168.68.xxx\Folder\Folder", which is per the official documentation (https://jellyfin.org/docs/general/clients/kodi.html#install-jellyfin-for-kodi-add-on). In Kodi, according to their official documentation (https://kodi.wiki/view/SMB), in order to add my SMB server I've already set up in Jellyfin, I need to write first the IP address (see link) and separately write in the folder including a drive letter, which I don't have on Mac so only write folder (it'll refuse the connection if I append with "Volume/" first). 

So it appears I've followed all the steps but I still cannot get it to work. Any ideas?

**Comment by mcarlton00** [comment]
So unfortunately none of the devs actually use Native mode.  It's a headache to manage and provides no benefit for us.  We can't even tell you for sure if 7.1 works in Native or Addon mode.  The only concrete thing I've seen in the code is that if a video is transcoding, it gets limited to 5.1.  But Kodi rarely, if ever, transcodes unless you manually tell it to.

The only real test of this that I can think of is to go to your media sources in Kodi and verify you can actually browse them and see your media in the correct spots.

**Comment by kauniss** [comment]
Well, I have spent 2 days trying to get native mode to work and I don't feel like giving up. It should be possible to get working... 

> The only real test of this that I can think of is to go to your media sources in Kodi and verify you can actually browse them and see your media in the correct spots.

I can browse the media and play it directly from the drive in Kodi, no issues.

Right now, I'm going to try this [https://radusuciu.com/posts/setup-jellyfin-for-kodi/](suggestion), which is to use nfs instead.

**Comment by kauniss** [comment]
I've figured out what I did wrong. Both SMB and NFS work now without issues.

I'm ashamed to say (yes yes, laugh at me) I did a complete rookie mistake. As mentioned, I've set up the Kodi client on my Mac to test it and install everything, same IP as my media. So the IP I should have used wasn't 192.168.xx.xxx but rather the localhost IP, 127.0.0.1:port.  

You gotta learn sometime I guess. ¯\_(ツ)_/¯

**Comment by kauniss** [comment]
It does still raise a question about whether Jellyfin should have a matching IP set up in the shared folder path...

**Comment by kauniss** [comment]
Setting up the NFS server was the solution for me and now I've got Kodi to work perfectly with Jellyfin through the add-on on macOS. I'll explain incase anyone else out there have issues getting Native Mode to work on Mac. 

Firstly, the solution certainly wasn't to use the 127.0.0.1 localhost IP, even though it allowed me to access and play the movies directly from a network share for the first time in Kodi. I could not get SMB servers to work whatsoever on macOS, testing as many options and configurations as I could in macOS File Sharing (smb) settings, having referred to official Kodi and Jellyfin documentation on how to set it up. This remains a question mark.

The issue was I entered the network credentials in Kodi. Unfortunately I must say, the Jellyfin4Kodi documentation (https://jellyfin.org/docs/general/clients/kodi.html) regarding this was very vague and actually misleading. As I've chosen to use Native Mode and NFS, the documentation informs me to enter the shared network path as follows:

- NFS in Jellyfin: "nfs://192.168.xx.xxx:/path/to/media"
- NFS in Kodi: "Create either a NFS or SMB location from the selection box and fill in the necessary information about your network share"

So, firstly, the Jellyfin path format is wrong: the ":" after the IP should be removed. It should be: "nfs://192.168.xx.xxx/path/to/media". 
It's understandable that it's included, as this is the standard format for nfs. But as this guy (https://radusuciu.com/posts/setup-jellyfin-for-kodi/ ) emphasised, the path in Jellyfin has to be identical to the one in Kodi. 

How I should enter the network path in Kodi, was not specified in the documentation. It is simply necessary to enter as little information as possible: 

"Add network location"... 
> 
"Protocol" = "Network File System"
 > 
"Server address" = "192.168.xx.xxx" (nothing more)" 
>
"Remote path" = "Volumes/MountDrive/Folder"

The resultant address will be: "nfs://192.168.xx.xxx/Volumes/MountDrive/Folder"

**Comment by mcarlton00** [comment]
The docs are open source as well.  Especially since you went through the effort to figure out the issues, feel free to make a PR and get some credit for your work. https://github.com/jellyfin/jellyfin-docs/blob/master/general/clients/kodi.md

Unfortunately this is one of those things where we're pretty much fully reliant on the community.  Since none of us have a use for Native mode (and frankly it's sort of a hack to begin with), some of it's workings are a bit of a black box that only gets looked at in rare occurrences.

**Comment by kauniss** [comment]
> The docs are open source as well. Especially since you went through the effort to figure out the issues, feel free to make a PR and get some credit for your work

I will do that! :) I just need to do some further testing.

For anyone else having issues, I've figured out how to get SMB-servers to work on macOS Catalina 10.15.7; forcing the SMB1 protocol (SMB minimum to 1 and maximum to 1). For some reason, the protocols of SMB2 and SMB3 from this macOS won't permit Kodi to access them (no issues accessing them in other apps though, such as through the iOS or tvOS app "Infuse").
