### ISSUE TITLE
Unable to log in to jellyfin from kodi 19

### ISSUE THREAD

**Issue by richardbrodie** [jellyfin/jellyfin-kodi#478]
**Describe the bug**
On a fresh install of the new kodi 19, with just the jellyfin-kodi plugin, I am unable to authenticate. I am connecting locally to an IP on the same network. An identical setup works with the previous kodi 18 client.

**To Reproduce**
1. Fresh install of kodi 19
2. Install jellyfin-kodi plugin (0.7.0-py3)
3. Enter server address
4. Enter username and password
5. See "Invalid username or password"
6. See above output on server

**Expected behavior**
I should log in and be able to start syncing

**Logs**
```
jellyfinx       | [14:34:23] [ERR] [231] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /Users/AuthenticateByName.
jellyfinx       | System.ArgumentException: Invalid username (Parameter 'name')
jellyfinx       |    at Jellyfin.Server.Implementations.Users.UserManager.GetUserByName(String name)
jellyfinx       |    at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
jellyfinx       |    at Jellyfin.Api.Controllers.UserController.AuthenticateUserByName(AuthenticateUserByName request)
jellyfinx       |    at lambda_method773(Closure , Object )
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jellyfinx       | --- End of stack trace from previous location ---
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
jellyfinx       | --- End of stack trace from previous location ---
jellyfinx       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfinx       |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jellyfinx       |    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfinx       |    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfinx       |    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfinx       |    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfinx       |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfinx       |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfinx       |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfinx       |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfinx       |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfinx       |    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfinx       |    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfinx       |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
jellyfinx       |    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
jellyfinx       |    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**System (please complete the following information):**
 - OS: Ubuntu 20.10
 - Jellyfin Version: 10.8.0 nightly
 - Kodi Version: 19
 - Addon Version: 0.7.0-py3
 - Playback Mode: N/A

**Comment by mcarlton00** [comment]
I'm not sure what has changed to make it stop working, but targeting unstable/nightly is a moving target and is not a priority, particularly since we're still working through the RC process for 10.7 and 10.8 isn't planned out yet.  This may not be looked into for some time.

**Comment by richardbrodie** [comment]
Thanks for the reply. It's slightly disappointing that a regression that renders the whole server unusable isn't considered interesting but hey.

I will try the rc branch, and see if it works any better. But I'm currently dependent on the linuxserver docker images because they are ubuntu based instead of debian based, which is necessary for the mesa dependencies jellyfin realistically depends on.

**Comment by thornbill** [comment]
“Unstable” is called that for a reason. Breakages happen frequently. 😉

**Comment by richardbrodie** [comment]
A fair point. What's the testing situation like? These kinds of regressions should be very easy to catch if the right tests are in place.

**Comment by thornbill** [comment]
The testing situation is not great currently. It is an area we are focusing on improving for the next release cycle though.

**Comment by oddstr13** [comment]
The testing situation is usually me or @mcarlton00 loading up the relevant Kodi version and pointing it at whatever Jellyfin version we want to test.

For me, this currently is Kodi 19 nightly against Jellyfin 10.6.4, cause this is how I consume content.
I do occasionally test against a 10.7 test server, but not so often.

There is no automated testing for API compatibility (yet).
Our inherited code base is still a tightly interconnected un-testable mess.

This particular issue is a regression in the server's API backwards compat, and should be fixed there.

**Comment by richardbrodie** [comment]
To be fair nobody's testing situation is ever as good as they'd like, especially in the case of an inherited project like this. I've reported this upstream, so I'll close this in favour of that one.
