### ISSUE TITLE
Constant database crashes on Kodi

### ISSUE THREAD

**Issue by zynexiz** [jellyfin/jellyfin-kodi#496]
I had this problem back and forth for a amount of time. Sometimes when I try scan my library to Kodi, the scanning hangs and don't keep going. I need to stop Kodi altogether for it to abort. When trying to re-scan it, the scanning gets stuck again. Even thought I get is to work after some trial and error (hopefully), after a random amount of days/weeks, the the add-on stops syncing again (mostly know because new shows stop showing up).

When I try re-syncing it again, the same thing happens. If I delete all databases, it work some times, and sometimes it don't. It's like playing on lottery or something. The add-on itself seems to make Kodi less stable to, crashes a lot randomly. Thinking of ditching the add-on all together soon and use it the old fashion way, it's just brakes way to easy.

Any idea how to make it less crashable (might have missed some crucial part?), the idea behind it otherwise is really good and when it works it works good.

System running Kodi:
Arch Linux (headless), kernel 5.11, kodi-gbm 19.0-9, Jellyfin Plugin 0.7.0+py3 
Jellyfin server:
CentOS Stream, kernel 5.11, jellyfin-server/web 10.7.0

Error in kodi.log related to jellyfin addon:
```
2021-03-31 21:44:26.130 T:2615     INFO <general>: JELLYFIN.database -> ERROR::jellyfin_kodi/database/__init__.py:163 type: <class 'sqlite3.IntegrityError'> value: UNIQUE constraint failed: actor.name

.......

2021-03-31 21:44:23.834 T:2597    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not callable
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 148, in onNotification
                                                       self.server_instance(data['ServerId'])
                                                     File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 163, in server_instance
                                                       self.post_capabilities(server)
                                                     File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 183, in post_capabilities
                                                       server.jellyfin.post_capabilities({
                                                     File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 312, in post_capabilities
                                                       return self.sessions("/Capabilities/Full", "POST", json=data)
                                                     File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 80, in sessions
                                                       return self._post("Sessions%s" % handler, json, params)
                                                     File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 64, in _post
                                                       return self._http("POST", handler, {'params': params, 'json': json})
                                                     File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 58, in _http
                                                       return self.client.request(request)
                                                     File "/home/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/http.py", line 169, in request
                                                       response = r.json()
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "/usr/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/usr/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
                                                       obj, end = self.raw_decode(s)
                                                     File "/usr/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                                       return self.scan_once(s, idx=_w(s, idx).end())
                                                     File "/usr/lib/python3.9/site-packages/simplejson/errors.py", line 41, in __init__
                                                       ValueError.__init__(self, errmsg(msg, doc, pos, end=end))
                                                     File "/usr/lib/python3.9/site-packages/simplejson/errors.py", line 17, in errmsg
                                                       msg = msg.replace('%r', repr(doc[pos:pos + 1]))
                                                   TypeError: 'NoneType' object is not callable
                                                   -->End of Python script error report<--
```

**Comment by mcarlton00** [comment]
Duplicate of #469 

This should have been fixed with addon version 0.7.1.  Please update to the latest release

**Comment by zynexiz** [comment]
I saw that 0.7.1 was out a while ago, odd that the repo only has v0.7.0. I'll reinstall the repo and check again.

**Comment by zynexiz** [comment]
Not sure why it stayed on old version (other addons have been updated recently), but now it's on v0.7.1, and seems to sync without issue. Keep my fingers x-ed :)
