### ISSUE TITLE
Sync no longer works if it did not work on Kodi startup

### ISSUE THREAD

**Issue by flashkiller999** [jellyfin/jellyfin-kodi#524]
**Describe the bug**
When Kodi starts (und subsequently Jellyfin Addon) and the datetime is not yet synced from NTP server, Jellyfin stops syncing and Sync cannot be restarted again. No error message is shown, only in the logfile an error is logged (see below).
However after the DateTime is correctly snyced (5-10 seconds after Kodi started) playback of already synced files can be played back, but playback status (eg Episode completed) will not be synced and gets lost.

The problem is caused by a certificate the client believes to be invalid.
Eg SystemDateTime = 2019-04-11 18:28:51
Certificate Validity Start DateTime = 2021-04-15 15:14:16

**To Reproduce**
1. (Re-)Start Kodi while having slow DateTime Sync on startup

**Expected behavior**
Retry Sync with JellyfinServer after a period of time (eg 1 minute)
and/or show visible error message that server was not reachable because of certificate failure

**Logs**

```
2019-04-11 18:28:51.581 T:2630349680  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:241 Found Servers: []
2019-04-11 18:28:51.587 T:2630349680  NOTICE: JELLYFIN.jellyfin.credentials -> DEBUG::jellyfin_kodi/jellyfin/credentials.py:58 credentialsupdated
2019-04-11 18:28:51.593 T:2630349680  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:180 connect has 1 servers
2019-04-11 18:28:51.599 T:2630349680  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:155 begin connectToServer
2019-04-11 18:28:51.611 T:2630349680  NOTICE: JELLYFIN.jellyfin.api -> INFO::jellyfin_kodi/jellyfin/api.py:393 Sending get request to system/info/public
2019-04-11 18:28:51.617 T:2630349680  NOTICE: JELLYFIN.jellyfin.api -> DEBUG::jellyfin_kodi/jellyfin/api.py:394 5
2019-04-11 18:28:51.623 T:2630349680  NOTICE: JELLYFIN.jellyfin.api -> DEBUG::jellyfin_kodi/jellyfin/api.py:395 {u'Accept-encoding': u'gzip', u'x-emby-authorization': 'MediaBrowser Client=Kodi, Device=Kodi (KodiVie), DeviceId=85001bd3-34f7-4fc4-a5c5-112562d8e1c9, Version=0.7.1+py2', u'Accept': u'application/json', u'User-Agent': u'Jellyfin-Kodi/0.7.1+py2', u'X-Application': u'Kodi/0.7.1+py2', u'Accept-Charset': u'UTF-8,*', u'Content-type': u'application/x-www-form-urlencoded; charset=UTF-8'}
2019-04-11 18:28:51.697 T:2630349680  NOTICE: JELLYFIN.jellyfin.connection_manager -> ERROR::jellyfin_kodi/jellyfin/connection_manager.py:171 Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/connection_manager.py", line 158, in connect_to_server
                                                result = self.API.get_public_info(server.get('address'))
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 441, in get_public_info
                                                response = self.send_request(server_address, "system/info/public")
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 397, in send_request
                                                return request_method(url, **request_settings)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 514, in send
                                                raise SSLError(e, request=request)
                                            SSLError: HTTPSConnectionPool(host='{jellyfin-server}', port=443): Max retries exceeded with url: /system/info/public (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
2019-04-11 18:28:51.702 T:2630349680  NOTICE: JELLYFIN.jellyfin.connection_manager -> ERROR::jellyfin_kodi/jellyfin/connection_manager.py:172 Failing server connection. ERROR msg: HTTPSConnectionPool(host='{jellyfin-server}', port=443): Max retries exceeded with url: /system/info/public (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
2019-04-11 18:28:51.707 T:2630349680  NOTICE: JELLYFIN.jellyfin.connection_manager -> DEBUG::jellyfin_kodi/jellyfin/connection_manager.py:188 resolving connect with result: {u'State': 0}
2019-04-11 18:28:51.725 T:2630349680  NOTICE: JELLYFIN.entrypoint.service -> ERROR::jellyfin_kodi/entrypoint/service.py:130 u'Status_Code'
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/entrypoint/service.py", line 126, in start_default
                                                self.connect.register()
                                              File "jellyfin_kodi/connect.py", line 50, in register
                                                new_credentials = self.register_client(credentials, options, server_id, server_select)
                                              File "jellyfin_kodi/connect.py", line 121, in register_client
                                                elif state['State'] == CONNECTION_STATE['Unavailable'] and state['Status_Code'] == 401:
                                            KeyError: u'Status_Code'
2019-04-11 18:29:00.517 T:2580910960   ERROR: Previous line repeats 7 times.
```

**System:**
 - OS: LibreElec (9 and 10)
 - Jellyfin Version: 10.7.5
 - Kodi Version: 18.9 and 19.1 (Based on LiberElec version)
 - Addon Version: 0.7.3
 - Playback Mode: Add-On

**Workaround:**
Add a delay to the startup of LibreElec and Kodi:
echo "sleep 30" >> /storage/.config/autostart.sh

**Comment by mcarlton00** [comment]
If the time is wrong, the time is wrong and there's nothing we can do about that code wise.  You can delay the startup of the addon in the settings instead of delaying starting Kodi entirely.  

`Addons -> Jellyfin -> Settings -> Advanced -> Startup delay`

I don't think it makes sense to have it retry the sync like you're suggesting, because in the large majority of cases, if it doesn't work the first time, it's not going to work shortly after either.  You're just generating more network traffic and noise.  This is very much a niche edge case that feature would solve.  However we can fix the `Status_Code` error so that it should properly display an error dialog when this happens.

**Comment by flashkiller999** [comment]
Thanks for the info.
Delay was set in the Jellyfin settings.

**Comment by mcarlton00** [comment]
Increasing the delay fixed the issue, or it's still not working?

**Comment by zehnerGIT** [comment]
The missing 2nd resync could be a problem for embedded devices (CoreElec, Rasperries, ...). They don't have a real time clock, so on first attempt, the time is set to 1970/01/01 00:00:00 (if the plugin starts before the ntp-service) and is never corrected.

I always wondered, why playing back an episode on my CoreElec-devices with JellyCon changed the watched-state on my Jellyfin-server, but the watched state never synchronizes to my NUCs with the regular Jellyfin-Kodi-Plugin, but that sounds like a possible explanation of this problem.
