### ISSUE TITLE
Sync shows stuck

### ISSUE THREAD

**Issue by HarHarLinks** [jellyfin/jellyfin-kodi#552]
**Describe the bug**
Syncing TV shows gets stuck. Always the same show/episode.
I tried resetting local db, addon and native modes, etc.

As far as I could tell in the debug log, it was always a case of "virtual episodes". However other shows that also have them sync fine.
Also movies sync fine, I suppose because there are no missing episodes.

Finally I started temporarily removing the offending shows from my library to try adding them back later.

Finally I got an actual error message:

**To Reproduce**

1. initial sync

**Expected behavior**
/

**Logs**
```
2021-08-01 14:06:58.375 T:602      INFO <general>: JELLYFIN.objects.tvshows -> INFO::jellyfin_kodi/objects/tvshows.py:263 Skipping virtual episode [...]
2021-08-01 14:06:58.376 T:602      INFO <general>: JELLYFIN.database -> ERROR::jellyfin_kodi/database/__init__.py:164 type: <class 'KeyError'> value: 'Name'
2021-08-01 14:06:58.377 T:602      INFO <general>: JELLYFIN.database -> DEBUG::jellyfin_kodi/database/__init__.py:168 [jellyfin] 288 rows updated.
2021-08-01 14:06:58.386 T:602      INFO <general>: JELLYFIN.database -> DEBUG::jellyfin_kodi/database/__init__.py:171 ---<[ database: jellyfin ] 139925138849840
2021-08-01 14:06:58.396 T:602      INFO <general>: JELLYFIN.database -> ERROR::jellyfin_kodi/database/__init__.py:164 type: <class 'KeyError'> value: 'Name'
2021-08-01 14:06:58.397 T:602      INFO <general>: JELLYFIN.database -> DEBUG::jellyfin_kodi/database/__init__.py:168 [video] 5502 rows updated.
2021-08-01 14:06:58.411 T:602      INFO <general>: JELLYFIN.database -> DEBUG::jellyfin_kodi/database/__init__.py:171 ---<[ database: video ] 139925138853200
2021-08-01 14:10:28.464 T:602      INFO <general>: JELLYFIN.full_sync -> ERROR::jellyfin_kodi/full_sync.py:276 full sync exited unexpectedly
2021-08-01 14:10:28.468 T:602      INFO <general>: JELLYFIN.full_sync -> ERROR::jellyfin_kodi/full_sync.py:277 'Name'
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/full_sync.py", line 262, in process_library
                                                       media[library['CollectionType']](library)
                                                     File "jellyfin_kodi/helper/wrapper.py", line 41, in wrapper
                                                       result = func(self, dialog=dialog, *args, **kwargs)
                                                     File "jellyfin_kodi/full_sync.py", line 359, in tvshows
                                                       dialog.update(percent, message="%s/%s" % (message, episode['Name'][:10]))
                                                   KeyError: 'Name'

2021-08-01 14:10:28.471 T:602      INFO <general>: JELLYFIN.helper.utils -> DEBUG::jellyfin_kodi/helper/utils.py:48 --[ window clear: jellyfin_sync ]
2021-08-01 14:10:28.477 T:602      INFO <general>: JELLYFIN.full_sync -> INFO::jellyfin_kodi/full_sync.py:605 --<[ fullsync ]
2021-08-01 14:10:28.479 T:602      INFO <general>: JELLYFIN.library -> ERROR::jellyfin_kodi/library.py:381 'Name'
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/library.py", line 338, in startup
                                                       sync.libraries()
                                                     File "jellyfin_kodi/full_sync.py", line 111, in libraries
                                                       self.start()
                                                     File "jellyfin_kodi/full_sync.py", line 195, in start
                                                       self.process_library(library)
                                                     File "jellyfin_kodi/full_sync.py", line 262, in process_library
                                                       media[library['CollectionType']](library)
                                                     File "jellyfin_kodi/helper/wrapper.py", line 41, in wrapper
                                                       result = func(self, dialog=dialog, *args, **kwargs)
                                                     File "jellyfin_kodi/full_sync.py", line 359, in tvshows
                                                       dialog.update(percent, message="%s/%s" % (message, episode['Name'][:10]))
                                                   KeyError: 'Name'

2021-08-01 14:10:28.496 T:602      INFO <general>: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:105 ---<[ library ]
```

**Screenshots**

**System (please complete the following information):**
 - OS: arch
 - Jellyfin Version: docker latest
 - Kodi Version: 19.1
 - Addon Version: 0.7.4+py3
 - Playback Mode: both

**Additional context**

**Comment by mcarlton00** [comment]
Interesting.  From your logs it appears that you're missing metadata for some episodes and that's causing the sync to lockup.  What do you mean by "virtual episodes" in this case?

**Comment by HarHarLinks** [comment]
> What do you mean by "virtual episodes" in this case?

episodes added to the library by the missing episodes plugin. those that have no actual file present but only metadata.

**Comment by RealStickman** [comment]
I have the same issue with syncing shows.  
Disabling the Display of missing episodes for the user or removing the plugin makes Shows sync normally.  

Jellyfin: 10.7.7 on Debian
Kodi: 18.9 (LibreELEC 9.2.6)
Addon Version: 0.7.7+py2

[Log file](https://pastebin.com/AaGERy28)
