### ISSUE TITLE
API call `/Videos/ActiveEncodings` is missing the `PlaySessionId` argument

### ISSUE THREAD

**Issue by jessbo** [jellyfin/jellyfin-kodi#557]
**Describe the bug**

API call `/Videos/ActiveEncodings` is missing the `PlaySessionId` argument.

**To Reproduce**

1. Enable transcoding
2. Play w/transcoding
3. Errors at close_transcode()

**Expected behavior**

```
2021-08-21 10:03:59.674 T:660728    INFO <general>: JELLYFIN.player -> INFO::jellyfin_kodi/player.py:416 <[ transcode/5e0d3d02d38f834bd81000a41b0bfd86 ]
2021-08-21 10:04:00.192 T:660728    INFO <general>: JELLYFIN.player -> INFO::jellyfin_kodi/player.py:386 --<<[ playback ]
```

**Logs**

```
2021-08-20 19:11:50.090 T:24038    INFO <general>: JELLYFIN.player -> INFO::jellyfin_kodi/player.py:424 <[ transcode/4326fcd028916ea9c25bf213726cc44d ]
2021-08-20 19:11:50.135 T:24038    INFO <general>: JELLYFIN.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:124 400 Client Error: Bad Request for url: https://{jellyfin-server}/Videos/ActiveEncodings?DeviceId=08f80990-e8bb-4e9e-828f-75b3b444c0e0
2021-08-20 19:11:50.140 T:24038    INFO <general>: JELLYFIN.jellyfin.http -> WARNING::jellyfin_kodi/jellyfin/http.py:139 400 Client Error: Bad Request for url: https://{jellyfin-server}/Videos/ActiveEncodings?DeviceId=08f80990-e8bb-4e9e-828f-75b3b444c0e0
2021-08-20 19:11:50.145 T:24038    INFO <general>: JELLYFIN.jellyfin.http -> WARNING::jellyfin_kodi/jellyfin/http.py:140 {'params': {'DeviceId': '08f80990-e8bb-4e9e-828f-75b3b444c0e0'}, 'url': 'https://{jellyfin-server}/Videos/ActiveEncodings', 'headers': {'Content-type': 'application/json', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-Kodi/0.7.4+py3', 'x-emby-authorization': 'MediaBrowser Client=Kodi, Device=RPi_Front, DeviceId=08f80990-e8bb-4e9e-828f-75b3b444c0e0, Version=0.7.4+py3, UserId=db5ad0f17a10436dbfc1779b9e702edc', 'X-MediaBrowser-Token': '{jellyfin-token}'}, 'timeout': 30, 'verify': True}
2021-08-20 19:11:50.151 T:24038    INFO <general>: JELLYFIN.jellyfin.http -> WARNING::jellyfin_kodi/jellyfin/http.py:142 {'type': 'https://tools.ietf.org/html/rfc7231#section-6.5.1', 'title': 'One or more validation errors occurred.', 'status': 400, 'traceId': '00-d7a71c84b46f4941bc1434e850839dab-670a95779a8a1040-00', 'errors': {'playSessionId': ['The playSessionId field is required.']}}
2021-08-20 19:11:50.152 T:24038   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'helper.exceptions.HTTPException'>
                                                   Error Contents: (400, HTTPError('400 Client Error: Bad Request for url: https://{jellyfin-server}/Videos/ActiveEncodings?DeviceId=08f80990-e8bb-4e9e-828f-75b3b444c0e0'))
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/http.py", line 96, in request
                                                       r.raise_for_status()
                                                     File "/var/lib/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://{jellyfin-server}/Videos/ActiveEncodings?DeviceId=08f80990-e8bb-4e9e-828f-75b3b444c0e0
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/player.py", line 385, in onPlayBackEnded
                                                       self.stop_playback()
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/player.py", line 425, in stop_playback
                                                       item['Server'].jellyfin.close_transcode(item['DeviceId'])
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 360, in close_transcode
                                                       return self._delete("Videos/ActiveEncodings", params={
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 67, in _delete
                                                       return self._http("DELETE", handler, {'params': params})
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 58, in _http
                                                       return self.client.request(request)
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/http.py", line 159, in request
                                                       raise HTTPException(r.status_code, error)
                                                   helper.exceptions.HTTPException: (400, HTTPError('400 Client Error: Bad Request for url: https://{jellyfin-server}/Videos/ActiveEncodings?DeviceId=08f80990-e8bb-4e9e-828f-75b3b444c0e0'))
                                                   -->End of Python script error report<--
```

**Additional context**

Fixed with https://github.com/jessbo/plugin.video.jellyfin/commit/7131abd47e69902ca3352d9408cbcd98dded85c9 and https://github.com/jessbo/plugin.video.jellyfin/commit/1cce37b1dc20cfb6aad12d4ddb244eaa97caadca.  Not entirely sure if the second commit is needed.

**Comment by mcarlton00** [comment]
Since it seems as though you've already tracked down the error location and fixed it, feel free to open a PR and get credit for your efforts.
