### ISSUE TITLE
Doesn't login in additional server 

### ISSUE THREAD

**Issue by diff75** [jellyfin/jellyfin-kodi#562]
**Describe the bug**
After add additional server, it doesn't login

**To Reproduce**
1. Click Jellyfin in left menu Add-ons
2. Click Add server (works fine)
3. Click Login to added server
4. See nothing

**Expected behavior**
Show modal window to enter username and password
**Logs**
NOTICE: JELLYFIN.__main__ -> ERROR::default.py:37 '27668418cfef478ea9268d152c2ee8e8'
                                            Traceback (most recent call last):
                                              File "default.py", line 35, in <module>
                                                Events()
                                              File "jellyfin_kodi/entrypoint/default.py", line 57, in __init__
                                                jellyfin_client = Jellyfin(server).get_client()
                                              File "jellyfin_kodi/jellyfin/__init__.py", line 58, in get_client
                                                return self.client[self.server_id]
                                            KeyError: '27668418cfef478ea9268d152c2ee8e8'

**System (please complete the following information):**
 - OS: Debian 11
 - Jellyfin Version: 10.7.6
 - Kodi Version: 18.9
 - Addon Version: 0.7.4+py2
 - Playback Mode: Add-On

**Comment by mcarlton00** [comment]
As far as I'm aware, support for multiple servers is literally impossible in the current codebase.  I'm not sure why that option was ever even included back in the Emby days, but I don't think it's possible to have multiple servers be available at the same time.

The problem is that things are stored in the database like so: `plugin://plugin.video.jellyfin/9276c0693276926e40192244218f3723/`.  Meaning that then we have to manually keep track of that `9276c0693276926e40192244218f3723` ID and remember which server it belongs to in order to make the right request.  That's not happening anywhere currently.

**Comment by Serph91P** [comment]
Only Workaround I found till now is to use 2 User Profiles for the 2 different Servers, but would be great to be able to add 2 Servers in one.
