### ISSUE TITLE
[0.7.5py2] not connecting to server

### ISSUE THREAD

**Issue by Cissoubaka** [jellyfin/jellyfin-kodi#587]
**Describe the bug**
turn on my wetek play 2 on Coreelec 9.2.8 this morning, and it throws an error, just found out the kodi plugin was updated to 0.7.5, but can't connect, everything works fine if I downgrade plugin to 0.7.4

**Logs**
[log](https://0bin.net/paste/0RWARQ6Y#sxA8VUgUMQtC+MyqXrIaxM-yUFHuGcLAsTxCeJzkI63)

**System (please complete the following information):**
 - OS: Coreelec 9.2.8
 - Jellyfin Version: 10.7.7
 - Kodi Version: 18.9
 - Addon Version: 0.7.5py2
 - Playback Mode: add-on

**Comment by plains203** [comment]
I am also having the same issue and resolved it the same way. I am running Kodi 18.5 on Windows 10x64

Log File
[https://0bin.net/paste/CK3uzZ5A#tBX7gWcVjpDzfYcheId36PguxD85iJezmPO2pHHVTgL](url)

**Comment by plains203** [comment]
> @Cissoubaka, @plains203: could you please try 0.7.6, and see if that fixes your issue?

Ok this does not resolve the issue. 

Log File [https://0bin.net/paste/OPe0hjgn#FgxEjsTMqjUBufsThiMOHScrki1WKIMfc+oX62y9wcD](url)

Getting this error
`2021-10-20 15:15:30.493 T:25464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named enum `

**Comment by Cissoubaka** [comment]
@oddstr13 same error than @plains203 

`2021-10-20 07:20:49.516 T:3745502080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named enum
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/service.py", line 10, in <module>
                                                from jellyfin_kodi.entrypoint.service import Service
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/service.py", line 15, in <module>
                                                from .. import objects
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/objects/__init__.py", line 8, in <module>
                                                from .actions import Actions
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/objects/actions.py", line 13, in <module>
                                                from ..helper import translate, playutils, api, window, settings, dialog
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/playutils.py", line 6, in <module>
                                                import enum
                                            ImportError: No module named enum
                                            -->End of Python script error report<--`

**Comment by jessbo** [comment]
Does [this branch](https://github.com/jessbo/plugin.video.jellyfin/tree/mediadefault-py2) correct this?  I don't have an older version of Kodi for local testing.

**Comment by joulester** [comment]
I have this on the latest issue on libreelec with 7.6.

**Comment by Cissoubaka** [comment]
> Does [this branch](https://github.com/jessbo/plugin.video.jellyfin/tree/mediadefault-py2) correct this? I don't have an older version of Kodi for local testing.

I don't know how to test it

**Comment by oddstr13** [comment]
I would strongly recommend updating to Kodi 19 if you are able.

The `enum` issue is fixed in 0.7.7.
