### ISSUE TITLE
Missing manage libraries option on builds older that 0.7.4

### ISSUE THREAD

**Issue by Tomcatter31** [jellyfin/jellyfin-kodi#613]
Manage libraries option is missing on jellyfin plugin versions greater than 0.7.4

Reproduce
Install version. 0.7.4
Navigate into jellyfin
Setting is there

Update to 0.7.5
Navigate into jellyfin
Option will be missing.

**Comment by mcarlton00** [comment]
How are you accessing the jellyfin addon in this case?  I have 0.7.7 installed right now and going to addons -> video addons -> jellyfin loads correctly for me

**Comment by Tomcatter31** [comment]
The add on loads, however if you open the add on you used to see all the libraries then a button stating manage libraries, this is the button which is missing

Sent from my Sprint Samsung Galaxy S20 Ultra 5G.
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mcarlton00** [comment]
![2022-02-03-183435_1921x1078_scrot](https://user-images.githubusercontent.com/17029228/152447080-abbc1e10-097a-4e27-9697-ab8ff165c6b7.png)

I'm not able to replicate the issue

**Comment by Tomcatter31** [comment]
Using an nvidia shield and shield pro

Settings > Addons > my Addons > video addons

Version. 0.77

Gives below

[Image]
 Same access method on 0.74

[Image]

As no settings change, a simple upgrade / downgrade reproduces



Sent from my Sprint Samsung Galaxy S20 Ultra 5G.
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mcarlton00** [comment]
Your images don't attach when you reply via email

**Comment by hillbicks** [comment]
I can report the same issue. 

Jellyfin Server is version 10.7.7
Jellyfin Addon 0.7.7+py3
Kodi 19.3 on a nvidia shield pro running android 9

- Favorite Movies
- Movies
- TV Shows
- Favorite Shows
- Favorite Episodes

This is missing for a long time now, can't really say when it disappeared, not something you look at every day. I've only seen the websocket connection from the client in the jellyfin server logs, nothing to indicate something is missing. But I suspect it is something on the client side that's missing.

**Comment by hillbicks** [comment]
Some further information. I forgot that I have the same issue on a nvidia shield (non pro model). 

I tried a couple of things: 
- remove the addon, leave user data, reinstall-> same result
- remove the addon and userdata, reinstall -> same result. 

I then looked at the kodi logs on the shield and low and behold, this is what I got:

```
2022-02-06 16:27:36.102 T:12007   ERROR <general>: Control 500 in window 10025 has been asked to focus, but it can't
2022-02-06 16:27:36.134 T:16231    INFO <general>: initializing python engine.
2022-02-06 16:27:37.296 T:16231    INFO <general>: JELLYFIN -> INFO::jellyfin_kodi/jellyfin/__init__.py:98 ---[ START JELLYFINCLIENT ]---
2022-02-06 16:27:37.303 T:16231    INFO <general>: JELLYFIN.jellyfin_kodi.entrypoint.default -> INFO::jellyfin_kodi/entrypoint/default.py:72 path:  params: {}
2022-02-06 16:27:37.307 T:16231    INFO <general>: JELLYFIN.jellyfin_kodi.entrypoint.default -> INFO::jellyfin_kodi/entrypoint/default.py:263 --[ v:plugin.video.jellyfin/ ] None
2022-02-06 16:27:37.374 T:16231    INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:124 400 Client Error: Bad Request for url: http://{jellyfin-server}/Users/376e689688d74bcbbd5e7e951d894adf/Items/plugin.video.jellyfin
2022-02-06 16:27:37.381 T:16231    INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.http -> WARNING::jellyfin_kodi/jellyfin/http.py:139 400 Client Error: Bad Request for url: http://{jellyfin-server}/Users/376e689688d74bcbbd5e7e951d894adf/Items/plugin.video.jellyfin
2022-02-06 16:27:37.386 T:16231    INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.http -> WARNING::jellyfin_kodi/jellyfin/http.py:140 {'params': None, 'url': 'http://{jellyfin-server}/Users/376e689688d74bcbbd5e7e951d894adf/Items/plugin.video.jellyfin', 'headers': {'Content-type': 'application/json', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin for Kodi/0.0.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin for Kodi, Device=Unknown Device, DeviceId=Unknown Device id, Version=0.0.0, UserId=376e689688d74bcbbd5e7e951d894adf', 'X-MediaBrowser-Token': '{jellyfin-token}'}, 'timeout': 30, 'verify': False}
2022-02-06 16:27:37.391 T:16231    INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.http -> WARNING::jellyfin_kodi/jellyfin/http.py:142 {'type': 'https://tools.ietf.org/html/rfc7231#section-6.5.1', 'title': 'One or more validation errors occurred.', 'status': 400, 'traceId': '00-a8eeff5c39f53341bb0dd0f458bff6e5-4b3b24dc62040640-00', 'errors': {'itemId': ["The value 'plugin.video.jellyfin' is not valid."]}}
2022-02-06 16:27:37.411 T:16231    INFO <general>: JELLYFIN.__main__ -> ERROR::default.py:23 (400, HTTPError('400 Client Error: Bad Request for url: http://{jellyfin-server}/Users/376e689688d74bcbbd5e7e951d894adf/Items/plugin.video.jellyfin'))
Traceback (most recent call last):
File "jellyfin_kodi/jellyfin/http.py", line 96, in request
r.raise_for_status()
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://{jellyfin-server}/Users/376e689688d74bcbbd5e7e951d894adf/Items/plugin.video.jellyfin

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "default.py", line 21, in <module>
Events()
File "jellyfin_kodi/entrypoint/default.py", line 149, in __init__
browse('', item_id, None, server, api_client)
File "jellyfin_kodi/entrypoint/default.py", line 289, in browse
view = api_client.get_item(view_id)
File "jellyfin_kodi/jellyfin/api.py", line 139, in get_item
return self.users("/Items/%s" % item_id)
File "jellyfin_kodi/jellyfin/api.py", line 92, in users
return self._get("Users/{UserId}%s" % handler, params)
File "jellyfin_kodi/jellyfin/api.py", line 61, in _get
return self._http("GET", handler, {'params': params})
File "jellyfin_kodi/jellyfin/api.py", line 58, in _http
return self.client.request(request)
File "jellyfin_kodi/jellyfin/http.py", line 159, in request
raise HTTPException(r.status_code, error)
jellyfin_kodi.helper.exceptions.HTTPException: (400, HTTPError('400 Client Error: Bad Request for url: http://{jellyfin-server}/Users/376e689688d74bcbbd5e7e951d894adf/Items/plugin.video.jellyfin'))

2022-02-06 16:27:37.417 T:16231    INFO <general>: JELLYFIN.__main__ -> INFO::default.py:25 ---<[ default ]
2022-02-06 16:27:37.418 T:16231    INFO <general>: CPythonInvoker(9, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/default.py): script successfully run
2022-02-06 16:27:37.763 T:16231    INFO <general>: Python interpreter stopped
2022-02-06 16:27:37.776 T:16229   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.jellyfin/
2022-02-06 16:27:37.778 T:12007   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellyfin/) failed
```

settings.xml on the shield, server and username redacted. 

```
<settings version="2">
<setting id="idMethod" default="true">0</setting>
<setting id="username">USERNAME</setting>
<setting id="serverName">jellyfin</setting>
<setting id="server">http://jellyfin:8096</setting>
<setting id="sslverify">true</setting>
<setting id="deviceNameOpt" default="true">false</setting>
<setting id="deviceName" default="true">Kodi</setting>
<setting id="kodiCompanion">true</setting>
<setting id="syncIndicator">999</setting>
<setting id="syncDuringPlay">true</setting>
<setting id="dbSyncScreensaver">true</setting>
<setting id="useDirectPaths">1</setting>
<setting id="limitIndex">15</setting>
<setting id="limitThreads">3</setting>
<setting id="enableCoverArt">true</setting>
<setting id="compressArt" default="true">false</setting>
<setting id="maxArtResolution">5</setting>
<setting id="enableMusic">true</setting>
<setting id="enableCinema">true</setting>
<setting id="askCinema" default="true">false</setting>
<setting id="playFromStream">true</setting>
<setting id="playFromTranscode" default="true">false</setting>
<setting id="maxBitrate">23</setting>
<setting id="enableExternalSubs">true</setting>
<setting id="transcodeHi10P" default="true">false</setting>
<setting id="transcode_h265" default="true">false</setting>
<setting id="transcode_mpeg2" default="true">false</setting>
<setting id="transcode_vc1" default="true">false</setting>
<setting id="transcode_vp9" default="true">false</setting>
<setting id="transcode_av1" default="true">false</setting>
<setting id="videoPreferredCodec" default="true">H264/AVC</setting>
<setting id="audioPreferredCodec" default="true">AAC</setting>
<setting id="audioBitrate">4</setting>
<setting id="audioMaxChannels">6</setting>
<setting id="skipDialogTranscode">3</setting>
<setting id="allowBurnedSubs">true</setting>
<setting id="resumeJumpBack">10</setting>
<setting id="offerDelete" default="true">false</setting>
<setting id="deleteTV" default="true">false</setting>
<setting id="deleteMovies" default="true">false</setting>
<setting id="markPlayed">90</setting>
<setting id="enableContext">true</setting>
<setting id="enableContextTranscode">true</setting>
<setting id="enableContextDelete">true</setting>
<setting id="skipContextMenu" default="true">false</setting>
<setting id="additionalUsers" default="true" />
<setting id="connectMsg">true</setting>
<setting id="offlinetMsg">true</setting>
<setting id="restartMsg">true</setting>
<setting id="displayMessage">4</setting>
<setting id="syncProgress">15</setting>
<setting id="newContent" default="true">false</setting>
<setting id="newvideotime">5</setting>
<setting id="newmusictime">2</setting>
<setting id="ignoreSpecialsNextEpisodes" default="true">false</setting>
<setting id="getCast" default="true">false</setting>
<setting id="logLevel">1</setting>
<setting id="maskInfo">true</setting>
<setting id="enableAddon">true</setting>
<setting id="startupDelay" default="true">0</setting>
<setting id="devMode" default="true">false</setting>
<setting id="backupPath" default="true" />
<setting id="SyncInstallRunDone" default="true">true</setting>
<setting id="groupedSets" default="true">false</setting>
<setting id="platformDetected" default="true">Linux/Android</setting>
<setting id="LastIncrementalSync" default="true">2022-02-06T15:23:00z</setting>
</settings>
```

Still nothing in the jellyfin server logs during that time though. As you can see, I'm using native paths (nfs) and they're working. Syncing works fine and I can play Movies/Series. The device is also displayed as active on the jellyfin admin dashboard. 

If you need any further information on anything that I can do on my side to debug this, just let me know.

**Comment by Kidswiss** [comment]
Can confirm, have the same issue.

Was able to reproduce it on fresh Kodi installs on following systems:
* MacOS
* FireTV
* Libreelec

I've done fresh installs, added my Jellyfin server, let it sync the library and then checked the options. None of them show the "manage libraries" menu.

**Comment by mcarlton00** [comment]
I don't mean to be demeaning here, so I hope nobody takes it that way, but we just keep getting updates about it happening, I can't make it happen, and looking at the code, what's being described appears to be impossible.

This is the function that generates the addon menu when nothing else is selected (ie: when you select 'jellyfin' and the menu loads) - https://github.com/jellyfin/jellyfin-kodi/blob/master/jellyfin_kodi/entrypoint/default.py#L154-L215

It starts by checking all of the jellyfin libraries it knows about and choosing whether they should be displayed as a normal library or a "dynamic" library, and adds the relevant context menu options for each of them. (lines 154-190)

It then loops through servers it knows about and adds relevant options for those. (lines 192-201)

Finally, it adds the options for manage libraries, add server, add user to session, etc etc. (lines 203-209).  There's no conditionals around these.  There's no loops that could be exiting before it happens.  These happen literally every time the function is called.  It doesn't matter how many libraries are found, it doesn't matter how many servers it knows about, it doesn't even matter if the addon is configured, these options are programmed to show up every time.  This is what happens when I install the addon, and refuse to go through the setup wizard then open the addon.

![2022-04-02-175744_1897x1047_scrot](https://user-images.githubusercontent.com/17029228/161402639-cf08a214-84f9-4747-85d1-c6f721a8c328.png)

I've tried this on Arch, Ubuntu, libreelec, my android phone, and a windows VM.  Open kodi's home page, scroll down to Add-ons, select "Jellyfin" from any of the options available (video, music, etc, doesn't matter) and I get the above image, or the one from further up the thread where I do have libraries configured.  I literally can't make it not work, and I'm completely at a loss as to what's happening.  I need something concrete.  Preferably logs showing an error message.  Screenshots.  _Something_.  Otherwise, my hands are completely tied here.

**Comment by Tomcatter31** [comment]
I have moved to emby, however as per my original ticket, under the plugin
settings, not under the video > jellyfin the option will be missing

**Comment by Kidswiss** [comment]
Hi @mcarlton00 

Thanks for the more detailed explanation. I've tried it exactly as you've described it and then it works!

It looks like it breaks depending on how you access the plugin though.

If I go Settings -> Add-Ons -> My add-ons -> All -> Jellyfin -> Open, then it won't show up.

Not sure if this is now the expected behaviour or a bug. It used to show up there, too.

**Comment by mcarlton00** [comment]
That was the key piece of info I was missing.  Naturally, there's multiple ways of opening things and Kodi sends us slightly different data from each that we have to process

**Comment by Kidswiss** [comment]
Cool!

Glad I was able to help here! :)
