### ISSUE TITLE
Playback stops every few min and kodi loses connection to server

### ISSUE THREAD

**Issue by roc16** [jellyfin/jellyfin-kodi#632]
**Describe the bug**
Playback of media stops after a few min. 
Looking at the activity on the jellyfin dashboard, the kodi client disconnects and reconnects every few min as well.
This only happens on kodi 19.4 Matrix.
I can successfully play all media from Kodi 18.9, iOS and Windows
It was working ok until a few days ago (I can't figure out what changed)
To troubleshoot I reinstalled Kodi from scratch, installed only Jellyfin and got the log you see below. 
Full log is available if I didn't capture the useful information below.

Any help from you is greatly appreciated.

**To Reproduce**

Just play a video or launch kodi

**Expected behavior**
Video should play without losing connection
Kodi should not disconnect from server every few min

**Logs**
2022-04-05 20:36:36.845 T:3808    ERROR <general>: Process - <nfs://x.x.x.x/volume1/media/movies/K****S (2022)/K****S - --1080p--1080p.mkv> source read failed with -4!
2022-04-05 20:36:37.071 T:3810    DEBUG <general>: CVideoPlayerVideo - CDVDMsg::GENERAL_SYNCHRONIZE
2022-04-05 20:36:37.071 T:3807     INFO <general>: waiting for video thread to exit
2022-04-05 20:36:37.071 T:3810    ERROR <general>: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2022-04-05 20:36:37.071 T:3810     INFO <general>: thread end: video_thread
2022-04-05 20:36:37.071 T:3810    DEBUG <general>: Thread VideoPlayerVideo 3360924288 terminating
2022-04-05 20:36:37.071 T:3807     INFO <general>: deleting video codec
2022-04-05 20:36:37.071 T:3807    DEBUG <general>: CAMLCodec::CloseDecoder
2022-04-05 20:36:37.097 T:3807     INFO <general>: Closing stream player 3
2022-04-05 20:36:37.098 T:3852    DEBUG <general>: Thread JobWorker start, auto delete: true
2022-04-05 20:36:37.099 T:3808    DEBUG <general>: Thread FileCache 3648832128 terminating
2022-04-05 20:36:37.100 T:3807    DEBUG <general>: CNFSFile::Close closing file volume1/media/movies/K****S (2022)/K****S - --1080p--1080p.mkv
2022-04-05 20:36:37.101 T:3807    DEBUG <general>: Thread VideoPlayer 3657224832 terminating
2022-04-05 20:36:37.104 T:3852     INFO <general>: Deleting settings information for files nfs://x.x.x.x/volume1/media/movies/K****S (2022)/K****S - --1080p--1080p.mkv
2022-04-05 20:36:37.106 T:3853    DEBUG <general>: Thread JobWorker start, auto delete: true
2022-04-05 20:36:37.106 T:3853    DEBUG <general>: DoWork - Saving file state for video item nfs://x.x.x.x/volume1/media/movies/K****S (2022)/K****S - --1080p--1080p.mkv
2022-04-05 20:36:37.159 T:3776    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:36:37.160 T:3776    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:36:37.160 T:3776    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:36:37.160 T:3776    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:36:37.160 T:3776    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:36:37.162 T:3776    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:36:37.163 T:3776    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:36:37.164 T:3776    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:36:37.164 T:3776    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:36:37.164 T:3776    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:36:37.164 T:3776     INFO <general>: JELLYFIN.jellyfin_kodi.objects.actions -> INFO::jellyfin_kodi/objects/actions.py:720  [ update/0 ] kodi_id: 626 media: movie
2022-04-05 20:36:37.166 T:3776    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:36:37.168 T:3776    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:36:37.168 T:3776    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:36:37.168 T:3776    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:36:37.168 T:3776    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:36:37.170 T:3852    DEBUG <general>: OnPlayBackEnded: CApplication::OnPlayBackEnded
2022-04-05 20:36:37.172 T:3656     INFO <general>: CVideoPlayer::CloseFile()
2022-04-05 20:36:37.172 T:3776    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:36:37.172 T:3656    DEBUG <general>: DeleteRenderer - deleting renderer
2022-04-05 20:36:37.172 T:3656    DEBUG <general>: CAMLVideoBufferPool::~CAMLVideoBufferPool: Deleting 9 buffers
2022-04-05 20:36:37.173 T:3656     INFO <general>: VideoPlayer: waiting for threads to exit
2022-04-05 20:36:37.173 T:3656     INFO <general>: VideoPlayer: finished waiting
2022-04-05 20:36:37.173 T:3656     INFO <general>: CVideoPlayer::CloseFile()
2022-04-05 20:36:37.173 T:3656     INFO <general>: VideoPlayer: waiting for threads to exit
2022-04-05 20:36:37.173 T:3656     INFO <general>: VideoPlayer: finished waiting
2022-04-05 20:36:37.174 T:3656    DEBUG <general>: Radio UECP (RDS) Processor - delete ~CDVDRadioRDSData
2022-04-05 20:36:37.174 T:3656    DEBUG <general>: CGUIWindowManager::PreviousWindow: Deactivate
2022-04-05 20:36:37.174 T:3656    DEBUG <general>: ------ Window Deinit (VideoFullScreen.xml) ------
2022-04-05 20:36:37.174 T:3776    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:36:37.174 T:3776    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:36:37.174 T:3776    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:36:37.174 T:3776    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:36:37.182 T:3656    DEBUG <general>: AMLUtils::aml_handle_display_stereo_mode old mode 3doff new mode 3doff
2022-04-05 20:36:37.182 T:3656    DEBUG <general>: AMLUtils::aml_handle_display_stereo_mode - no change needed
2022-04-05 20:36:37.348 T:3656    DEBUG <general>: AMLUtils::aml_handle_display_stereo_mode old mode 3doff new mode 3doff
2022-04-05 20:36:37.348 T:3656    DEBUG <general>: AMLUtils::aml_handle_display_stereo_mode - no change needed
2022-04-05 20:36:37.348 T:3656     INFO <general>: GLES: Maximum texture width: 8192
2022-04-05 20:36:37.350 T:3656    DEBUG <general>: CGUIWindowManager::PreviousWindow: Activate new
2022-04-05 20:36:37.350 T:3656    DEBUG <general>: ------ Window Init (Home.xml) ------
2022-04-05 20:36:37.381 T:3656    DEBUG <general>: CDirectoryProvider[library://video/movies/]: refreshing..
2022-04-05 20:36:37.381 T:3656    DEBUG <general>: CDirectoryProvider[special://skin/playlists/inprogress_movies.xsp]: refreshing..
2022-04-05 20:36:37.381 T:3656    DEBUG <general>: CDirectoryProvider[special://skin/playlists/recent_unwatched_movies.xsp]: refreshing..
2022-04-05 20:36:37.381 T:3656    DEBUG <general>: CDirectoryProvider[special://skin/playlists/unwatched_movies.xsp]: refreshing..
2022-04-05 20:36:37.381 T:3656    DEBUG <general>: CDirectoryProvider[special://skin/playlists/random_movies.xsp]: refreshing..
2022-04-05 20:36:37.381 T:3853    ERROR <general>: GetDirectory - Error getting library://video/movies/
2022-04-05 20:36:37.394 T:3862    DEBUG <general>: Thread JobWorker start, auto delete: true
2022-04-05 20:36:37.396 T:3656    DEBUG <general>: CDirectoryProvider[videodb://movies/genres/]: refreshing..
2022-04-05 20:36:37.396 T:3656    DEBUG <general>: CDirectoryProvider[videodb://movies/sets/]: refreshing..
2022-04-05 20:36:37.396 T:3656    DEBUG <general>: CDirectoryProvider[library://video/tvshows/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[videodb://inprogresstvshows]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[special://skin/playlists/recent_unwatched_episodes.xsp]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[special://skin/playlists/unwatched_tvshows.xsp]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[videodb://tvshows/genres/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[videodb://tvshows/studios/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[addons://]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[addons://sources/video/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[addons://sources/audio/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[addons://sources/game/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[addons://sources/executable/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[addons://sources/image/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[library://video/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[sources://video/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[special://videoplaylists/]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[favourites://]: refreshing..
2022-04-05 20:36:37.397 T:3656    DEBUG <general>: CDirectoryProvider[sources://pictures/]: refreshing..
2022-04-05 20:36:37.398 T:3656    DEBUG <general>: CDirectoryProvider[addons://sources/game/]: refreshing..
2022-04-05 20:36:37.406 T:3776    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:36:37.406 T:3656    DEBUG <general>: ffmpeg[(nil)X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2022-04-05 20:36:37.409 T:3776    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:36:37.409 T:3776    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:36:37.410 T:3776    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:36:37.410 T:3776    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:36:37.434 T:3853    DEBUG <general>: easy_acquire - Created session to http://x.x.x.x
2022-04-05 20:36:37.503 T:3656     INFO <general>: Skipped 2 duplicate messages..
2022-04-05 20:36:37.503 T:3656    DEBUG <general>: ffmpeg[(nil)X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2022-04-05 20:36:37.525 T:3863    DEBUG <general>: Thread JobWorker start, auto delete: true
2022-04-05 20:36:37.526 T:3863    DEBUG <general>: ffmpeg[0x2c5a570X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2022-04-05 20:36:37.534 T:3776    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:36:37.536 T:3776    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:36:37.536 T:3776    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:36:37.536 T:3776    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:36:37.536 T:3776    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:36:37.539 T:3776    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:36:37.540 T:3776    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:36:37.540 T:3776    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:36:37.540 T:3776    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:36:37.540 T:3776    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:36:37.643 T:3776    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:36:37.644 T:3776    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:36:37.644 T:3776    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:36:37.644 T:3776    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:36:37.644 T:3776    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:36:37.645 T:3776     INFO <general>: JELLYFIN.jellyfin_kodi.player -> INFO::jellyfin_kodi/player.py:393 Played info: {'nfs://x.x.x.x/volume1/media/movies/K****S (2022)/K****S - --1080p--1080p.mkv': {'Type': 'Movie', 'Id': '3d6d5acb8adad10d3de777b9f9e0f189', 'Path': 'nfs://x.x.x.x/volume1/media/movies/K****S (2022)/K****S - --1080p--1080p.mkv', 'PlayMethod': 'DirectPlay', 'PlayOption': 'Native', 'MediaSourceId': '3d6d5acb8adad10d3de777b9f9e0f189', 'Runtime': 53468000256, 'PlaySessionId': 'b701402e225449908216670bf3e485a5', 'ServerId': None, 'DeviceId': '55594fd6-0f5d-40ae-8e78-520b83c73652', 'SubsMapping': None, 'AudioStreamIndex': None, 'SubtitleStreamIndex': None, 'CurrentPosition': 37, 'CurrentEpisode': None, 'File': 'nfs://x.x.x.x/volume1/media/movies/K****S (2022)/K****S - --1080p--1080p.mkv', 'Muted': False, 'Volume': 100, 'Server': <jellyfin_kodi.jellyfin.client.JellyfinClient object at 0xea99a078>, 'Paused': False}}
2022-04-05 20:36:37.646 T:3776    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:36:37.648 T:3776    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:36:37.648 T:3776    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:36:37.648 T:3776    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:36:37.648 T:3776    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:36:39.481 T:3862    DEBUG <general>: CCurlFile::GetMimeType - http://x.x.x.x:8096/Items/2d9f070699e3354d536ba0adcfbe757e/Images/Primary/0?Format=original&Tag=c5885dd05a623c1fee17666cfe9c0a5a -> image/jpeg
http://x.x.x.x:8096/Items/2cce5c8b1ea2848a784fc0e5fdf29da0/Images/Primary/0?Format=original&Tag=a985e9d9a40c7dcdf2ecbe1bb278b5f7
2022-04-05 20:36:39.937 T:3862    DEBUG <general>: CFileCache::Open - <http://x.x.x.x:8096/Items/2cce5c8b1ea2848a784fc0e5fdf29da0/Images/Primary/0?Format=original&Tag=a985e9d9a40c7dcdf2ecbe1bb278b5f7> source chunk size is 0, setting cache chunk size to 131072
2022-04-05 20:36:39.940 T:3862    DEBUG <general>: CFileCache::Open - <http://x.x.x.x:8096/Items/2cce5c8b1ea2848a784fc0e5fdf29da0/Images/Primary/0?Format=original&Tag=a985e9d9a40c7dcdf2ecbe1bb278b5f7> using single memory cache sized 205998 bytes
2022-04-05 20:36:39.947 T:3865    DEBUG <general>: Thread FileCache start, auto delete: false
2022-04-05 20:36:39.965 T:3865    DEBUG <general>: CFileCache::Process - <http://x.x.x.x:8096/Items/2cce5c8b1ea2848a784fc0e5fdf29da0/Images/Primary/0?Format=original&Tag=a985e9d9a40c7dcdf2ecbe1bb278b5f7> source read hit eof
2022-04-05 20:36:40.015 T:3862    DEBUG <general>: ffmpeg[0xf0801b68X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2022-04-05 20:36:40.082 T:3865    DEBUG <general>: Thread FileCache 3752841856 terminating
2022-04-05 20:36:40.082 T:3862    DEBUG <general>: Caching image 'http://x.x.x.x:8096/Items/2cce5c8b1ea2848a784fc0e5fdf29da0/Images/Primary/0?Format=original&Tag=a985e9d9a40c7dcdf2ecbe1bb278b5f7' to '1/171e3b43.jpg':
2022-04-05 20:36:40.112 T:3864    DEBUG <general>: Thread FileCache 3811558016 terminating
2022-04-05 20:36:40.113 T:3863    DEBUG <general>: Caching image 'http://x.x.x.x:8096/Items/35eb11f16f353fe90dbad8680a99d18d/Images/Primary/0?Format=original&Tag=961ddd7f7bcfeb1f9543dbfa02660f68' to '5/53e2c997.jpg':
2022-04-05 20:36:40.216 T:3776    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:36:40.223 T:3776    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:36:40.224 T:3776    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:36:40.224 T:3776    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:36:40.225 T:3776    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:36:40.229 T:3776     INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:124 405 Client Error: Method Not Allowed for url: http://{jellyfin-server}/Sessions/Playing/Stopped
2022-04-05 20:36:40.240 T:3862    DEBUG <general>: cached image 'special://masterprofile/Thumbnails/1/171e3b43.jpg' size 480x720
2022-04-05 20:36:40.250 T:3776    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'jellyfin_kodi.helper.exceptions.HTTPException'>
                                                   Error Contents: (405, HTTPError('405 Client Error: Method Not Allowed for url: http://x.x.x.x:8096/Sessions/Playing/Stopped'))
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/http.py", line 96, in request
                                                       r.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://x.x.x.x:8096/Sessions/Playing/Stopped
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/player.py", line 383, in onPlayBackEnded
                                                       self.stop_playback()
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/player.py", line 412, in stop_playback
                                                       item['Server'].jellyfin.session_stop(data)
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 324, in session_stop
                                                       return self.sessions("/Playing/Stopped", "POST", json=data)
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 80, in sessions
                                                       return self._post("Sessions%s" % handler, json, params)
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 64, in _post
                                                       return self._http("POST", handler, {'params': params, 'json': json})
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 58, in _http
                                                       return self.client.request(request)
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/http.py", line 159, in request
                                                       raise HTTPException(r.status_code, error)
                                                   jellyfin_kodi.helper.exceptions.HTTPException: (405, HTTPError('405 Client Error: Method Not Allowed for url: http://x.x.x.x:8096/Sessions/Playing/Stopped'))
                                                   -->End of Python script error report<--

The below log entries also occur multiple times:
2022-04-05 20:37:01.590 T:3779     INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.ws_client -> ERROR::jellyfin_kodi/jellyfin/ws_client.py:71 [Errno 104] Connection reset by peer
2022-04-05 20:37:06.601 T:3779    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:37:06.604 T:3779    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:37:06.604 T:3779    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:37:06.604 T:3779    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:37:06.604 T:3779    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:37:06.605 T:3779     INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.ws_client -> INFO::jellyfin_kodi/jellyfin/ws_client.py:74 --->[ websocket ]
2022-04-05 20:37:07.018 T:3779    DEBUG <CAddonSettings[plugin.video.jellyfin]>: trying to load setting definitions from old format...
2022-04-05 20:37:07.022 T:3779    DEBUG <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2022-04-05 20:37:07.022 T:3779    DEBUG <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2022-04-05 20:37:07.023 T:3779    DEBUG <CSettingsManager>: requested setting (groupedSets) was not found.
2022-04-05 20:37:07.023 T:3779    DEBUG <CSettingsManager>: requested setting (platformDetected) was not found.
2022-04-05 20:37:07.554 T:3656    DEBUG <general>: SECTION:UnloadDelayed(DLL: libamcodec.so)

**Screenshots**

**System (please complete the following information):**
 - OS: Coreelec 19.4 Matrix
 - Jellyfin Version: 10.7.7
 - Kodi Version: 19.4
 - Addon Version: kodi0.7.7+py3
 - Playback Mode: Both

**Additional context**

**Comment by mcarlton00** [comment]
I don't think this is an addon problem, specifically because of the first line in your logs.

```
`2022-04-05 20:36:36.845 T:3808    ERROR <general>: Process - <nfs://x.x.x.x/volume1/media/movies/K****S (2022)/K****S - --1080p--1080p.mkv> source read failed with -4!
```

The addon doesn't handle network communication during playback at all.  We simply pass Kodi a URL and let it do it's thing.  _Especially_ since this is native mode, we have basically nothing to do with playback and only handle playback reporting.  You're definitely hitting an error in Kodi of some kind, but I suspect there's going to be nothing much we can do for you.

What's more confusing is that the logs are indicating that a post isn't allowed when updating the server about play status, which is absolutely false as a post is the only way to interact with that endpoint.  I suspect it's a red herring for something else causing issues, but I can't say for certain what's happening here.

**Comment by roc16** [comment]
Hi @mcarlton00 thanks for your response. I was hoping you would see some easy fix 😃. The only weird thing is that on dashboard, looking at the activity feed, even without playing a file the Jellyfin server would lose connection with the client every few min. 

However as you mentioned, this could also be caused by some other issue specific to coreelec 19.4 and my home setup (all other clients work ok). 

I'll play around a bit more and do some research. If still an issue I'll raise it on the coreelec forums. Feel free to close this issue. 

Thanks for your help and for such an awesome product you guys spend your free time on. Well done and very much appreciated.

**Comment by mcarlton00** [comment]
I don't think you're losing connection.  Just because it's not showing up in the active devices doesn't mean it's disappeared from the server.  If I'm not actively using a device, it doesn't show up in active devices.  At this moment I know for a fact that I have 2 Kodi devices and 2 Mopidy devices hooked to my server.  My active devices only show one Mopidy instance and the web session I'm using to see it.  Those other clients are still connected and available, they're just not doing anything right now.  A better check would be if you can see the client from the "play to" menu in the top right.  If yes, you have no connection problems.  If no, you have a network error that's causing the websocket connection to drop.  But that's not required for playback, so it's not the cause of your issue.

**Comment by roc16** [comment]
Great info and makes more sense now. Thanks @mcarlton00 👍
