### ISSUE TITLE
Multiple errors: "name 'ValueError' is not defined"

### ISSUE THREAD

**Issue by dakush** [jellyfin/jellyfin-kodi#643]
**Describe the bug**
Going through my kodi log I see multiple errors like this:
```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'NameError'>
Error Contents: name 'ValueError' is not defined
Traceback (most recent call last):
File "/home/dakush/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 139, in onNotification self.player.report_playback(data.get('Report', True))
File "/home/dakush/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/player.py", line 369, in report_playback item['Server'].jellyfin.session_progress(data)
File "/home/dakush/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 321, in session_progress return self.sessions("/Playing/Progress", "POST", json=data)
File "/home/dakush/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 80, in sessions return self._post("Sessions%s" % handler, json, params)
File "/home/dakush/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 64, in _post return self._http("POST", handler, {'params': params, 'json': json})
File "/home/dakush/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 58, in _http return self.client.request(request)
File "/home/dakush/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/http.py", line 169, in request response = r.json()
File "/home/dakush/.kodi/addons/script.module.requests/lib/requests/models.py", line 900, in json return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads return _default_decoder.decode(s)
File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode obj, end = self.raw_decode(s)
File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode return self.scan_once(s, idx=_w(s, idx).end())
File "/usr/lib/python3/dist-packages/simplejson/errors.py", line 41, in __init__ ValueError.__init__(self, errmsg(msg, doc, pos, end=end))
NameError: name 'ValueError' is not defined
-->End of Python script error report<--
```
Overall the system seems to work OK, the only problem I notice is that the dialog to delete media after watching doesn't show (I DO have that option enabled in the plugin settings).

**To Reproduce**
This happens everytime I use Kodi with the Jellyfin plugin, and the error shows multiple times in a session

**Expected behavior**
No errors in the log, and getting the delete media dialog to show after watching a movie/episode.

**Logs**
[https://controlc.com/5699fc49](https://controlc.com/5699fc49)

**System (please complete the following information):**
 - OS: Linux / Ubuntu 20.04
 - Jellyfin Version: 10.7.7.0
 - Kodi Version: 19.4
 - Addon Version: 0.7.7
 - Playback Mode: Add-on

**Comment by oddstr13** [comment]
That is probably indeed an error with the media deletion feature then.

That particular feature is unmaintained, as none of the devs wish to enable that feature, even for testing.

If this is an inconvenience to you, I really do apologize, but that particular feature will never be a priority for me personally.

Maybe one day, when I feel like working on jf4kodi, but there is nothing else to do, I may get around to setting up a test server with dummy media, with which I'm comfortable enabling and debugging that feature.

In the mean while, I'd highly recommend managing media deletion the old fashioned way, with a file manager (or any other appropriate software for the task).

**Comment by dakush** [comment]
Thank you so much for your answer, and for explaining the situation to me. It's not a big inconvenient at all, like you well said I can still delete the old fashioned way. No worries. Thanks again.

**Comment by jessbo** [comment]
I _think_ it's due to how requests imports `simplejson` with `json` as a fallback.

You can test this by editing your requests addon.

`<kodi-path-here>/addons/script.module.requests/lib/requests/compat.py`

If you replace...

```
try:
    import simplejson as json
except ImportError:
    import json
```

...with just...

```
import json
```

...does the issue persist?

**Comment by dakush** [comment]
The issue is gone! Thank you. Is that a know issue with requests or should I report it... somewhere?

Anyway, thanks again for your help!

**Comment by jessbo** [comment]
Modifying simplejson's error.py to include `from builtins import ValueError` seems to resolve all instances of this for me.  Byte compilation gone wrong somewhere?  Regardless, it's definitely something upstream.

**Comment by bossanova808** [comment]
@oddstr13 I believe this is the issue you were referring to (https://github.com/jellyfin/jellyfin-kodi/issues/912#issuecomment-3393301987) - that you will perhaps re-open? 

Can confirm this error still happens on, at least, CoreELEC kodi installs, frequently during most (all?) playbacks, as far as I can see.  As discussed it looks like an upstream packaging error, but one that should be patched around, as I suspect this is at least a contributing factor to several issues to do with playback reporting/resuming and Kodi <> JF communication.
