### ISSUE TITLE
Next Episode - Playback not working with Native Playback mode

### ISSUE THREAD

**Issue by sonicnkt** [jellyfin/jellyfin-kodi#677]
**Describe the bug**
Using the "Next Episode" feature is not working with native playback mode for me.
If i try to play an episode this way i get a playback failed error in kodi (See log Below).
Other Library features like "In Progress Movies" work fine tho.

Im using native mode because my device has only 100MBit Network and i want to keep the network overhead as low as possible for highbitrate 4k Content. The shares are mounted using nfs/fstab.

**To Reproduce**
1. Setup Native Playback
2. Open Addon and browse to your TV Library -> Next Episodes
3. Try to playback an episode
4. Playback Error

**Expected behavior**
Episdoe should play back fine.

**Logs**
``` 
2022-09-10 11:36:47.625 T:2920    DEBUG <general>: CLibInputKeyboard::ProcessKey - using delay: 500ms repeat: 33ms
2022-09-10 11:36:47.625 T:4927    DEBUG <general>: Thread Timer start, auto delete: false
2022-09-10 11:36:47.641 T:2882    DEBUG <general>: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
2022-09-10 11:36:47.785 T:4927    DEBUG <general>: Thread Timer 3535794432 terminating
2022-09-10 11:36:47.808 T:2882    DEBUG <general>: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
2022-09-10 11:36:47.808 T:2882    DEBUG <general>: HandleKey: return (0xf00d) pressed, action is Select
2022-09-10 11:36:47.808 T:2882    DEBUG <general>: ------ Window Deinit (DialogVideoInfo.xml) ------
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerCoreFactory::GetPlayers()
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: system rules
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: matches rule: system rules
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: streams
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: dvd
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: discimage
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: nsv
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: radio
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
2022-09-10 11:36:47.830 T:2882    DEBUG <general>: CPlayerCoreFactory::GetPlayers: added 1 players
2022-09-10 11:36:47.833 T:2882    DEBUG <general>: Radio UECP (RDS) Processor - new CDVDRadioRDSData
2022-09-10 11:36:47.833 T:2882     INFO <general>: VideoPlayer::OpenFile: 
2022-09-10 11:36:47.834 T:4928    DEBUG <general>: Thread VideoPlayer start, auto delete: false
2022-09-10 11:36:47.834 T:2882    DEBUG <general>: OnPlayBackStarted: CApplication::OnPlayBackStarted
2022-09-10 11:36:47.835 T:4928     INFO <general>: Creating InputStream
2022-09-10 11:36:47.836 T:4928    DEBUG <general>: SECTION:LoadDLL(special://xbmcbin/system/players/VideoPlayer/libdvdnav-arm.so)
2022-09-10 11:36:47.836 T:4928    DEBUG <general>: Loading: /usr/lib/kodi/system/players/VideoPlayer/libdvdnav-arm.so
2022-09-10 11:36:47.838 T:4928     INFO <general>:   msg: libdvdnav: Using dvdnav version 6.0.0
                                                   
2022-09-10 11:36:47.839 T:4928     INFO <general>:   msg: libdvdread: Can't stat 
                                                   
2022-09-10 11:36:47.839 T:4928     INFO <general>:   msg: libdvdread: Could not open 
                                                   
2022-09-10 11:36:47.840 T:4928    DEBUG <general>: libdvdnav: vm: failed to open/read the DVD
                                                   
2022-09-10 11:36:47.840 T:4928    ERROR <general>: Error on dvdnav_open
2022-09-10 11:36:47.840 T:4928    ERROR <general>: CVideoPlayer::OpenInputStream - error opening []
2022-09-10 11:36:47.840 T:4928     INFO <general>: CVideoPlayer::OnExit()
2022-09-10 11:36:47.840 T:4928    DEBUG <general>: Thread VideoPlayer 3282538752 terminating
2022-09-10 11:36:47.842 T:4924    DEBUG <general>: Loading settings for 
2022-09-10 11:36:47.844 T:4929    DEBUG <general>: Thread JobWorker start, auto delete: true
2022-09-10 11:36:47.853 T:4924    DEBUG <general>: OnPlayBackStopped: CApplication::OnPlayBackStopped
2022-09-10 11:36:47.874 T:2882    DEBUG <general>: CVideoGUIInfo::InitCurrentItem()
2022-09-10 11:36:47.975 T:2882    DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2022-09-10 11:36:47.976 T:2882    DEBUG <general>: ------ Window Init (DialogConfirm.xml) ------
2022-09-10 11:36:47.977 T:2882     INFO <general>: CVideoPlayer::CloseFile()
2022-09-10 11:36:47.977 T:2882    DEBUG <general>: DeleteRenderer - deleting renderer
2022-09-10 11:36:47.977 T:2882    DEBUG <general>: LinuxRendererGLES: Cleaning up GLES resources
2022-09-10 11:36:47.977 T:2882     INFO <general>: VideoPlayer: waiting for threads to exit
2022-09-10 11:36:47.977 T:2882     INFO <general>: VideoPlayer: finished waiting
2022-09-10 11:36:47.979 T:2882    DEBUG <general>: Radio UECP (RDS) Processor - delete ~CDVDRadioRDSData
2022-09-10 11:36:47.979 T:2882    DEBUG <general>: CDirectoryProvider[library://video/jellyfintvshows3e840160b2d8a553d88213a62925f0fa/nextepisodes.xml/]: refreshing..
2022-09-10 11:36:47.982 T:4929    DEBUG <general>: StartScript - calling plugin Jellyfin('plugin://plugin.video.jellyfin/','22','?id=3e840160b2d8a553d88213a62925f0fa&mode=nextepisodes&limit=25','resume:false')
2022-09-10 11:36:47.983 T:4930    DEBUG <general>: Thread LanguageInvoker start, auto delete: false
2022-09-10 11:36:47.983 T:4930     INFO <general>: initializing python engine.
2022-09-10 11:36:47.984 T:4930    DEBUG <general>: CPythonInvoker(52, /home/osmc/.kodi/addons/plugin.video.jellyfin/default.py): start processing
2022-09-10 11:36:48.037 T:3010    ERROR <general>: EXCEPTION: XBMC is not playing any file
2022-09-10 11:36:48.038 T:2939    DEBUG <general>: Skipped 1 duplicate messages..
2022-09-10 11:36:48.038 T:2939    DEBUG <general>: [plugin.video.youtube] PlaybackMonitor active threads: ||
2022-09-10 11:36:48.160 T:3010     INFO <general>: JELLYFIN.jellyfin_kodi.objects.actions -> INFO::jellyfin_kodi/objects/actions.py:762  [ play ] kodi_id: 1505 media: episode
2022-09-10 11:36:48.267 T:3010    ERROR <general>: EXCEPTION: XBMC is not playing any file
2022-09-10 11:36:48.293 T:3010     INFO <general>: JELLYFIN.jellyfin_kodi.objects.actions -> ERROR::jellyfin_kodi/objects/actions.py:778 XBMC is not playing any file
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/player.py", line 58, in onPlayBackStarted
                                                       current_file = self.getPlayingFile()
                                                   RuntimeError: XBMC is not playing any file
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/objects/actions.py", line 776, in on_play
                                                       file = player.getPlayingFile()
                                                   RuntimeError: XBMC is not playing any file
2022-09-10 11:36:48.314 T:3010     INFO <general>: JELLYFIN.jellyfin_kodi.player -> INFO::jellyfin_kodi/player.py:377 --<[ playback ]
2022-09-10 11:36:48.320 T:4930    DEBUG <general>: -->Python Interpreter Initialized<--                                                   
2022-09-10 11:36:48.320 T:4930    DEBUG <general>: CPythonInvoker(52, /home/osmc/.kodi/addons/plugin.video.jellyfin/default.py): the source file to load is "/home/osmc/.kodi/addons/plugin.video.jellyfin/default.py"
2022-09-10 11:36:48.320 T:4930    DEBUG <general>: CPythonInvoker(52, /home/osmc/.kodi/addons/plugin.video.jellyfin/default.py): setting the Python path to /home/osmc/.kodi/addons/plugin.video.jellyfin:/home/osmc/.kodi/addons/script.module.addon.signals/lib:/home/osmc/.kodi/addons/script.module.certifi/lib:/home/osmc/.kodi/addons/script.module.chardet/lib:/home/osmc/.kodi/addons/script.module.dateutil/lib:/home/osmc/.kodi/addons/script.module.idna/lib:/home/osmc/.kodi/addons/script.module.kodi-six/libs:/home/osmc/.kodi/addons/script.module.requests/lib:/home/osmc/.kodi/addons/script.module.six/lib:/home/osmc/.kodi/addons/script.module.urllib3/lib:/home/osmc/.kodi/addons/script.module.websocket/lib:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages
2022-09-10 11:36:48.321 T:4930    DEBUG <general>: CPythonInvoker(52, /home/osmc/.kodi/addons/plugin.video.jellyfin/default.py): entering source directory /home/osmc/.kodi/addons/plugin.video.jellyfin
2022-09-10 11:36:48.321 T:4930    DEBUG <general>: CPythonInvoker(52, /home/osmc/.kodi/addons/plugin.video.jellyfin/default.py): instantiating addon using automatically obtained id of "plugin.video.jellyfin" dependent on version 3.0.0 of the xbmc.python api
2022-09-10 11:36:49.072 T:3010    ERROR <general>: EXCEPTION: XBMC is not playing any file
2022-09-10 11:36:52.037 T:4930     INFO <general>: JELLYFIN -> INFO::jellyfin_kodi/jellyfin/__init__.py:98 ---[ START JELLYFINCLIENT ]---
2022-09-10 11:36:52.050 T:4930     INFO <general>: JELLYFIN.jellyfin_kodi.entrypoint.default -> INFO::jellyfin_kodi/entrypoint/default.py:72 path: ?id=3e840160b2d8a553d88213a62925f0fa&mode=nextepisodes&limit=25 params: {
                                                       "id": "3e840160b2d8a553d88213a62925f0fa",
                                                       "mode": "nextepisodes",
                                                       "limit": "25"
                                                   } 
``` 

**System (please complete the following information):**
 - OS: Linux (OSMC)
 - Jellyfin Version: 10.8.4
 - Kodi Version: 19.4
 - Addon Version: 0.7.8+py3
 - Playback Mode: Native

**Comment by oddstr13** [comment]
you should enable debug settings in the plugin settings for more verbose logs.

How much of a difference is the network overhead? I can't imagine HTTP adding much overhead over nfs, if any.

**Comment by sonicnkt** [comment]
I have to admit that i never really tested this before going "native". 
When i first got my Vero4K i read a lot of setup guides that advised of using NFS with fstab mount for the media files as SMB and especially mounts using kodi itself could cause issues for larger bitrate files. I just kept this philosophy in mind when i setup kodi with jellyfin.... 

I have another kodi setup in the bedroom and even tho its not a Vero4K it using the same soc and also has only 100Mbit networking. I will switch to addon mode on this device and test a few of my larger files to see if it makes a difference.

But i will also enable debugging in the addon to get more detailed logs later.

**Comment by sonicnkt** [comment]
Hmm does not seem to be much more info with plugin logging set to "debug" but here it is:
```
2022-09-12 15:33:26.370 T:2879     INFO <general>: VideoPlayer::OpenFile: 
2022-09-12 15:33:26.372 T:4253     INFO <general>: Creating InputStream
2022-09-12 15:33:26.374 T:4253     INFO <general>:   msg: libdvdnav: Using dvdnav version 6.0.0
                                                   
2022-09-12 15:33:26.376 T:4253     INFO <general>:   msg: libdvdread: Can't stat 
                                                   
2022-09-12 15:33:26.379 T:4253     INFO <general>:   msg: libdvdread: Could not open 
                                                   
2022-09-12 15:33:26.379 T:4253    ERROR <general>: Error on dvdnav_open
2022-09-12 15:33:26.380 T:4253    ERROR <general>: CVideoPlayer::OpenInputStream - error opening []
2022-09-12 15:33:26.380 T:4253     INFO <general>: CVideoPlayer::OnExit()
2022-09-12 15:33:26.499 T:2993    ERROR <general>: EXCEPTION: XBMC is not playing any file
2022-09-12 15:33:26.514 T:2879     INFO <general>: Skipped 1 duplicate messages..
2022-09-12 15:33:26.514 T:2879     INFO <general>: CVideoPlayer::CloseFile()
2022-09-12 15:33:26.514 T:2879     INFO <general>: VideoPlayer: waiting for threads to exit
2022-09-12 15:33:26.514 T:2879     INFO <general>: VideoPlayer: finished waiting
2022-09-12 15:33:26.522 T:4256     INFO <general>: initializing python engine.
2022-09-12 15:33:26.609 T:2993     INFO <general>: JELLYFIN.jellyfin_kodi.monitor -> DEBUG::jellyfin_kodi/monitor.py:91 [ xbmc: Player.OnPlay ] {
                                                       "item": {
                                                           "id": 1505,
                                                           "type": "episode"
                                                       },
                                                       "player": {
                                                           "playerid": 1,
                                                           "speed": 1
                                                       }
                                                   }
2022-09-12 15:33:26.617 T:2993     INFO <general>: JELLYFIN.jellyfin_kodi.objects.actions -> INFO::jellyfin_kodi/objects/actions.py:762  [ play ] kodi_id: 1505 media: episode
2022-09-12 15:33:26.638 T:2993     INFO <general>: JELLYFIN.jellyfin_kodi.database -> DEBUG::jellyfin_kodi/database/__init__.py:60 --->[ database: jellyfin ] 3588662776
2022-09-12 15:33:26.656 T:2993     INFO <general>: JELLYFIN.jellyfin_kodi.database -> DEBUG::jellyfin_kodi/database/__init__.py:172 ---<[ database: jellyfin ] 3588662776
2022-09-12 15:33:26.658 T:2993    ERROR <general>: EXCEPTION: XBMC is not playing any file
2022-09-12 15:33:26.681 T:2993     INFO <general>: JELLYFIN.jellyfin_kodi.objects.actions -> ERROR::jellyfin_kodi/objects/actions.py:778 XBMC is not playing any file
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/player.py", line 58, in onPlayBackStarted
                                                       current_file = self.getPlayingFile()
                                                   RuntimeError: XBMC is not playing any file
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/objects/actions.py", line 776, in on_play
                                                       file = player.getPlayingFile()
                                                   RuntimeError: XBMC is not playing any file
                                                   
2022-09-12 15:33:26.689 T:2993     INFO <general>: JELLYFIN.jellyfin_kodi.helper.utils -> DEBUG::jellyfin_kodi/helper/utils.py:56 --[ window clear: jellyfin_play ]
2022-09-12 15:33:26.698 T:2993     INFO <general>: JELLYFIN.jellyfin_kodi.player -> INFO::jellyfin_kodi/player.py:377 --<[ playback ]
2022-09-12 15:33:27.525 T:2993    ERROR <general>: EXCEPTION: XBMC is not playing any file
2022-09-12 15:33:30.367 T:4256     INFO <general>: Skipped 2 duplicate messages..
2022-09-12 15:33:30.367 T:4256     INFO <general>: JELLYFIN.__main__ -> DEBUG::default.py:18 --->[ default ]
2022-09-12 15:33:30.376 T:4256     INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.client -> DEBUG::jellyfin_kodi/jellyfin/client.py:35 JellyfinClient initializing...
2022-09-12 15:33:30.384 T:4256     INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.configuration -> DEBUG::jellyfin_kodi/jellyfin/configuration.py:25 Configuration initializing...
2022-09-12 15:33:30.394 T:4256     INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.configuration -> DEBUG::jellyfin_kodi/jellyfin/configuration.py:50 Begin http constructor.
2022-09-12 15:33:30.403 T:4256     INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.ws_client -> DEBUG::jellyfin_kodi/jellyfin/ws_client.py:34 WSClient initializing...
2022-09-12 15:33:30.413 T:4256     INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.connection_manager -> DEBUG::jellyfin_kodi/jellyfin/connection_manager.py:39 ConnectionManager initializing...
2022-09-12 15:33:30.422 T:4256     INFO <general>: JELLYFIN.jellyfin_kodi.jellyfin.credentials -> DEBUG::jellyfin_kodi/jellyfin/credentials.py:23 Credentials initializing...
2022-09-12 15:33:30.431 T:4256     INFO <general>: JELLYFIN -> INFO::jellyfin_kodi/jellyfin/__init__.py:98 ---[ START JELLYFINCLIENT ]---
2022-09-12 15:33:30.444 T:4256     INFO <general>: JELLYFIN.jellyfin_kodi.entrypoint.default -> INFO::jellyfin_kodi/entrypoint/default.py:72 path: ?id=3e840160b2d8a553d88213a62925f0fa&mode=nextepisodes&limit=25 params: {
                                                       "id": "3e840160b2d8a553d88213a62925f0fa",
                                                       "mode": "nextepisodes",
                                                       "limit": "25"
                                                   }
2022-09-12 15:33:30.455 T:4256     INFO <general>: JELLYFIN.jellyfin_kodi.database -> DEBUG::jellyfin_kodi/database/__init__.py:60 --->[ database: jellyfin ] 3481936040
2022-09-12 15:33:30.465 T:4256     INFO <general>: JELLYFIN.jellyfin_kodi.database -> DEBUG::jellyfin_kodi/database/__init__.py:172 ---<[ database: jellyfin ] 3481936040
2022-09-12 15:33:30.540 T:2993    ERROR <general>: EXCEPTION: XBMC is not playing any file
2022-09-12 15:33:30.818 T:4256     INFO <general>: JELLYFIN.__main__ -> INFO::default.py:25 ---<[ default ]
2022-09-12 15:33:30.819 T:4256     INFO <general>: CPythonInvoker(36, /home/osmc/.kodi/addons/plugin.video.jellyfin/default.py): script successfully run
2022-09-12 15:33:31.032 T:4256     INFO <general>: Python interpreter stopped
2022-09-12 15:33:31.549 T:2993     INFO <general>: JELLYFIN.jellyfin_kodi.player -> INFO::jellyfin_kodi/player.py:72 Cancel playback report

```
For more content, this is in the "next episodes" menu, selecting "play" on an episode.

I also have to add that i tried this on another Mediplayer with the same Version of Kodi and Addon but this device is NOT using native playback and i have the samme issue with the "Next Episodes" Feature.

**Comment by sonicnkt** [comment]
Okay getting closer :)

This seems to be related to Kodi's "Default select action" setting in Library/Videos. 
The default is `Play` but on all of my devices it is set to `Show information` and this breaks the "Next Episode" Feature in the Addon.

**Comment by sonicnkt** [comment]
I updated the orignal post and issue name as its not related to the playback mode (native / addon ) but relates to a default kodi setting.

**Comment by mcarlton00** [comment]
It has nothing to do with the default action setting.  It fails even when default action is set to play and you choose "show info" from the context menu.  Kodi appears to have changed something in the last 18 months (since I fixed this last year in #484) and it's now completely failing before it's even reaching the entrypoint of the addon.
