### ISSUE TITLE
add 2nd Server

### ISSUE THREAD

**Issue by Serph91P** [jellyfin/jellyfin-kodi#740]
**Describe the bug**
When you add a 2nd server the login mask is not showing up

**To Reproduce**
add 2nd server
try to login
nothing happens

**Expected behavior**
login appears and you can login

**Logs**
`                                                   Traceback (most recent call last):
                                                     File "default.py", line 21, in <module>
                                                       Events()
                                                     File "jellyfin_kodi/entrypoint/default.py", line 56, in __init__
                                                       jellyfin_client = Jellyfin(server).get_client()
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "jellyfin_kodi/jellyfin/__init__.py", line 56, in get_client
                                                       return self.client[self.server_id]
                                                              ~~~~~~~~~~~^^^^^^^^^^^^^^^^
                                                   KeyError: '0dd3b9674e81461fa43d5181ccb49ab5'`



**System (please complete the following information):**
 - OS: Linux
 - Jellyfin Version: 10.8.10
 - Kodi Version: 20.1
 - Addon Version: 0.7.10
 - Playback Mode: Addon

**Comment by Serph91P** [comment]
Found related Issue: https://github.com/jellyfin/jellyfin-kodi/issues/562
