### ISSUE TITLE
Jellyfin libraries sync manually but not automatically

### ISSUE THREAD

**Issue by vzografos** [jellyfin/jellyfin-kodi#800]
**Describe the bug**

Jellyfin library does not automatically update.  Only manual sync possible

**To Reproduce**

1. Go to 'Add ons'
2. Click on 'Jellyfin'
3. Scroll down to 'Update Libraries'
4. choose All
5.  Press OK
6.  Popup appears on upper right and libraries are synced after a few seconds

**Expected behavior**

I expect that the Jellyfin addon for Kodi updates the libraries automatically either periodically or when something is added in jellyfin

**Logs**
```

2023-12-21 23:15:33.587 T:16485    info <general>: JELLYFIN.jellyfin_kodi.helper.playutils -> ERROR::jellyfin_kodi/helper/playutils.py:550 HTTPConnectionPool(host='192.168.1.27', port=8096): Max retries exceeded with url: /Videos/4b6de>
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 203, in _new_conn
                                                       sock = connection.create_connection(
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 85, in create_connection
                                                       raise err
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 73, in create_connection
                                                       sock.connect(sa)
                                                   ConnectionRefusedError: [Errno 111] Connection refused

                                                   The above exception was the direct cause of the following exception:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 790, in urlopen
                                                       response = self._make_request(
                                                                  ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 496, in _make_request
                                                       conn.request(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 395, in request
                                                       self.endheaders()
                                                     File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
                                                     File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
                                                     File "/usr/lib/python3.11/http/client.py", line 975, in send
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 243, in connect
                                                       self.sock = self._new_conn()
                                                                   ^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 218, in _new_conn
                                                       raise NewConnectionError(
                                                   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc21126dc10>: Failed to establish a new connection: [Errno 111] Connection refused

                                                   The above exception was the direct cause of the following exception:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 486, in send
                                                       resp = conn.urlopen(
                                                              ^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 844, in urlopen
                                                       retries = retries.increment(
                                                                 ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 515, in increment
                                                       raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.27', port=8096): Max retries exceeded with url: /Videos/4b6de3e3-c4ba-3078-1621-11e3c33a15a6/4b6de3e3c4ba3078162111>

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/helper/playutils.py", line 548, in set_external_subs
                                                       subs.append(self.download_external_subs(url, filename))
        
                                                   File "jellyfin_kodi/helper/playutils.py", line 575, in download_external_subs
                                                       response = requests.get(src, stream=True, verify=settings('sslverify.bool'))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 73, in get
                                                       return request("get", url, params=params, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 59, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 589, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 703, in send
                                                       r = adapter.send(request, **kwargs)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 519, in send
                                                       raise ConnectionError(e, request=request)
                                                   requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.27', port=8096): Max retries exceeded with url: /Videos/4b6de3e3-c4ba-3078-1621-11e3c33a15a6/4b6de3e3c4ba3078162>



```

**Screenshots**

**System (please complete the following information):**
 - OS:  LibreELEC 11.0.3  (Generic-legacy.x86_64)
 - Jellyfin Version:  10.8.12
 - Kodi Version: [e.g. 18.3]
 - Addon Version: [e.g. 0.2.1]
 - Playback Mode: Add-On 

**Additional context**
Kodi sync Queue 9.0.0.0 is installed on Jellyfin server

**Comment by oddstr13** [comment]
The provided logs indicate that the server is unreachable.

Nothing actionable for this addon as far as I can tell, closing this as a configuration/networking issue.

Feel free to comment with additional information or create a new issue if you have more information indicating that this is an issue with the addon code.
