### ISSUE TITLE
Content update error on kodi start

### ISSUE THREAD

**Issue by bradgy** [jellyfin/jellyfin-kodi#825]
**Describe the bug**
Error message on starting kodi saying that new content will not be added until next restart, and if the issue continues to please make a new issue here :)

**To Reproduce**

1. Start Kodi
2. See error
3. See existing JF content, but no new updates

**Expected behavior**
Regular updated content as in previous cases.

**Logs**
[kodi.log](https://github.com/jellyfin/jellyfin-kodi/files/14371161/kodi.log)

**Screenshots**
![Screenshot from 2024-02-22 19-38-11](https://github.com/jellyfin/jellyfin-kodi/assets/5727821/4175b9d5-39c9-40cf-93d3-8deb3b16d798)

**System (please complete the following information):**
 - OS: arch linux w latest updates (sorry)
 - Jellyfin Version: 10.9.0
 - Kodi Version: 20.4
 - Addon Version: 0.7.12+py3
 - Playback Mode: Native

**Additional context**
NA

**Comment by mcarlton00** [comment]
Do you have the kodi sync queue installed in the server?  From a quick scroll through the logs you're getting a 404 when trying to query for music videos.

```
2024-02-22 19:40:27.504 T:232033    info <general>: JELLYFIN.jellyfin_kodi.library -> ERROR::jellyfin_kodi/library.py:438 (404, HTTPError('404 Client Error: Not Found for url: http://{jellyfin-server}/Jellyfin.Plugin.KodiSyncQueue/5a5f7e208219469aaceb43cb6bcc160b/GetItems?LastUpdateDT=2024-02-11T11%3A36%3A01z&filter=musicvideos'))
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/jellyfin/http.py", line 96, in request
                                                       r.raise_for_status()
                                                     File "/home/brad/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://{jellyfin-server}/Jellyfin.Plugin.KodiSyncQueue/5a5f7e208219469aaceb43cb6bcc160b/GetItems?LastUpdateDT=2024-02-11T11%3A36%3A01z&filter=musicvideos

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/library.py", line 408, in fast_sync
                                                       result = self.server.jellyfin.get_sync_queue(last_sync, ",".join([x for x in query_filter]))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "jellyfin_kodi/jellyfin/api.py", line 354, in get_sync_queue
                                                       return self._get("Jellyfin.Plugin.KodiSyncQueue/{UserId}/GetItems", params={
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "jellyfin_kodi/jellyfin/api.py", line 61, in _get
                                                       return self._http("GET", handler, {'params': params})
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "jellyfin_kodi/jellyfin/api.py", line 58, in _http
                                                       return self.client.request(request)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "jellyfin_kodi/jellyfin/http.py", line 159, in request
                                                       raise HTTPException(r.status_code, error)
                                                   jellyfin_kodi.helper.exceptions.HTTPException: (404, HTTPError('404 Client Error: Not Found for url: http://{jellyfin-server}/Jellyfin.Plugin.KodiSyncQueue/5a5f7e208219469aaceb43cb6bcc160b/GetItems?LastUpdateDT=2024-02-11T11%3A36%3A01z&filter=musicvideos'))
```

**Comment by mcarlton00** [comment]
Plugins are generally not compatible with unstable, so that's to be expected.  And unfortunately without that the startup sync won't work properly.
