### ISSUE TITLE
Can not start the plugin after the installation, shows error and check the log

### ISSUE THREAD

**Issue by werran2** [jellyfin/jellyfin-kodi#833]
**Describe the bug**
Can not start the plugin after the installation, shows error and check the log, I tried to reinstall kodi clearly but still same problem
And all others are good as I installed this plugin in my TV and a tv box works fine.

PS: I am using a nas qnap 464 and it works as I checked a youtuber is using the same nas and kodi version works fine with jellyfin plugin.

PLS help ;(

**To Reproduce**

**Expected behavior**

**Logs**
```
2024-03-06 23:11:40.120 T:3517    error <general>: Control 54 in window 10025 has been asked to focus, but it can't
2024-03-06 23:11:42.352 T:7208    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: future feature annotations is not defined (__init__.py, line 5)
                                                   Traceback (most recent call last):
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/default.py", line 6, in <module>
                                                       from jellyfin_kodi.entrypoint.default import Events
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/__init__.py", line 7, in <module>
                                                       from ..jellyfin import Jellyfin
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/__init__.py", line 8, in <module>
                                                       from .client import JellyfinClient
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/client.py", line 8, in <module>
                                                       from . import api
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 6, in <module>
                                                       import requests
                                                     File "/opt/Kodi20/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                       import urllib3
                                                     File "/opt/Kodi20/.kodi/addons/script.module.urllib3/lib/urllib3/__init__.py", line 5
                                                       from __future__ import annotations
                                                                                        ^
                                                   SyntaxError: future feature annotations is not defined
                                                   -->End of Python script error report<--
                                                   
2024-03-06 23:11:42.361 T:3993     info <general>: CActiveAESink::OpenSink - initialize sink
2024-03-06 23:11:42.362 T:3993     info <general>: CAESinkALSA::Initialize - Attempting to open device "default"
2024-03-06 23:11:42.389 T:7207    error <general>: GetDirectory - Error getting plugin://plugin.video.jellyfin/
2024-03-06 23:11:42.399 T:3517    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellyfin/) failed
2024-03-06 23:11:42.463 T:3993     info <general>: CAESinkALSA::Initialize - Opened device "default"
2024-03-06 23:11:48.341 T:7216    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: future feature annotations is not defined (__init__.py, line 5)
                                                   Traceback (most recent call last):
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/default.py", line 6, in <module>
                                                       from jellyfin_kodi.entrypoint.default import Events
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/__init__.py", line 7, in <module>
                                                       from ..jellyfin import Jellyfin
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/__init__.py", line 8, in <module>
                                                       from .client import JellyfinClient
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/client.py", line 8, in <module>
                                                       from . import api
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 6, in <module>
                                                       import requests
                                                     File "/opt/Kodi20/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                       import urllib3
                                                     File "/opt/Kodi20/.kodi/addons/script.module.urllib3/lib/urllib3/__init__.py", line 5
                                                       from __future__ import annotations
                                                                                        ^
                                                   SyntaxError: future feature annotations is not defined
                                                   -->End of Python script error report<--
                                                   
2024-03-06 23:11:48.377 T:7215    error <general>: GetDirectory - Error getting plugin://plugin.video.jellyfin/?content_type=video
2024-03-06 23:11:48.378 T:3517    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellyfin/?content_type=video) failed
2024-03-06 23:11:49.944 T:7221    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: future feature annotations is not defined (__init__.py, line 5)
                                                   Traceback (most recent call last):
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/default.py", line 6, in <module>
                                                       from jellyfin_kodi.entrypoint.default import Events
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/__init__.py", line 7, in <module>
                                                       from ..jellyfin import Jellyfin
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/__init__.py", line 8, in <module>
                                                       from .client import JellyfinClient
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/client.py", line 8, in <module>
                                                       from . import api
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 6, in <module>
                                                       import requests
                                                     File "/opt/Kodi20/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                       import urllib3
                                                     File "/opt/Kodi20/.kodi/addons/script.module.urllib3/lib/urllib3/__init__.py", line 5
                                                       from __future__ import annotations
                                                                                        ^
                                                   SyntaxError: future feature annotations is not defined
                                                   -->End of Python script error report<--
                                                   
2024-03-06 23:11:49.982 T:7220    error <general>: GetDirectory - Error getting plugin://plugin.video.jellyfin/?content_type=video
2024-03-06 23:11:49.994 T:3517    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellyfin/?content_type=video) failed
2024-03-06 23:11:51.621 T:7226    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: future feature annotations is not defined (__init__.py, line 5)
                                                   Traceback (most recent call last):
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/default.py", line 6, in <module>
                                                       from jellyfin_kodi.entrypoint.default import Events
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/__init__.py", line 7, in <module>
                                                       from ..jellyfin import Jellyfin
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/__init__.py", line 8, in <module>
                                                       from .client import JellyfinClient
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/client.py", line 8, in <module>
                                                       from . import api
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 6, in <module>
                                                       import requests
                                                     File "/opt/Kodi20/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                       import urllib3
                                                     File "/opt/Kodi20/.kodi/addons/script.module.urllib3/lib/urllib3/__init__.py", line 5
                                                       from __future__ import annotations
                                                                                        ^
                                                   SyntaxError: future feature annotations is not defined
                                                   -->End of Python script error report<--
                                                   
2024-03-06 23:11:51.668 T:7225    error <general>: GetDirectory - Error getting plugin://plugin.video.jellyfin/?content_type=video
2024-03-06 23:11:51.677 T:3517    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellyfin/?content_type=video) failed
2024-03-06 23:11:52.735 T:7231    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: future feature annotations is not defined (__init__.py, line 5)
                                                   Traceback (most recent call last):
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/default.py", line 6, in <module>
                                                       from jellyfin_kodi.entrypoint.default import Events
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/__init__.py", line 7, in <module>
                                                       from ..jellyfin import Jellyfin
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/__init__.py", line 8, in <module>
                                                       from .client import JellyfinClient
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/client.py", line 8, in <module>
                                                       from . import api
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 6, in <module>
                                                       import requests
                                                     File "/opt/Kodi20/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                       import urllib3
                                                     File "/opt/Kodi20/.kodi/addons/script.module.urllib3/lib/urllib3/__init__.py", line 5
                                                       from __future__ import annotations
                                                                                        ^
                                                   SyntaxError: future feature annotations is not defined
                                                   -->End of Python script error report<--
                                                   
2024-03-06 23:11:52.781 T:7230    error <general>: GetDirectory - Error getting plugin://plugin.video.jellyfin/?content_type=video
2024-03-06 23:11:52.794 T:3517    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellyfin/?content_type=video) failed
```

**Screenshots**

**System (please complete the following information):**
 - OS: qnap nas
 - Jellyfin Version: latest
 - Kodi Version: 20.2
 - Addon Version: 0.7.12
 - Playback Mode:Add-On

**Additional context**

**Comment by HaoLiMRI** [comment]
I have the same issue. It seems to be the wrong python version, because "from future import annotations" works on the versions after 3.7, and the default python version of qnap nas is 2.7. I installed python3, but don't know how to make kodi and the addon work on python3...

**Comment by mcarlton00** [comment]
If you're running Kodi 20, you're already running python3.  Python3 is a requirement since Kodi 19.  Now it's possible that qnap has a version of python3 that's older than 3.7, but in this case I'm not sure what options you have.  As far as I'm aware, it's not possible to change what python version Kodi is using.

**Comment by HaoLiMRI** [comment]
Thanks a lot for your response. 
I just found a similar issue of the wrong python version with another plugin: https://github.com/CastagnaIT/plugin.video.netflix/issues/1262
Maybe the solution to this issue could help.

**Comment by oddstr13** [comment]
The only appropriate fix for this issue is to install a modern Python version, upstream *security* support for py3.7 ended in june last year, and py3.6 in december 2021.

Python 3.10 is available in the AppCenter on my QNAP, but Kodi is not.

Please forward this issue to whoever is providing the Kodi package you use.
