### ISSUE TITLE
Various Artists albums show up empty in Kodi

### ISSUE THREAD

**Issue by csaavedra** [jellyfin/jellyfin-kodi#837]
Many of my "Various Artists" albums in Jellyfin show correctly, with all their tracks, but in Kodi they show up empty. I use picard and musicbrainz metadata to tag the files before importing them in Jellyfin.

Some examples of albums that show up empty: 
https://musicbrainz.org/release/2b3067bd-79cc-4c41-b96b-c28b0a44e2dd
https://musicbrainz.org/release/2aefd156-4ac9-4550-b2b5-608ade009c8b

jellyfin-kodi: 0.7.12+py3 (in add-on mode).
Kodi: 20.3
Jellyfin: 10.8.13
Kodi sync queue: 9.0.0

**Comment by csaavedra** [comment]
Happy to provide any further info that might aid in debugging this.

**Comment by oddstr13** [comment]
I'm not seeing this in my own library, I've got five albums in my library with the album artist set to 89ad4ac3-39f7-470e-963a-56509c546377, but all show up as expected in Kodi.

Are you seeing any errors in the kodi logs when syncing these albums?

**Comment by csaavedra** [comment]
I think this might be related to https://github.com/jellyfin/jellyfin-kodi/issues/913 

In that bug the problem is that when a track artist is different from the album artist, it fails to import. There are logs there.

I have been thinking and I suspect the issue might be that when importing an album, the album artist is created in the artists database. But then if there are track artists that are different from the album artists, these are not found. That's what the error in the logs I pasted in that issue show.

I recently had to resync my whole library and now all albums are complete, but this issue was happening when adding new albums to jellyfin and later the synchronization for that album alone is triggered.

**Comment by kontell** [comment]
Music library syncing is working well for me with the exception of Various Artists. I find only a handful of tracks get imported to Kodi for each album.

A library repair does fix each album and all tracks will show correctly. I get one of the below errors for each missing track.

```
2025-05-18 14:41:30.250 T:1147995    info <general>: JELLYFIN.jellyfin_kodi.helper.utils -> ERROR::jellyfin_kodi/helper/utils.py:583 No ancestor found, not syncing item with ID: 852b12eedf3230f8d4865d9cc0b8145c
2025-05-18 14:41:30.252 T:1147995    info <general>: JELLYFIN.jellyfin_kodi.objects.music -> ERROR::jellyfin_kodi/objects/music.py:471 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/objects/music.py", line 460, in song_artist_link
                                                       temp_obj["ArtistId"] = self.jellyfin_db.get_item_by_id(
                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                           *values(temp_obj, QUEM.get_item_obj)
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       )[0]
                                                       ~^^^
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/objects/music.py", line 467, in song_artist_link
                                                       temp_obj["ArtistId"] = self.jellyfin_db.get_item_by_id(
                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                           *values(temp_obj, QUEM.get_item_obj)
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       )[0]
                                                       ~^^^
                                                   TypeError: 'NoneType' object is not subscriptable
```

[kodi.log](https://github.com/user-attachments/files/20273063/kodi.log)
