### ISSUE TITLE
Jellyfin crashed. "Could not apply migration 'MigrateActivityLogDatabase"

### ISSUE THREAD

**Issue by werran2** [jellyfin/jellyfin-kodi#846]
**Describe the bug**
After updated jellyfin-kodi to the latest, Jellyfin crashed.

**Logs**
[09:41:10] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'MigrateActivityLogDatabase'
CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnectionBuilder.Build()
   at Jellyfin.Server.Migrations.Routines.MigrateActivityLogDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)

[09:41:10] [FTL] [1] Main: Error while starting server.
CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnectionBuilder.Build()
   at Jellyfin.Server.Migrations.Routines.MigrateActivityLogDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)

[09:41:10] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[09:41:11] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[09:41:11] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[09:41:11] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing SchedulesDirect
[09:41:11] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing EmbyTV
[09:41:11] [INF] [2] Main: Received a SIGTERM signal, shutting down

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Android, Debian, Windows]
 - Jellyfin Version: [e.g. 10.0.1]
 - Kodi Version: [e.g. 18.3]
 - Addon Version: [e.g. 0.2.1]
 - Playback Mode: [e.g. Add-On or Native]

**Additional context**

**Comment by crobibero** [comment]
This looks like a permission issue, and has nothing to do with Kodi.
