### ISSUE TITLE
Consistent Sync Failure: List Index Out of Range in full_sync.py:291

### ISSUE THREAD

**Issue by valpamp** [jellyfin/jellyfin-kodi#890]
**Describe the bug**

**To Reproduce**

1. Reinstall latest Kodi Sync Queue version
2. Restart the Jellyfin Server
3. Reinstall Kodi
4. Install Jellyfin for Kodi
5. Successfully log into my account
6. Attempt full library sync
7. Fail

**Expected behavior**

The full library sync completes without errors.

**Logs**

The relevant portion of the log should be the following:
```
2024-07-16 15:21:59.815 T:24508    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.connection_manager -> INFO::jellyfin_kodi\jellyfin\connection_manager.py:182 Begin connect
2024-07-16 15:21:59.816 T:24508    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.connection_manager -> INFO::jellyfin_kodi\jellyfin\connection_manager.py:58 Begin getAvailableServers
2024-07-16 15:22:00.827 T:24508    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.connection_manager -> INFO::jellyfin_kodi\jellyfin\connection_manager.py:244 Found Servers: [{'Address': 'http://192.168.1.50:8096', 'Id': '66d307ce650648fc98268b3c219449f1', 'Name': 'odroidhc4', 'EndpointAddress': None}]
2024-07-16 15:22:00.837 T:24508    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.connection_manager -> INFO::jellyfin_kodi\jellyfin\connection_manager.py:185 connect has 1 servers
2024-07-16 15:22:00.842 T:24508    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.connection_manager -> INFO::jellyfin_kodi\jellyfin\connection_manager.py:156 begin connectToServer
2024-07-16 15:22:00.851 T:24508    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.api -> INFO::jellyfin_kodi\jellyfin\api.py:434 Sending get request to system/info/public
2024-07-16 15:22:01.091 T:24508    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.connection_manager -> INFO::jellyfin_kodi\jellyfin\connection_manager.py:165 calling onSuccessfulConnection with server odroidhc4
2024-07-16 15:22:01.099 T:24508    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.api -> INFO::jellyfin_kodi\jellyfin\api.py:434 Sending get request to system/info
2024-07-16 15:22:01.263 T:24508    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.client -> INFO::jellyfin_kodi\jellyfin\client.py:57 User is authenticated.
2024-07-16 15:22:01.412 T:12672    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.ws_client -> INFO::jellyfin_kodi\jellyfin\ws_client.py:60 Websocket url: ws://192.168.1.50:8096/socket?api_key=944a601dd41844df9ede5f8a7deb7fbf&device_id=b9b84226-e3e8-4292-a6f3-6b04bcaed52e
2024-07-16 15:22:01.446 T:12672    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.ws_client -> INFO::jellyfin_kodi\jellyfin\ws_client.py:80 --->[ websocket opened ]
2024-07-16 15:22:03.549 T:9252  warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2024-07-16 15:22:03.633 T:24508    info <general>: Skipped 4 duplicate messages..
2024-07-16 15:22:03.633 T:24508    info <general>: JELLYFIN.jellyfin_kodi.helper.utils -> INFO::jellyfin_kodi\helper\utils.py:486 Add-on playback: True
2024-07-16 15:22:03.800 T:4620     info <general>: JELLYFIN.jellyfin_kodi.library -> INFO::jellyfin_kodi\library.py:85 --->[ library ]
2024-07-16 15:22:03.817 T:5804     info <general>: VideoInfoScanner: Starting scan ..
2024-07-16 15:22:03.818 T:5804     info <general>: VideoInfoScanner: Finished scan. Scanning for video info took 1 ms
2024-07-16 15:22:03.834 T:24508    info <general>: JELLYFIN.jellyfin_kodi.monitor -> INFO::jellyfin_kodi\monitor.py:42 -->[ kodi scan/video ]
2024-07-16 15:22:03.836 T:24508    info <general>: JELLYFIN.jellyfin_kodi.monitor -> INFO::jellyfin_kodi\monitor.py:45 --<[ kodi scan/video ]
2024-07-16 15:22:04.009 T:4620     info <general>: JELLYFIN.jellyfin_kodi.database -> INFO::jellyfin_kodi\database\__init__.py:162 Database locked in: C:\Users\Home\AppData\Roaming\Kodi\userdata\Database\MyVideos131.db
2024-07-16 15:22:04.024 T:4620     info <general>: JELLYFIN.jellyfin_kodi.database -> INFO::jellyfin_kodi\database\__init__.py:162 Database locked in: C:\Users\Home\AppData\Roaming\Kodi\userdata\Database\MyMusic83.db
2024-07-16 15:22:04.051 T:4620     info <general>: JELLYFIN.jellyfin_kodi.objects.kodi.movies -> INFO::jellyfin_kodi\objects\kodi\movies.py:154 Starting migration for Omega database changes
2024-07-16 15:22:04.053 T:4620     info <general>: JELLYFIN.jellyfin_kodi.objects.kodi.movies -> INFO::jellyfin_kodi\objects\kodi\movies.py:164 Omega database migration is complete
2024-07-16 15:22:05.604 T:4620     info <general>: JELLYFIN.jellyfin_kodi.full_sync -> INFO::jellyfin_kodi\full_sync.py:53 -->[ fullsync ]
2024-07-16 15:22:05.609 T:4620     info <general>: JELLYFIN.jellyfin_kodi.full_sync -> INFO::jellyfin_kodi\full_sync.py:138 generate full sync
2024-07-16 15:22:05.617 T:9252     info <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
2024-07-16 15:22:08.333 T:9252  warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2024-07-16 15:22:08.469 T:4620     info <general>: JELLYFIN.jellyfin_kodi.full_sync -> INFO::jellyfin_kodi\full_sync.py:197 starting sync with ['Mixed:d929e7cec980548fcc4923e777dc019a', '3148cf0701708325a446ec1751b2b64e', '6362c8c966cc0fe60a1c97cc4bf95c31', '35557e21b52daa9c3a3901d3641fbe7f', '3598d0b4d08409b972479f7f00d3a284', '43a7fe7b1501aab96b15058b920fac93', 'a627c8c9009da1cd39f36ee4fc829a98', 'abebc196cc1b8bbf6f8bb5ca7b5ad6f1', '0c41907140d802bb58430fed7e2cd79e', 'c248dc0bec4b0ce8fb01231d1f12c5c1', 'c67be889cf1dbdd55d59c83a6cdbd50b', '74be02f1a93c3eea02b1877addca53ee', 'bef1adbdf71d0e70600017e97df2fdff', 'f137a2dd21bbc1b99aa5c0f6bf02a805', 'bdf38141c3a366eb1a2a8240d2e65e68', 'Boxsets:']
2024-07-16 15:22:08.502 T:4620     info <general>: JELLYFIN.jellyfin_kodi.helper.wrapper -> INFO::jellyfin_kodi\helper\wrapper.py:35 Processing Boxing: d929e7cec980548fcc4923e777dc019a
2024-07-16 15:22:08.701 T:4620     info <general>: Skipped 1 duplicate messages..
2024-07-16 15:22:08.701 T:4620     info <general>: JELLYFIN.jellyfin_kodi.helper.wrapper -> INFO::jellyfin_kodi\helper\wrapper.py:35 Processing TV Series: 3148cf0701708325a446ec1751b2b64e
2024-07-16 15:22:08.919 T:22424    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.http -> ERROR::jellyfin_kodi\jellyfin\http.py:131 500 Server Error: Internal Server Error for url: http://192.168.1.50:8096/Users/d5d16d4d9a7e45a08c4b8f4dbb18e282/Items?ParentId=3148cf0701708325a446ec1751b2b64e&IncludeItemTypes=Series&SortBy=SortName&SortOrder=Ascending&Fields=Path%2CGenres%2CSortName%2CStudios%2CWriter%2CTaglines%2CLocalTrailerCount%2COfficialRating%2CCumulativeRunTimeTicks%2CItemCounts%2CMetascore%2CAirTime%2CDateCreated%2CPeople%2COverview%2CEtag%2CShortOverview%2CProductionLocations%2CTags%2CProviderIds%2CParentId%2CRemoteTrailers%2CSpecialEpisodeNumbers%2CMediaSources%2CVoteCount%2CRecursiveItemCount%2CPrimaryImageAspectRatio&CollapseBoxSetItems=False&IsVirtualUnaired=False&EnableTotalRecordCount=False&LocationTypes=FileSystem%2CRemote%2COffline&IsMissing=False&Recursive=True&StartIndex=0&Limit=15
2024-07-16 15:22:08.922 T:22424    info <general>: JELLYFIN.jellyfin_kodi.jellyfin.http -> ERROR::jellyfin_kodi\jellyfin\http.py:160 --[ 500 response ] 500 Server Error: Internal Server Error for url: http://192.168.1.50:8096/Users/d5d16d4d9a7e45a08c4b8f4dbb18e282/Items?ParentId=3148cf0701708325a446ec1751b2b64e&IncludeItemTypes=Series&SortBy=SortName&SortOrder=Ascending&Fields=Path%2CGenres%2CSortName%2CStudios%2CWriter%2CTaglines%2CLocalTrailerCount%2COfficialRating%2CCumulativeRunTimeTicks%2CItemCounts%2CMetascore%2CAirTime%2CDateCreated%2CPeople%2COverview%2CEtag%2CShortOverview%2CProductionLocations%2CTags%2CProviderIds%2CParentId%2CRemoteTrailers%2CSpecialEpisodeNumbers%2CMediaSources%2CVoteCount%2CRecursiveItemCount%2CPrimaryImageAspectRatio&CollapseBoxSetItems=False&IsVirtualUnaired=False&EnableTotalRecordCount=False&LocationTypes=FileSystem%2CRemote%2COffline&IsMissing=False&Recursive=True&StartIndex=0&Limit=15
2024-07-16 15:22:09.133 T:9252     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-07-16 15:22:11.008 T:9252  warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2024-07-16 15:22:11.052 T:4620     info <general>: JELLYFIN.jellyfin_kodi.full_sync -> ERROR::jellyfin_kodi\full_sync.py:290 full sync exited unexpectedly
2024-07-16 15:22:11.057 T:4620     info <general>: JELLYFIN.jellyfin_kodi.full_sync -> ERROR::jellyfin_kodi\full_sync.py:291 list index out of range
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi\full_sync.py", line 276, in process_library
                                                       media[library["CollectionType"]](library)
                                                     File "jellyfin_kodi\helper\wrapper.py", line 43, in wrapper
                                                       result = func(self, dialog=dialog, *args, **kwargs)
                                                     File "jellyfin_kodi\full_sync.py", line 360, in tvshows
                                                       for items in server.get_items(
                                                     File "jellyfin_kodi\downloader.py", line 168, in get_items
                                                       for items in _get_items(query):
                                                     File "jellyfin_kodi\downloader.py", line 275, in _get_items
                                                       if result["Items"][0].get("ProductionYear"):
                                                   IndexError: list index out of range
                                                   
2024-07-16 15:22:11.064 T:4620     info <general>: JELLYFIN.jellyfin_kodi.full_sync -> INFO::jellyfin_kodi\full_sync.py:703 --<[ fullsync ]
2024-07-16 15:22:11.070 T:4620     info <general>: JELLYFIN.jellyfin_kodi.library -> ERROR::jellyfin_kodi\library.py:455 list index out of range
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi\library.py", line 417, in startup
                                                       sync.libraries()
                                                     File "jellyfin_kodi\full_sync.py", line 112, in libraries
                                                       self.start()
                                                     File "jellyfin_kodi\full_sync.py", line 203, in start
                                                       self.process_library(library)
                                                     File "jellyfin_kodi\full_sync.py", line 276, in process_library
                                                       media[library["CollectionType"]](library)
                                                     File "jellyfin_kodi\helper\wrapper.py", line 43, in wrapper
                                                       result = func(self, dialog=dialog, *args, **kwargs)
                                                     File "jellyfin_kodi\full_sync.py", line 360, in tvshows
                                                       for items in server.get_items(
                                                     File "jellyfin_kodi\downloader.py", line 168, in get_items
                                                       for items in _get_items(query):
                                                     File "jellyfin_kodi\downloader.py", line 275, in _get_items
                                                       if result["Items"][0].get("ProductionYear"):
                                                   IndexError: list index out of range
```

**Screenshots**

This is the error I invariably get.
![image](https://github.com/user-attachments/assets/a1a977eb-6eff-49ed-b6c3-6b3f312b33df)

**System (please complete the following information):**
- OS: Windows 10, Fire Stick and Fire Stick 4k
- Jellyfin Version: 10.9.7
- Kodi Version: 21.0
- Addon Version: 11.0.0.0
- Playback Mode: Add-On

**Additional context**

At some point, while troubleshooting, I found multiple versions of the plugin installed on my Jellyfin server, but I removed them all and reinstalled the latest. This had no effect. Should I try downgrading?

**Comment by oddstr13** [comment]
The server returned a 500 error, so I need the relevant section of the Jellyfin server log in order to determine whether this is a server or addon error.

**Comment by valpamp** [comment]
Here is the entire [kodi.log](https://github.com/user-attachments/files/16561808/kodi.log).

**Comment by oddstr13** [comment]
`ERROR::jellyfin_kodi\jellyfin\http.py:160 --[ 500 response ] 500 Server Error: Internal Server Error for url: http://{jellyfin-server}/Users/…/Items?…`

I need the corresponding *server* logs.

**Comment by valpamp** [comment]
Whoops, sorry, [this](https://github.com/user-attachments/files/16561946/jellyfin.log) should be it.

**Comment by oddstr13** [comment]
Seems related to jellyfin/jellyfin#11796, jellyfin/jellyfin#11528 and probably others.

> This should not happen as this would only happen with incorrectly packaged versions. But we do aware that some old environment variable/config might be leftover if you just re-pull the image. Can you check if your container has the env variable `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` set to `true` or `1` ? This is a wrong configuration for 10.9 now and if it does you need to change it to 0 or just remove this env variable.

_Originally posted by @gnattu in https://github.com/jellyfin/jellyfin/issues/11528#issuecomment-2105568202_

**Comment by valpamp** [comment]
Spot on, I redeployed my container after setting the environment variable to 0 and the sync completed successfully on two separate devices. Thanks!
