### ISSUE TITLE
Resuming media plays from incorrect time

### ISSUE THREAD

**Issue by ChocOranger** [jellyfin/jellyfin-kodi#912]
**Describe the bug**
When resuming a movie the time displayed in Kodi's context popup for resume is correct (eg Resume from 00:13:45) will actually resume from around a minute or so before that time (eg 00:12:45). Actual time appears to vary depending on how far played (eg  1:08:31 resumes @ 1:07:07)
The jumpback on resume time is the default of 10 seconds.
I originally posted on the Jellyfin forum https://forum.jellyfin.org/t-jellyfin-kodi-addon-resuming-media-jumps-back-about-a-minute with one other person replying they had the same issue. Nobody replied it was working correctly for them.

**To Reproduce**
1. Play a movie
2. Stop the movie part way through noting the time played
3. Restart the movie and the resume from should be the time played in step 2 minus jumpback time.
4. Actual restart position is around a minute earlier than displayed in the Kodi context menu.

**Expected behavior**
Movie restarts from the stopped time minus the jumpback on resume time.

**Logs**
Couldn't see any relevant log errors

**Screenshots**

**System (please complete the following information):**
All versions latest stable available. Clean installs of portable versions to test
- OS: Windows 10. Also happens on Shield Pro.
- Jellyfin Version: 10.9.9
- Kodi Version: 21.1 Portable. Default skin with no extra addons.
- Addon Version:  10.0.4 + py3
- Playback Mode: Add-On

**Additional context**
Kodi without jellyfin resumes correctly.
Jellyfin web interface resumes correctly.
Jellyfin addon causes a jumpback of around a minute from the time shown in Kodi's context window.

**Comment by sic6SaNdMaN** [comment]
I can confirm this problem.
It occurs to me since I switched from "native paths" to "AddOn mode" due to this discussion:
https://github.com/jellyfin/jellyfin/discussions/11654

I never switched back to "native paths" because I want to test "AddOn mode" more, if I can find anymore issues.
And I think, that this IS an issue with AddOn mode - I never experienced this behavious with native paths.

**Comment by sic6SaNdMaN** [comment]
More Info: I'm pretty sure, that the resuming time is always exactly one minute before the actual stopping time.
So the configured time isn't used, it's always 60 seconds instead.

**Comment by bossanova808** [comment]
I am surprised this bug isn't getting more noise.  In general this addon works amazingly well (in addon mode, I have not tried native paths mode) - but this is a bit of a show-stopper really - resume behaviour is all over the place with Jellyfin for Kodi, and resume is a very basic and necessary part of a reliable media system.

On resume, it's often some seconds, or a minute or two, behind.  Or it's way back.  Or it starts from the beginning.  It's a mess.

In all these cases, Kodi seems to report the correct resume time in its own resume dialogue, so it leads me to think the issue is with some sort of issue with the reporting of playback progress to Jellyfin and/or a race condition or similar when Jellyfin updates the Kodi library...

I'm trying to look in to it but it's all a bit complicated...I can see e.g. the the `204` response from:
https://api.jellyfin.org/#tag/Playstate/operation/ReportPlaybackProgress

...results in exceptions at [response = r.json()](https://github.com/jellyfin/jellyfin-kodi/blob/2c407039ff59a6b6936406446cb5340f3bb73426/jellyfin_kodi/jellyfin/http.py#L184) - as the json is empty.  But I can also see the progress updating as expected in the Jellyfin dashboard, so the Kodi -> JF reporting is working ok best I can tell.  And given the Kodi resume time seems right in the presented dialogue, it's something about the resume at the JF end itself that seems to fail in this case (resume from the JF web UI is correct).

Is there some sort of guide/doc to this addon/development of it, anywhere?

**Comment by bossanova808** [comment]
This bug has been driving my family to distraction.   The behaviour is just all over the place - with resumes ranging from some seconds off, to many minutes, to complete resets back to the start.  Compared to everything else about the JF for Kodi addon, which works a treat, it's just a bizarre miss on a very basic and necessary playback function.  I have begun digging in to the JF for Kodi code to try and tackle the issue in a proper way, but it's a bit of a beast of an addon compared to the simpler things I am used to working on.

**So - in the meantime, I have made a Monkey Patch addon to try and solve this issue another way.**  

### New addon: Jellyfin Fixer

This hacked together addon intercepts the start of all movie and TV episode playbacks and queries the Kodi DB for the current resume point (which is correct, as is easy to confirm visually when you get the 'Resume from XX:XX / Play From Beginning' pop up).

If a resume point is set, it performs a post-start-of-playback seek to that exact point (or a few configurable seconds before, if you prefer). 

**Pros**
This works pretty much perfectly and solves the resume point failures (implying it really should be possible to solve in JF for Kodi directly - even if it's with a similar but in-built approach, it would be better than current behaviour!).  It's essentially seamless and without jank (you will see the seek in the UI but it's very fast and happens before playback as such really begins, at least on my systems (Ugoos AM6s with CE, or Windows PCs).  Interestingly, if you watch the UI indication of the seek that happens (which displays the offset from correct) - you will see the near random resumes that normally happen.  

**Cons**
There is no reliable way to detect, when playback is triggered, that 'Play From Beginning' has been selected instead of resume.  Kodi doesn't seem to immediately clear the resume point, and indeed I suspect it internally does a seek to handle thus, thus so far I can only find janky ways of going back to the beginning, after a few seconds have played.  I don't like that behaviour, and since I basically never use 'Play From Beginning' in practice, I am happy to live without this working...so this is a compromise to be aware of.  

**Extras**
The addon also allows you to set up a seek to occur after playback from the beginning of a file...this seeks seems to help solve another problem, which is the slow display of subtitles.  It's not as foolproof as the resume behaviour fix, and a little janky (you can control when this seek to 0 occurs, by default after 1 second of playback) - but it does seem to result in subs coming up quicker (see refs https://github.com/jellyfin/jellyfin-kodi/issues/35, https://github.com/xbmc/xbmc/issues/21086 etc - long standing Kodi problem, but the behaviour is noticeably worse with http streaming as JF for Kodi uses, vs. NFS/SMB)

**Installation**
Grab the (zip for my repo)[https://github.com/bossanova808/repository.bossanova808/raw/refs/heads/main/repository-downloads/repository.bossanova808/repository.bossanova808-0.2.7.zip].  'Install from zip', then from there install via `Services -> Jellyfin Fixer`

**Issues** 
Please do NOT report any issues here - I am sure @oddstr13 can do without the extra noise!  Feel free to create an issue on the repo here: https://github.com/bossanova808/repository.bossanova808/issues

**Comment by JulioQc** [comment]
Y'all aware there's an option to configure this jump back?

![Image](https://github.com/user-attachments/assets/bdd67140-688d-45bd-977a-75a114d129fb)

**Comment by bossanova808** [comment]
Yep, definitely aware, but it doesn't work/work properly. No matter what it is set to, including 0, wildly variable resume behaviour...

**Comment by sic6SaNdMaN** [comment]
Are you waiting long enough for Kodi sending the resume point to Jellyfin and then syncing it back from there?
It can take up to one minute.

I'm still using native paths since nearly a year now. But this also has some flaws.
But resuming works very good - only problem is, that it is always 10 seconds, no matter what I configure it to be.
But that's tolerable.

I just have to wait for the sync.
You see the sync indicator eventually in the upper right corner, like always, but in this case only for a fraction of a second.
That's where Jellyfin is not neary as fast as Emby was in my tests, years ago.

I'm planning to set up the newest (beta?) version of Kodi in parallel on my Shield. 
Since the data is not shared, I can start from scratch and will therefore give AddOn-mode another fresh try.

I'm curious, if I can confirm the behaviour you're describing.

**Comment by JulioQc** [comment]
> Are you waiting long enough for Kodi sending the resume point to Jellyfin and then syncing it back from there? It can take up to one minute.
> 
> I'm still using native paths since nearly a year now. Bit this also has some flaws. But resuming works very good - only problem is, that it is always 10 seconds, no matter what I configure it to be. But that's tolerable.
> 
> I just have to wait for the sync. You see the sync indicator eventually in the upper right corner, like always, but in this case only for a fraction of a second. That's where Jellyfin is not neary as fast as Emby was in my tests, years ago.
> 
> I'm planning to set up the newest (beta?) version of Kodi in parallel on my Shield. Since the data is not shared, I can start from scratch and will therefore give AddOn-mode another fresh try.
> 
> I'm curious, if I can confirm the behaviour you're describing.

Are you talking to me about #1048 ?

**Comment by sic6SaNdMaN** [comment]
> Are you talking to me about [#1048](https://github.com/jellyfin/jellyfin-kodi/issues/1048) ?

Sorry, I was replying to @bossanova808.
But perhaps it's applicable to both issues?

**Comment by bossanova808** [comment]
Yep I am waiting long enough.  

Typically, the small post playback sync is rarely longer than a few seconds on my system, but I have of course tried waiting (much) longer.  This behaviour happens shortly after, but also literally days after.  The most common behaviour is resumes ~ a minute back, but sometimes it's more or less, and sometimes it totally resets to the start (as per #1048).  

I am using add-on mode.  I haven't tried native, am a relative newcomer to JF and all the warnings implied that was not the future. (...also, I want to take my system when travelling and access the home server and stream, via Tailscale, which I imagine will be at best fiddly/at worst impossible, using native mode).

In case it matters:

My main systems are 2 * Ugoos AM6B+ with CE-ng and Omega.   
(These machines are used every day by our family of 4, so in total the testing is extensive and encompasses many stops/starts and scenarios - the incorrect resumes are consistent).

This behaviour also happens on a Win 11 64-bit monster of a workstation PC where I do my Kodi addon development (including the fixer addon above which works very well!)

And also with Kodi on an Android tablet (although there I in practise use the Jellyfin client, and that resumes as expected).

Server is Jellyfin on an Ubuntu 24.04 LTS Server (running in an LXC on Proxmox on a beast of a server).

(All things connected by 2.5gbe wired networking where available or 1gbe if not (e.g. Ugoos))

**Comment by ChocOranger** [comment]
Just thought I'd say thanks for the Jellyfin Fixer addon. It works great.

Strangely I've never had a resume go back and restart from the beginning. Not that I've noticed anyway.
Roughly, how often does it happen for you?

**Comment by bossanova808** [comment]
Glad it is working for you.

Resumes from the beginning are probably...1 in 10 or less?  Not nearly as frequent as the 'just being off by an annoying amount issue', anyway.  But they do happen.  With the Fixer it's not really an issue in practise, but you can occasionally see a flash of the opening credits before the Fixer seek happens, so yeah, it definitely happens.

**Comment by oddstr13** [comment]
Quite possibly related to #538.

I don't personally use resume much, but the times I have seen the playback progress reset to start seem to be happening more often when there is some form of playback issue causing the playback to stop right after starting.

**Comment by bossanova808** [comment]
@oddstr13 Yes that feels like it _might_ well be related.  

(As it happens I have seen those same errors at times in my logs (`Error Contents: name 'ValueError' is not defined` as well - and my LAN is definitely not 'poo'!)...given it seems to be a relatively simple import error, might be worth addressing? -> those issues certainly can't be helping, anyway!)

I don't think I have seen anything in the logs indicating playback issues when the resume errors (start or otherwise) happen, but I will look out for it.

I see you've tagged this as 'help wanted' - I am very happy to help and dig in to the problem if I can, just let me know what I can do.

**Comment by oddstr13** [comment]
If you are seeing `name 'ValueError' is not defined` in your logs, something is *very* wrong, as that is a Python builtin which should always be present (no need to import it). (When I say very wrong here, I mean Kodi's Python implementation is broken on your install or something similarly severe).

I'd need more log context to be able to more accurately judge what is going on there.

<img width="569" height="241" alt="Image" src="https://github.com/user-attachments/assets/b81fe267-f20e-40fd-9c14-90837f6c0ad8" />

I marked as help wanted mainly because I am unlikely to prioritize spending time figuring out what is actually going on here anytime soon.

The number of times I pause a movie mid-way to continue watching a different day is almost non-existant, which means it doesn't really register on my personal annoyance list (the mark completed issue is on that list, but not very high).

As for docs on how to contribute to this repo in particular? The code. Otherwise, there is the [Jellyfin contribution guidelines](https://jellyfin.org/docs/general/contributing#developing-code) and general git(hub) best practices.
I haven't written up anything specific to this client.

**Comment by bossanova808** [comment]
(Must be nice to be able to watch whole movies through end to end without interruptions!!  (I am guessing maybe you don't have kids!).  In any case, unfortunately, for us, relaxing is often in shorter bursts.  And I am sure we are not alone in that. I would be confident, though, that it would generally be agreed that accurate resuming is kind of 'Media Player 101').

So far my efforts to fix all these seemingly related issues have been to make the addon, which goes a long way to patching around the issue - but is of course hardly ideal.  I guess next I will try and dig in to the addon itself, but it's a bit of behemoth with a lot of spaghetti like back and forth communication, so to date I have found it a little hard to get started with.

More specifically: 

The `ValueError` currently can at occasional times be seen to happen on both Kodi installed under Windows (Omega and Piers) and Kodi CoreELEC (and O and P) - and as per the discussion in https://github.com/jellyfin/jellyfin-kodi/issues/538 _looks_ to be something about how the Kodi requests module imports `simplejson`/`json`.  

Those installations types don't use system Python, so it can't really be reasonably blamed on a problem with a specific Python environment, other than that which the various packagings of Kodi provide.   But it might well be (probably is?) something about the packaging of that module, in those contexts..but also fair to say I've used a whole bunch of Kodi addons that use requests, over many years, and those _don't_ experience that error...so there seems to something about the combination of JF for Kodi and requests that triggers the problem (with these very standard installations - indeed they're likely the most popular types of Kodi installs...)

All that being said, I am not even sure that theses errors are specifically related to this problem...it was just you pointed at that issue and I happened to notice something in those logs I had also, at times, seen in my own, so I thought it might be useful information.

**Comment by bossanova808** [comment]
Ok just for extra info, here is a Kodi and Jellyfin debug level log of a file being played back, stopped, and then resumed - consecutively several times (with time in-between to allow for Jellyfin to update Kodi... (which can be seen as having occurred, given the title changes from (after Playback) a bare version of the title 'Orangutans' to the '1x03 Orangutans' title expected...and that is seen _before_ playback).  

(N.b. the Jellyfin resume seconds is set to 0 in the (vain) hope of achieving the correct resume point.)

In each case, you can see my Jellfyin Fixer addon intervening (add `onAvStarted` to detect the issue and fix up the incorrect resume by seeking to the right spot:

```
### Jellyfin Fixer 0.0.4: Currently playing time: 695.967, Kodi resume: 719.0, difference: 23.0
### Jellyfin Fixer 0.0.4: Currently playing time: 695.974, Kodi resume: 713.0, difference: 17.0
### Jellyfin Fixer 0.0.4: Currently playing time: 695.974, Kodi resume: 707.0, difference: 11.0
### Jellyfin Fixer 0.0.4: Currently playing time: 713.977, Kodi resume: 722.0, difference: 8.0
### Jellyfin Fixer 0.0.4: Currently playing time: 749.975, Kodi resume: 768.0, difference: 18.0
```

So the resume point is off, 5 out of 5 times.

Apologies the log is too long for pastebin etc, but both the Kodi and JF debug logs pump out a lot of stuff!

https://gist.github.com/bossanova808/089b533dbd2ae5761f35a7eccbbb6ae0/raw/f4ad3247d6ec11956a1efe278614986f9291d7f6/gistfile1.txt

**Comment by bossanova808** [comment]
I thought I'd throw coderabbitai at the problem as I have been experimenting with that lately (https://github.com/bossanova808/jellyfin-kodi/issues/1)

It pointed out this line: https://github.com/jellyfin/jellyfin-kodi/blob/2f7cf9b24d54f7c2c25f7325107871049dc9813b/jellyfin_kodi/objects/actions.py#L512

from
```
            if obj["Resume"] and item.get("resumePlayback"):
                listitem.setProperty("resumetime", str(obj["Resume"]))
                listitem.setProperty(
                    "StartPercent", str(((obj["Resume"] / obj["Runtime"]) * 100) - 0.40)
                )
```

...which is a bit of a bizarre line really. (Like, why have that seemingly random 0.40 , for example? 

I may well be ignorant of something here, and if so I apologise in advance - but I've never actually seen StartPercent used before.

In my own plugin (Switchback) I have recently been creating and experimenting with a whole bunch of video listitems and resumes (for Kodi library items (from JF), but also add-ons, PVR live/recording playbacks etc etc) - and they can all use resumetime rather than StartPercent. I presume StartPercent exists because of some other scenarios I don't know about, but in standard Kodi video playbacks, it's not needed (or generally used, at least as far as I've ever seen).

At the very least, I'd think setting both a resumetime and a StartPercent is going to confuse Kodi. And a quick test confirms that simply removing the SetPercent immediately makes the JF for Kodi resumes behave dramatically more accurately. I really don't think, if an actual resumetime is available (as confirmed by the if immediately above) - there is any point setting StartPercent - indeed it's only going to do harm.

The other issues - going back to the start and the occasional lazarus behaviour with watched episodes - are likely not going to be solved by this fix, but I think the general resume inaccuracy will be.

(Looking deeper, I think maybe you're using this because of potential transcodes maybe?  If so, I'd recommend (in those cases) getting Kodi to do an explicit seek `onAVStarted` (as per my fixer addon) as an alternative to this inherently innacurate `SetPercent` approach...but I just don't have the experience/context yet to tackle that properly and I don't really use transcodes with Kodi personally...kind of half the point of swiss-army-knife Kodi really!).

**Comment by bossanova808** [comment]
And just while poking through some logs just now I see this (Kodi Omega, CoreELEC)

```
2025-10-11 21:48:23.125 T:4765    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'ValueError' is not defined
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 168, in onNotification
                                                       self.player.report_playback(data.get("Report", True))
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/player.py", line 388, in report_playback
                                                       item["Server"].jellyfin.session_progress(data)
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 359, in session_progress
                                                       return self.sessions("/Playing/Progress", "POST", json=data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 80, in sessions
                                                       return self._post("Sessions%s" % handler, json, params)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 64, in _post
                                                       return self._http("POST", handler, {"params": params, "json": json})
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 58, in _http
                                                       return self.client.request(request)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/http.py", line 185, in request
                                                       response = r.json()
                                                                  ^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 971, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
                                                     File "/usr/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
                                                     File "/usr/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
                                                     File "/usr/lib/python3.11/site-packages/simplejson/errors.py", line 41, in __init__
                                                   NameError: name 'ValueError' is not defined
                                                   -->End of Python script error report<--
                                                   
```

...which is one of those errors happening as the addon is trying to report playback progress to the server, from what I can see...so definitely does seem like it might be related.

**Comment by oddstr13** [comment]
The ValueError issue is definetely an upstream issue, and probably related to #521 in some way.
It would only be visible on systems where simplejson is installed in the system packages (and Kodi's Python being configured to import from system wide python install). I have absolutely no idea of how that error occurs in the first place, but it is an upstream issue that we might have to hack around. I see that the issue is mentioned in other issues, but at least one of those where self-closed without being properly adressed - move that part of the discussion over there (it mentioned modifying the requests file to work around it), I'd link it, but I'm on mobile right now, so going back and forth between search and here is... cumbersome. Just summarize what you've found about it, and link back here, and I'll reopen that issue.

As for the StartPercent, that part of the code is largely unmodified since the fork from the Emby addon, so I don't know the rationale behind why any part of it works as it does. Only minor adjustments to accommodate other refractors, or code formatting/linting, as far as I could see. (Using blame view on github, you can click on "show blame before" or some such, and it'll go back past the particular change of that section)

**Comment by bossanova808** [comment]
Ok I think I found the issue you mean & commented there, and have moved discussion about `StartPercent` etc over to the PR.  Thanks for looking at this.  (I live in Australia so apologies as that means the back and forth gets a bit delayed!)

**Comment by bossanova808** [comment]
I've been using the fix in the (now-merged) PR (https://github.com/jellyfin/jellyfin-kodi/pull/1051) for several days now and it has solved the issues with consistently incorrect resume times I was experiencing.  So I expect this fix will come along whenever the next release of this addon is made (and until then my 'Fixer' addon solves the issue too).

(I have not seen any random jump back to 0s either, since using the proper fix - but not 100% sure that is solved as that was only occasional).

**Comment by ChocOranger** [comment]
I also applied the fix from your PR https://github.com/jellyfin/jellyfin-kodi/pull/1051 last night, disabled your fixer addon and have tested quite a bit on a windows 10 pc and a Shield Pro. Everything seems to work as expected.
Many thanks for finding a fix.
Happy to close this issue.
