### ISSUE TITLE
Tracks not getting imported from album

### ISSUE THREAD

**Issue by csaavedra** [jellyfin/jellyfin-kodi#913]
I recently added David Gilmour's new album to my Jellyfin library. It has two songs that a credit artist: "David Gilmour with Romany Gilmour", and these songs are not imported to Kodi.

Here is the log from the import:

```
2024-09-09 15:00:35.908 T:16779    info <general>: JELLYFIN.jellyfin_kodi.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:329 [ LibraryChanged ] {'CollectionFolders': ['a656b907eb3a73532e40e44b968d0225', 'f137a2dd21bbc1b99aa5c0f6bf02a805', '7e64e319657a9516ec78490da03edccb', '1071671e7bffa0532e930debee501d2e'], 'FoldersAddedTo': ['7b2b68c276e1abeee9b849570c4411cc', 'bed72bbb6d94e02236988744c5f607a0'], 'FoldersRemovedFrom': [], 'IsEmpty': False, 'ItemsAdded': ['bed72bbb6d94e02236988744c5f607a0', '21385e22393fe63e7c4e1933ee0f6a81', '3c805223b3dface55c87b62ab91c91e1', '7c76d6f733f6bd8b2f4f592f13eae378', '581d28c99aba4c14f5637c9b2b16037b', '25981b6834f4d272e5488059acb03345', '391db6081896e05c18457223432dfab4', '474b077d7db37306b668f04afb6082c5', '0be513ec96910f4853122a54a5735778', '658e10b4319e5ba10fcd778f7c73c601', 'ea8a1797ed7f643270487e7b385fb3a6', '0edae296fe2c222a5f2d3f7391297656'], 'ItemsRemoved': [], 'ItemsUpdated': []}
2024-09-09 15:00:35.916 T:16779    info <general>: JELLYFIN.jellyfin_kodi.library -> INFO::jellyfin_kodi/library.py:671 ---[ updated:12 ]
2024-09-09 15:00:35.978 T:16784    info <general>: JELLYFIN.jellyfin_kodi.library -> INFO::jellyfin_kodi/library.py:283 -->[ q:download/1341629656 ]
2024-09-09 15:00:37.235 T:17441    info <general>: JELLYFIN.jellyfin_kodi.downloader -> INFO::jellyfin_kodi/downloader.py:314 --<[ q:download/1341629656 ]
2024-09-09 15:00:38.000 T:16784    info <general>: JELLYFIN.jellyfin_kodi.library -> INFO::jellyfin_kodi/library.py:321 -->[ q:updated/MusicAlbum/1341629656 ]
2024-09-09 15:00:41.283 T:17442    info <general>: JELLYFIN.jellyfin_kodi.library -> INFO::jellyfin_kodi/library.py:767 --<[ q:updated/1341629656 ]
2024-09-09 15:00:42.064 T:16784    info <general>: JELLYFIN.jellyfin_kodi.library -> INFO::jellyfin_kodi/library.py:321 -->[ q:updated/Audio/1324218424 ]
2024-09-09 15:00:44.346 T:17443    info <general>: JELLYFIN.jellyfin_kodi.helper.utils -> ERROR::jellyfin_kodi/helper/utils.py:523 No ancestor found, not syncing item with ID: b6ee93e5ccaea024cc6439c93153c30d
2024-09-09 15:00:44.364 T:17443    info <general>: JELLYFIN.jellyfin_kodi.objects.music -> ERROR::jellyfin_kodi/objects/music.py:471 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/objects/music.py", line 460, in song_artist_link
                                                       temp_obj["ArtistId"] = self.jellyfin_db.get_item_by_id(
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/objects/music.py", line 467, in song_artist_link
                                                       temp_obj["ArtistId"] = self.jellyfin_db.get_item_by_id(
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   
2024-09-09 15:00:47.104 T:17443    info <general>: JELLYFIN.jellyfin_kodi.helper.utils -> ERROR::jellyfin_kodi/helper/utils.py:523 No ancestor found, not syncing item with ID: b6ee93e5ccaea024cc6439c93153c30d
2024-09-09 15:00:47.116 T:17443    info <general>: JELLYFIN.jellyfin_kodi.objects.music -> ERROR::jellyfin_kodi/objects/music.py:471 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/objects/music.py", line 460, in song_artist_link
                                                       temp_obj["ArtistId"] = self.jellyfin_db.get_item_by_id(
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/objects/music.py", line 467, in song_artist_link
                                                       temp_obj["ArtistId"] = self.jellyfin_db.get_item_by_id(
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   
2024-09-09 15:00:51.244 T:17443    info <general>: JELLYFIN.jellyfin_kodi.library -> INFO::jellyfin_kodi/library.py:767 --<[ q:updated/1324218424 ]
2024-09-09 15:00:52.213 T:16784    info <general>: JELLYFIN.jellyfin_kodi.library -> INFO::jellyfin_kodi/library.py:541 --[ sync/2024-09-09T11:58:48z ]
```

**Comment by csaavedra** [comment]
Jellyfin: 10.9.10
Kodi Sync Queue: 11.0.0.0
Jellyfin-Kodi: 1.0.5
